name: aix_devices
fqcn: community.general.aix_devices
collection: community.general
short_description: Manages AIX devices
description: This module discovers, defines, removes and modifies attributes of AIX devices.
options:
  attributes:
    type: dict
    description: A list of device attributes.
  device:
    type: str
    description: The name of the device. V(all) is valid to rescan C(available) all devices (AIX cfgmgr
      command).
  force:
    type: bool
    default: false
    description: Forces action.
  recursive:
    type: bool
    default: false
    description: Removes or defines a device and children devices.
  state:
    type: str
    default: available
    choices:
    - available
    - defined
    - removed
    description: Controls the device state. V(available) (alias V(present)) rescan a specific device or
      all devices (when O(device) is not specified). V(removed) (alias V(absent) removes a device. V(defined)
      changes device to Defined state.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Scan new devices\n  community.general.aix_devices:\n    device: all\n    state: available\n\
  \n- name: Scan new virtual devices (vio0)\n  community.general.aix_devices:\n    device: vio0\n    state:\
  \ available\n\n- name: Removing IP alias to en0\n  community.general.aix_devices:\n    device: en0\n\
  \    attributes:\n      delalias4: 10.0.0.100,255.255.255.0\n\n- name: Removes ent2\n  community.general.aix_devices:\n\
  \    device: ent2\n    state: removed\n\n- name: Put device en2 in Defined\n  community.general.aix_devices:\n\
  \    device: en2\n    state: defined\n\n- name: Removes ent4 (inexistent).\n  community.general.aix_devices:\n\
  \    device: ent4\n    state: removed\n\n- name: Put device en4 in Defined (inexistent)\n  community.general.aix_devices:\n\
  \    device: en4\n    state: defined\n\n- name: Put vscsi1 and children devices in Defined state.\n\
  \  community.general.aix_devices:\n    device: vscsi1\n    recursive: true\n    state: defined\n\n-\
  \ name: Removes vscsi1 and children devices.\n  community.general.aix_devices:\n    device: vscsi1\n\
  \    recursive: true\n    state: removed\n\n- name: Changes en1 mtu to 9000 and disables arp.\n  community.general.aix_devices:\n\
  \    device: en1\n    attributes:\n      mtu: 900\n      arp: 'off'\n    state: available\n\n- name:\
  \ Configure IP, netmask and set en1 up.\n  community.general.aix_devices:\n    device: en1\n    attributes:\n\
  \      netaddr: 192.168.0.100\n      netmask: 255.255.255.0\n      state: up\n    state: available\n\
  \n- name: Adding IP alias to en0\n  community.general.aix_devices:\n    device: en0\n    attributes:\n\
  \      alias4: 10.0.0.100,255.255.255.0\n    state: available\n"
