name: bearychat
fqcn: community.general.bearychat
collection: community.general
short_description: Send BearyChat notifications
description: The M(community.general.bearychat) module sends notifications to U(https://bearychat.com)
  via the Incoming Robot integration.
options:
  attachments:
    type: list
    description: Define a list of attachments. For more information, see https://github.com/bearyinnovative/bearychat-tutorial/blob/master/robots/incoming.md#attachments
  channel:
    type: str
    description: Channel to send the message to. If absent, the message goes to the default channel selected
      by the O(url).
  markdown:
    type: bool
    default: true
    description: If V(true), text will be parsed as markdown.
  text:
    type: str
    description: Message to send.
  url:
    type: str
    required: true
    description: BearyChat WebHook URL. This authenticates you to the bearychat service. It looks like
      V(https://hook.bearychat.com/=ae2CF/incoming/e61bd5c57b164e04b11ac02e66f47f60).
writes: true
runtime: starlark
source: translated
examples: "\n- name: Send notification message via BearyChat\n  local_action:\n    module: bearychat\n\
  \    url: |\n      https://hook.bearychat.com/=ae2CF/incoming/e61bd5c57b164e04b11ac02e66f47f60\n   \
  \ text: \"{{ inventory_hostname }} completed\"\n\n- name: Send notification message via BearyChat all\
  \ options\n  local_action:\n    module: bearychat\n    url: |\n      https://hook.bearychat.com/=ae2CF/incoming/e61bd5c57b164e04b11ac02e66f47f60\n\
  \    text: \"{{ inventory_hostname }} completed\"\n    markdown: false\n    channel: \"#ansible\"\n\
  \    attachments:\n      - title: \"Ansible on {{ inventory_hostname }}\"\n        text: \"May the Force\
  \ be with you.\"\n        color: \"#ffffff\"\n        images:\n          - http://example.com/index.png\n"
