name: btrfs_info
fqcn: community.general.btrfs_info
collection: community.general
short_description: Query btrfs filesystem info
description: Query status of available btrfs filesystems, including uuid, label, subvolumes and mountpoints.
options: {}
writes: false
runtime: starlark
source: translated
examples: "\n\n- name: Query information about mounted btrfs filesystems\n  community.general.btrfs_info:\n\
  \  register: my_btrfs_info\n\n"
