name: clc_blueprint_package
fqcn: community.general.clc_blueprint_package
collection: community.general
short_description: Deploys a blue print package on a set of servers in CenturyLink Cloud
description: An Ansible module to deploy blue print package on a set of servers in CenturyLink Cloud.
options:
  package_id:
    type: str
    required: true
    description: The package id of the blue print.
  package_params:
    type: dict
    default: {}
    description: The dictionary of arguments required to deploy the blue print.
  server_ids:
    type: list
    required: true
    description: A list of server Ids to deploy the blue print package.
  state:
    type: str
    default: present
    choices:
    - present
    description: Whether to install or uninstall the package. Currently it supports only "present" for
      install action.
  wait:
    type: str
    default: 'True'
    description: Whether to wait for the tasks to finish before returning.
writes: true
runtime: starlark
source: translated
examples: "\n# Note - You must set the CLC_V2_API_USERNAME And CLC_V2_API_PASSWD Environment variables\
  \ before running these examples\n\n- name: Deploy package\n  community.general.clc_blueprint_package:\n\
  \        server_ids:\n            - UC1TEST-SERVER1\n            - UC1TEST-SERVER2\n        package_id:\
  \ 77abb844-579d-478d-3955-c69ab4a7ba1a\n        package_params: {}\n"
