name: consul_binding_rule
fqcn: community.general.consul_binding_rule
collection: community.general
short_description: Manipulate Consul binding rules
description: Allows the addition, modification and deletion of binding rules in a consul cluster via the
  agent. For more details on using and configuring binding rules, see U(https://developer.hashicorp.com/consul/api-docs/acl/binding-rules).
options:
  auth_method:
    type: str
    required: true
    description: The name of the auth method that this rule applies to.
  bind_name:
    type: str
    description: The name to bind to a token at login-time. What it binds to can be adjusted with different
      values of the O(bind_type) parameter.
  bind_type:
    type: str
    choices:
    - service
    - node
    - role
    - templated-policy
    description: Specifies the way the binding rule affects a token created at login.
  bind_vars:
    type: dict
    description: Specifies the templated policy variables when O(bind_type) is set to V(templated-policy).
  ca_path:
    type: str
    description: The CA bundle to use for https connections
  description:
    type: str
    description: Free form human readable description of the binding rule.
  host:
    type: str
    default: localhost
    description: Host of the consul agent, defaults to V(localhost).
  name:
    type: str
    required: true
    description: 'Specifies a name for the binding rule. Note: This is used to identify the binding rule.
      But since the API does not support a name, it is prefixed to the description.'
  port:
    type: int
    default: 8500
    description: The port on which the consul agent is running.
  scheme:
    type: str
    default: http
    description: The protocol scheme on which the consul agent is running. Defaults to V(http) and can
      be set to V(https) for secure connections.
  selector:
    type: str
    description: Specifies the expression used to match this rule against valid identities returned from
      an auth method validation. If empty this binding rule matches all valid identities returned from
      the auth method.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Whether the binding rule should be present or absent.
  token:
    type: str
    description: The token to use for authorization.
  validate_certs:
    type: bool
    default: true
    description: Whether to verify the TLS certificate of the consul agent.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create a binding rule\n  community.general.consul_binding_rule:\n    name: my_name\n\
  \    description: example rule\n    auth_method: minikube\n    bind_type: service\n    bind_name: \"\
  {{ serviceaccount.name }}\"\n    token: \"{{ consul_management_token }}\"\n\n- name: Remove a binding\
  \ rule\n  community.general.consul_binding_rule:\n    name: my_name\n    auth_method: minikube\n   \
  \ state: absent\n"
