name: consul_token
fqcn: community.general.consul_token
collection: community.general
short_description: Manipulate Consul tokens
description: Allows the addition, modification and deletion of tokens in a consul cluster via the agent.
  For more details on using and configuring ACLs, see U(https://www.consul.io/docs/guides/acl.html).
options:
  accessor_id:
    type: str
    description: Specifies a UUID to use as the token's Accessor ID. If not specified a UUID will be generated
      for this field.
  ca_path:
    type: str
    description: The CA bundle to use for https connections
  description:
    type: str
    description: Free form human readable description of the token.
  expiration_ttl:
    type: str
    description: This is a convenience field and if set will initialize the C(expiration_time). Can be
      specified in the form of V(60s) or V(5m) (that is, 60 seconds or 5 minutes, respectively). Ingored
      when the token is updated!
  host:
    type: str
    default: localhost
    description: Host of the consul agent, defaults to V(localhost).
  local:
    type: bool
    description: If true, indicates that the token should not be replicated globally and instead be local
      to the current datacenter.
  node_identities:
    type: list
    description: List of node identities to attach to the token. If not specified, any node identities
      currently assigned will not be changed. If the parameter is an empty array (V([])), any node identities
      assigned will be unassigned.
  policies:
    type: list
    description: List of policies to attach to the token. Each policy is a dict. If the parameter is left
      blank, any policies currently assigned will not be changed. Any empty array (V([])) will clear any
      policies previously set.
  port:
    type: int
    default: 8500
    description: The port on which the consul agent is running.
  roles:
    type: list
    description: List of roles to attach to the token. Each role is a dict. If the parameter is left blank,
      any roles currently assigned will not be changed. Any empty array (V([])) will clear any roles previously
      set.
  scheme:
    type: str
    default: http
    description: The protocol scheme on which the consul agent is running. Defaults to V(http) and can
      be set to V(https) for secure connections.
  secret_id:
    type: str
    description: Specifies a UUID to use as the token's Secret ID. If not specified a UUID will be generated
      for this field.
  service_identities:
    type: list
    description: List of service identities to attach to the token. If not specified, any service identities
      currently assigned will not be changed. If the parameter is an empty array (V([])), any node identities
      assigned will be unassigned.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Whether the token should be present or absent.
  templated_policies:
    type: list
    description: The list of templated policies that should be applied to the role.
  token:
    type: str
    description: The token to use for authorization.
  validate_certs:
    type: bool
    default: true
    description: Whether to verify the TLS certificate of the consul agent.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create / Update a token by accessor_id\n  community.general.consul_token:\n    state:\
  \ present\n    accessor_id: 07a7de84-c9c7-448a-99cc-beaf682efd21\n    token: 8adddd91-0bd6-d41d-ae1a-3b49cfa9a0e8\n\
  \    roles:\n      - name: role1\n      - name: role2\n    service_identities:\n      - service_name:\
  \ service1\n        datacenters: [dc1, dc2]\n    node_identities:\n      - node_name: node1\n      \
  \  datacenter: dc1\n    expiration_ttl: 50m\n\n- name: Delete a token\n  community.general.consul_token:\n\
  \    state: absent\n    accessor_id: 07a7de84-c9c7-448a-99cc-beaf682efd21\n    token: 8adddd91-0bd6-d41d-ae1a-3b49cfa9a0e8\n"
