def main(ctx, params):
    name = params.get("name")
    value = params.get("value")
    user = params.get("user")
    cron_file = params.get("cron_file")
    insertafter = params.get("insertafter")
    insertbefore = params.get("insertbefore")
    state = params.get("state", "present")
    backup = params.get("backup", False)

    if not name:
        fail("You must specify 'name' to " + ("insert" if state == "present" else "remove") + " a cron variable")

    if state == "present" and value == None:
        fail("You must specify 'value' to insert a new cron variable")

    # Determine cron target
    cron_cmd = ctx.run(["which", "crontab"], mutates=False)
    if cron_cmd.rc != 0:
        fail("crontab not found on system")
    crontab_path = cron_cmd.stdout.strip()

    # Build command args
    def read_cmd():
        if cron_file:
            return []
        argv = [crontab_path, "-l"]
        if user:
            argv = [crontab_path, "-l", "-u", user]
        return argv

    def write_cmd(path):
        if cron_file:
            return []
        argv = [crontab_path, path]
        if user:
            argv = [crontab_path, "-u", user, path]
        return argv

    # Read current crontab lines
    lines = []
    if cron_file:
        if not ctx.file_exists(cron_file):
            pass  # file does not exist → empty
        else:
            content = ctx.file_read(cron_file)
            lines = content.splitlines()
    else:
        res = ctx.run(read_cmd(), mutates=False)
        if res.rc not in (0, 1):  # 1 can mean empty crontab
            fail("Unable to read crontab: " + res.stderr)
        # Skip Ansible's standard header lines
        skip_count = 0
        for line in res.stdout.splitlines():
            if skip_count < 3:
                # Skip header lines Ansible adds
                if "# DO NOT EDIT THIS FILE" in line or \
                   "(#/tmp/" in line and "installed on" in line or \
                   "(." in line and "version" in line:
                    skip_count += 1
                    continue
            lines.append(line)

    # Parse crontab variable lines
    def parse_var_line(line):
        eq_pos = line.find("=")
        if eq_pos == -1:
            return None
        varname = line[:eq_pos].strip()
        if not varname.isidentifier():
            return None
        value_part = line[eq_pos + 1:].strip()
        return varname, value_part

    def find_var(varname):
        for l in lines:
            parsed = parse_var_line(l)
            if parsed and parsed[0] == varname:
                return parsed[1]
        return None

    def get_var_names():
        names = []
        for l in lines:
            parsed = parse_var_line(l)
            if parsed:
                names.append(parsed[0])
        return names

    # Backup handling
    backup_file = None
    if backup:
        backup_file = "/tmp/cronvar_backup_" + str(hash(name))[:8]
        ctx.file_write(backup_file, ctx.run(["echo", ""], mutates=False).stdout + "\n", "0644")  # dummy write to reserve path
        # Actually write backup in-place
        ctx.file_write(backup_file, "\n".join(lines) + "\n", "0644")

    # State logic
    old_value = find_var(name)
    changed = False

    if state == "present":
        if old_value == None:
            # Insert new variable
            newlines = []
            if insertbefore == None and insertafter == None:
                newlines = [name + "=" + value] + lines
            else:
                inserted = False
                for l in lines:
                    parsed = parse_var_line(l)
                    if parsed and not inserted:
                        if parsed[0] == insertbefore:
                            newlines.append(name + "=" + value)
                            newlines.append(l)
                            inserted = True
                        elif parsed[0] == insertafter:
                            newlines.append(l)
                            newlines.append(name + "=" + value)
                            inserted = True
                        else:
                            newlines.append(l)
                    else:
                        newlines.append(l)
                if not inserted:
                    newlines.append(name + "=" + value)
            lines = newlines
            changed = True
        elif old_value != value:
            # Update existing variable
            newlines = []
            for l in lines:
                parsed = parse_var_line(l)
                if parsed and parsed[0] == name:
                    newlines.append(name + "=" + value)
                else:
                    newlines.append(l)
            lines = newlines
            changed = True
    else:  # absent
        if old_value != None:
            newlines = []
            for l in lines:
                parsed = parse_var_line(l)
                if parsed and parsed[0] == name:
                    continue
                newlines.append(l)
            lines = newlines
            changed = True

    # Write back
    if changed:
        if cron_file:
            ctx.file_write(cron_file, "\n".join(lines) + "\n", "0644")
        else:
            # Write to temp and load via crontab
            tmp_path = "/tmp/cronvar_" + str(hash(name))[:8]
            ctx.file_write(tmp_path, "\n".join(lines) + "\n", "0644")
            res = ctx.run(write_cmd(tmp_path), mutates=True)
            if res.skipped:
                pass  # check_mode
            elif res.rc != 0:
                fail("Failed to write crontab: " + res.stderr)
            else:
                # Cleanup temp file
                ctx.run(["rm", "-f", tmp_path], mutates=False)

    # Build result
    result = {
        "changed": changed,
        "msg": "done" if not changed else "variable updated" if state == "present" else "variable removed",
        "vars": get_var_names()
    }

    if backup:
        if changed:
            result["backup_file"] = backup_file
        else:
            # Remove backup if unchanged
            ctx.run(["rm", "-f", backup_path], mutates=False)

    if cron_file:
        result["cron_file"] = cron_file

    return result
