name: dnsimple_info
fqcn: community.general.dnsimple_info
collection: community.general
short_description: Pull basic info from DNSimple API
description: Retrieve existing records and domains from DNSimple API.
options:
  account_id:
    type: str
    required: true
    description: The account ID to query.
  api_key:
    type: str
    required: true
    description: The API key to use.
  name:
    type: str
    description: The domain name to retrieve info from. Will return all associated records for this domain
      if specified. If not specified, will return all domains associated with the account ID.
  record:
    type: str
    description: The record to find. If specified, only this record will be returned instead of all records.
  sandbox:
    type: bool
    default: false
    description: Whether or not to use sandbox environment.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Get all domains from an account\n  community.general.dnsimple_info:\n    account_id:\
  \ \"1234\"\n    api_key: \"1234\"\n\n- name: Get all records from a domain\n  community.general.dnsimple_info:\n\
  \    name: \"example.com\"\n    account_id: \"1234\"\n    api_key: \"1234\"\n\n- name: Get all info\
  \ from a matching record\n  community.general.dnsimple_info:\n    name: \"example.com\"\n    record:\
  \ \"subdomain\"\n    account_id: \"1234\"\n    api_key: \"1234\"\n"
