name: dpkg_divert
fqcn: community.general.dpkg_divert
collection: community.general
short_description: Override a debian package's version of a file
description: A diversion is for C(dpkg) the knowledge that only a given package (or the local administrator)
  is allowed to install a file at a given location. Other packages shipping their own version of this
  file will be forced to O(divert) it, that is to install it at another location. It allows one to keep
  changes in a file provided by a debian package by preventing its overwrite at package upgrade. This
  module manages diversions of debian packages files using the C(dpkg-divert) commandline tool. It can
  either create or remove a diversion for a given file, but also update an existing diversion to modify
  its O(holder) and/or its O(divert) location.
options:
  divert:
    type: path
    description: The location where the versions of file will be diverted. Default is to add suffix C(.distrib)
      to the file path. This parameter is ignored when O(state=absent).
  force:
    type: bool
    default: false
    description: When O(rename=true) and O(force=true), renaming is performed even if the target of the
      renaming exists, i.e. the existing contents of the file at this location will be lost. This parameter
      is ignored when O(rename=false).
  holder:
    type: str
    description: The name of the package whose copy of file is not diverted, also known as the diversion
      holder or the package the diversion belongs to. The actual package does not have to be installed
      or even to exist for its name to be valid. If not specified, the diversion is hold by 'LOCAL', that
      is reserved by/for dpkg for local diversions. This parameter is ignored when O(state=absent).
  path:
    type: path
    required: true
    description: The original and absolute path of the file to be diverted or undiverted. This path is
      unique, i.e. it is not possible to get two diversions for the same O(path).
  rename:
    type: bool
    default: false
    description: Actually move the file aside (when O(state=present)) or back (when O(state=absent)),
      but only when changing the state of the diversion. This parameter has no effect when attempting
      to add a diversion that already exists or when removing an unexisting one. Unless O(force=true),
      renaming fails if the destination file already exists (this lock being a dpkg-divert feature, and
      bypassing it being a module feature).
  state:
    type: str
    default: present
    choices:
    - absent
    - present
    description: When O(state=absent), remove the diversion of the specified O(path); when O(state=present),
      create the diversion if it does not exist, or update its package O(holder) or O(divert) location,
      if it already exists.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Divert /usr/bin/busybox to /usr/bin/busybox.distrib and keep file in place\n  community.general.dpkg_divert:\n\
  \    path: /usr/bin/busybox\n\n- name: Divert /usr/bin/busybox by package 'branding'\n  community.general.dpkg_divert:\n\
  \    path: /usr/bin/busybox\n    holder: branding\n\n- name: Divert and rename busybox to busybox.dpkg-divert\n\
  \  community.general.dpkg_divert:\n    path: /usr/bin/busybox\n    divert: /usr/bin/busybox.dpkg-divert\n\
  \    rename: true\n\n- name: Remove the busybox diversion and move the diverted file back\n  community.general.dpkg_divert:\n\
  \    path: /usr/bin/busybox\n    state: absent\n    rename: true\n    force: true\n"
