name: ejabberd_user
fqcn: community.general.ejabberd_user
collection: community.general
short_description: Manages users for ejabberd servers
description: This module provides user management for ejabberd servers
options:
  host:
    type: str
    required: true
    description: the ejabberd host associated with this username
  logging:
    type: bool
    default: false
    description: enables or disables the local syslog facility for this module
  password:
    type: str
    description: the password to assign to the username
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: describe the desired state of the user to be managed
  username:
    type: str
    required: true
    description: the name of the user to manage
writes: true
runtime: starlark
source: translated
examples: "\n# Example playbook entries using the ejabberd_user module to manage users state.\n\n- name:\
  \ Create a user if it does not exist\n  community.general.ejabberd_user:\n    username: test\n    host:\
  \ server\n    password: password\n\n- name: Delete a user if it exists\n  community.general.ejabberd_user:\n\
  \    username: test\n    host: server\n    state: absent\n"
