name: facter
fqcn: community.general.facter
collection: community.general
short_description: Runs the discovery program C(facter) on the remote system
description: Runs the C(facter) discovery program (U(https://github.com/puppetlabs/facter)) on the remote
  system, returning JSON data that can be useful for inventory purposes.
options:
  arguments:
    type: list
    description: Specifies arguments for facter.
writes: true
runtime: starlark
source: translated
examples: "\n# Example command-line invocation\n# ansible www.example.net -m facter\n\n- name: Execute\
  \ facter no arguments\n  community.general.facter:\n\n- name: Execute facter with arguments\n  community.general.facter:\n\
  \    arguments:\n        - -p\n        - system_uptime\n        - timezone\n        - is_virtual\n"
