name: grove
fqcn: community.general.grove
collection: community.general
short_description: Sends a notification to a grove.io channel
description: The C(grove) module sends a message for a service to a Grove.io channel.
options:
  channel_token:
    type: str
    required: true
    description: Token of the channel to post to.
  icon_url:
    type: str
    description: Icon for the service
  message_content:
    type: str
    required: true
    description: Message content. The alias O(ignore:message) has been removed in community.general 4.0.0.
  service:
    type: str
    default: ansible
    description: Name of the service (displayed as the "user" in the message)
  url:
    type: str
    description: Service URL for the web client
  validate_certs:
    type: bool
    default: true
    description: If V(false), SSL certificates will not be validated. This should only be used on personally
      controlled sites using self-signed certificates.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Sends a notification to a grove.io channel\n  community.general.grove:\n    channel_token:\
  \ 6Ph62VBBJOccmtTPZbubiPzdrhipZXtg\n    service: my-app\n    message: 'deployed {{ target }}'\n"
