name: gunicorn
fqcn: community.general.gunicorn
collection: community.general
short_description: Run gunicorn with various settings
description: Starts gunicorn with the parameters specified. Common settings for gunicorn configuration
  are supported. For additional configuration use a config file See U(https://gunicorn-docs.readthedocs.io/en/latest/settings.html)
  for more options. It's recommended to always use the chdir option to avoid problems with the location
  of the app.
options:
  app:
    type: str
    required: true
    aliases:
    - name
    description: The app module. A name refers to a WSGI callable that should be found in the specified
      module.
  chdir:
    type: path
    description: Chdir to specified directory before apps loading.
  config:
    type: path
    aliases:
    - conf
    description: Path to the gunicorn configuration file.
  pid:
    type: path
    description: A filename to use for the PID file. If not set and not found on the configuration file
      a tmp pid file will be created to check a successful run of gunicorn.
  user:
    type: str
    description: Switch worker processes to run as this user.
  venv:
    type: path
    aliases:
    - virtualenv
    description: Path to the virtualenv directory.
  worker:
    type: str
    choices:
    - sync
    - eventlet
    - gevent
    - 'tornado '
    - gthread
    - gaiohttp
    description: The type of workers to use. The default class (sync) should handle most "normal" types
      of workloads.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Simple gunicorn run example\n  community.general.gunicorn:\n    app: 'wsgi'\n   \
  \ chdir: '/workspace/example'\n\n- name: Run gunicorn on a virtualenv\n  community.general.gunicorn:\n\
  \    app: 'wsgi'\n    chdir: '/workspace/example'\n    venv: '/workspace/example/venv'\n\n- name: Run\
  \ gunicorn with a config file\n  community.general.gunicorn:\n    app: 'wsgi'\n    chdir: '/workspace/example'\n\
  \    conf: '/workspace/example/gunicorn.cfg'\n\n- name: Run gunicorn as ansible user with specified\
  \ pid and config file\n  community.general.gunicorn:\n    app: 'wsgi'\n    chdir: '/workspace/example'\n\
  \    conf: '/workspace/example/gunicorn.cfg'\n    venv: '/workspace/example/venv'\n    pid: '/workspace/example/gunicorn.pid'\n\
  \    user: 'ansible'\n"
