name: ibm_sa_host_ports
fqcn: community.general.ibm_sa_host_ports
collection: community.general
short_description: Add host ports on IBM Spectrum Accelerate Family storage systems
description: This module adds ports to or removes them from the hosts on IBM Spectrum Accelerate Family
  storage systems.
options:
  endpoints:
    type: str
    required: true
    description: The hostname or management IP of Spectrum Accelerate storage system.
  fcaddress:
    type: str
    description: Fiber channel address.
  host:
    type: str
    required: true
    description: Host name.
  iscsi_name:
    type: str
    description: iSCSI initiator name.
  num_of_visible_targets:
    type: str
    description: Number of visible targets.
  password:
    type: str
    required: true
    description: Password for username on the spectrum accelerate storage system.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Host ports state.
  username:
    type: str
    required: true
    description: Management user on the spectrum accelerate storage system.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Add ports for host.\n  community.general.ibm_sa_host_ports:\n    host: test_host\n\
  \    iscsi_name: iqn.1994-05.com***\n    username: admin\n    password: secret\n    endpoints: hostdev-system\n\
  \    state: present\n\n- name: Remove ports for host.\n  community.general.ibm_sa_host_ports:\n    host:\
  \ test_host\n    iscsi_name: iqn.1994-05.com***\n    username: admin\n    password: secret\n    endpoints:\
  \ hostdev-system\n    state: absent\n\n"
