name: ibm_sa_vol
fqcn: community.general.ibm_sa_vol
collection: community.general
short_description: Handle volumes on IBM Spectrum Accelerate Family storage systems
description: This module creates or deletes volumes to be used on IBM Spectrum Accelerate Family storage
  systems.
options:
  endpoints:
    type: str
    required: true
    description: The hostname or management IP of Spectrum Accelerate storage system.
  password:
    type: str
    required: true
    description: Password for username on the spectrum accelerate storage system.
  pool:
    type: str
    description: Volume pool.
  size:
    type: str
    description: Volume size.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Volume state.
  username:
    type: str
    required: true
    description: Management user on the spectrum accelerate storage system.
  vol:
    type: str
    required: true
    description: Volume name.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create a new volume.\n  community.general.ibm_sa_vol:\n    vol: volume_name\n   \
  \ pool: pool_name\n    size: 17\n    state: present\n    username: admin\n    password: secret\n   \
  \ endpoints: hostdev-system\n\n- name: Delete an existing volume.\n  community.general.ibm_sa_vol:\n\
  \    vol: volume_name\n    state: absent\n    username: admin\n    password: secret\n    endpoints:\
  \ hostdev-system\n"
