name: idrac_redfish_info
fqcn: community.general.idrac_redfish_info
collection: community.general
short_description: Gather PowerEdge server information through iDRAC using Redfish APIs
description: Builds Redfish URIs locally and sends them to remote iDRAC controllers to get information
  back. For use with Dell EMC iDRAC operations that require Redfish OEM extensions.
options:
  auth_token:
    type: str
    description: Security token for authenticating to iDRAC.
  baseuri:
    type: str
    required: true
    description: Base URI of iDRAC.
  category:
    type: str
    required: true
    description: Category to execute on iDRAC.
  command:
    type: list
    required: true
    description: List of commands to execute on iDRAC. V(GetManagerAttributes) returns the list of dicts
      containing iDRAC, LifecycleController and System attributes.
  password:
    type: str
    description: Password for authenticating to iDRAC.
  timeout:
    type: int
    default: 10
    description: Timeout in seconds for HTTP requests to iDRAC.
  username:
    type: str
    description: Username for authenticating to iDRAC.
writes: false
runtime: starlark
source: translated
examples: "\n  - name: Get Manager attributes with a default of 20 seconds\n    community.general.idrac_redfish_info:\n\
  \      category: Manager\n      command: GetManagerAttributes\n      baseuri: \"{{ baseuri }}\"\n  \
  \    username: \"{{ username }}\"\n      password: \"{{ password }}\"\n      timeout: 20\n    register:\
  \ result\n\n  # Examples to display the value of all or a single iDRAC attribute\n  - name: Store iDRAC\
  \ attributes as a fact variable\n    ansible.builtin.set_fact:\n      idrac_attributes: \"{{ result.redfish_facts.entries\
  \ | selectattr('Id', 'defined') | selectattr('Id', 'equalto', 'iDRACAttributes') | list | first }}\"\
  \n\n  - name: Display all iDRAC attributes\n    ansible.builtin.debug:\n      var: idrac_attributes\n\
  \n  - name: Display the value of 'Syslog.1.SysLogEnable' iDRAC attribute\n    ansible.builtin.debug:\n\
  \      var: idrac_attributes['Syslog.1.SysLogEnable']\n\n  # Examples to display the value of all or\
  \ a single LifecycleController attribute\n  - name: Store LifecycleController attributes as a fact variable\n\
  \    ansible.builtin.set_fact:\n      lc_attributes: \"{{ result.redfish_facts.entries | selectattr('Id',\
  \ 'defined') | selectattr('Id', 'equalto', 'LCAttributes') | list | first }}\"\n\n  - name: Display\
  \ LifecycleController attributes\n    ansible.builtin.debug:\n      var: lc_attributes\n\n  - name:\
  \ Display the value of 'CollectSystemInventoryOnRestart' attribute\n    ansible.builtin.debug:\n   \
  \   var: lc_attributes['LCAttributes.1.CollectSystemInventoryOnRestart']\n\n  # Examples to display\
  \ the value of all or a single System attribute\n  - name: Store System attributes as a fact variable\n\
  \    ansible.builtin.set_fact:\n      system_attributes: \"{{ result.redfish_facts.entries | selectattr('Id',\
  \ 'defined') | selectattr('Id', 'equalto', 'SystemAttributes') | list | first }}\"\n\n  - name: Display\
  \ System attributes\n    ansible.builtin.debug:\n      var: system_attributes\n\n  - name: Display the\
  \ value of 'PSRedPolicy'\n    ansible.builtin.debug:\n      var: system_attributes['ServerPwr.1.PSRedPolicy']\n\
  \n"
