name: ilo_redfish_command
fqcn: community.general.ilo_redfish_command
collection: community.general
short_description: Manages Out-Of-Band controllers using Redfish APIs
description: Builds Redfish URIs locally and sends them to remote OOB controllers to perform an action.
options:
  auth_token:
    type: str
    description: Security token for authenticating to iLO.
  baseuri:
    type: str
    required: true
    description: Base URI of OOB controller.
  category:
    type: str
    required: true
    choices:
    - Systems
    description: Category to execute on OOB controller.
  command:
    type: list
    required: true
    description: List of commands to execute on OOB controller.
  password:
    type: str
    description: Password for authenticating to iLO.
  timeout:
    type: int
    default: 60
    description: Timeout in seconds for HTTP requests to iLO.
  username:
    type: str
    description: Username for authenticating to iLO.
writes: true
runtime: starlark
source: translated
examples: "\n  - name: Wait for iLO Reboot Completion\n    community.general.ilo_redfish_command:\n  \
  \    category: Systems\n      command: WaitforiLORebootCompletion\n      baseuri: \"{{ baseuri }}\"\n\
  \      username: \"{{ username }}\"\n      password: \"{{ password }}\"\n"
