name: ip_netns
fqcn: community.general.ip_netns
collection: community.general
short_description: Manage network namespaces
description: Create or delete network namespaces using the ip command.
options:
  name:
    type: str
    description: Name of the namespace
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Whether the namespace should exist
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create a namespace named mario\n  community.general.ip_netns:\n    name: mario\n\
  \    state: present\n\n- name: Delete a namespace named luigi\n  community.general.ip_netns:\n    name:\
  \ luigi\n    state: absent\n"
