name: ipa_dnszone
fqcn: community.general.ipa_dnszone
collection: community.general
short_description: Manage FreeIPA DNS Zones
description: Add and delete an IPA DNS Zones using IPA API
options:
  allowsyncptr:
    type: bool
    default: false
    description: Allow synchronization of forward and reverse records in the zone.
  dynamicupdate:
    type: bool
    default: false
    description: Apply dynamic update to zone.
  ipa_host:
    type: str
    default: ipa.example.com
    description: IP or hostname of IPA server. If the value is not specified in the task, the value of
      environment variable E(IPA_HOST) will be used instead. If both the environment variable E(IPA_HOST)
      and the value are not specified in the task, then DNS will be used to try to discover the FreeIPA
      server. The relevant entry needed in FreeIPA is the C(ipa-ca) entry. If neither the DNS entry, nor
      the environment E(IPA_HOST), nor the value are available in the task, then the default value will
      be used.
  ipa_pass:
    type: str
    description: Password of administrative user. If the value is not specified in the task, the value
      of environment variable E(IPA_PASS) will be used instead. Note that if the C(urllib_gssapi) library
      is available, it is possible to use GSSAPI to authenticate to FreeIPA. If the environment variable
      E(KRB5CCNAME) is available, the module will use this kerberos credentials cache to authenticate
      to the FreeIPA server. If the environment variable E(KRB5_CLIENT_KTNAME) is available, and E(KRB5CCNAME)
      is not; the module will use this kerberos keytab to authenticate. If GSSAPI is not available, the
      usage of O(ipa_pass) is required.
  ipa_port:
    type: int
    default: 443
    description: Port of FreeIPA / IPA server. If the value is not specified in the task, the value of
      environment variable E(IPA_PORT) will be used instead. If both the environment variable E(IPA_PORT)
      and the value are not specified in the task, then default value is set.
  ipa_prot:
    type: str
    default: https
    choices:
    - http
    - https
    description: Protocol used by IPA server. If the value is not specified in the task, the value of
      environment variable E(IPA_PROT) will be used instead. If both the environment variable E(IPA_PROT)
      and the value are not specified in the task, then default value is set.
  ipa_timeout:
    type: int
    default: 10
    description: Specifies idle timeout (in seconds) for the connection. For bulk operations, you may
      want to increase this in order to avoid timeout from IPA server. If the value is not specified in
      the task, the value of environment variable E(IPA_TIMEOUT) will be used instead. If both the environment
      variable E(IPA_TIMEOUT) and the value are not specified in the task, then default value is set.
  ipa_user:
    type: str
    default: admin
    description: Administrative account used on IPA server. If the value is not specified in the task,
      the value of environment variable E(IPA_USER) will be used instead. If both the environment variable
      E(IPA_USER) and the value are not specified in the task, then default value is set.
  state:
    type: str
    default: present
    choices:
    - absent
    - present
    description: State to ensure
  validate_certs:
    type: bool
    default: true
    description: This only applies if O(ipa_prot) is V(https). If set to V(false), the SSL certificates
      will not be validated. This should only set to V(false) used on personally controlled sites using
      self-signed certificates.
  zone_name:
    type: str
    required: true
    description: The DNS zone name to which needs to be managed.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Ensure dns zone is present\n  community.general.ipa_dnszone:\n    ipa_host: spider.example.com\n\
  \    ipa_pass: Passw0rd!\n    state: present\n    zone_name: example.com\n\n- name: Ensure dns zone\
  \ is present and is dynamic update\n  community.general.ipa_dnszone:\n    ipa_host: spider.example.com\n\
  \    ipa_pass: Passw0rd!\n    state: present\n    zone_name: example.com\n    dynamicupdate: true\n\n\
  - name: Ensure that dns zone is removed\n  community.general.ipa_dnszone:\n    zone_name: example.com\n\
  \    ipa_host: localhost\n    ipa_user: admin\n    ipa_pass: topsecret\n    state: absent\n\n- name:\
  \ Ensure dns zone is present and is allowing sync\n  community.general.ipa_dnszone:\n    ipa_host: spider.example.com\n\
  \    ipa_pass: Passw0rd!\n    state: present\n    zone_name: example.com\n    allowsyncptr: true\n"
