name: iso_customize
fqcn: community.general.iso_customize
collection: community.general
short_description: Add/remove/change files in ISO file
description: This module is used to add/remove/change files in ISO file. The file inside ISO will be overwritten
  if it exists by option O(add_files).
options:
  add_files:
    type: list
    default: []
    description: Allows to add and replace files in the ISO file. Will create intermediate folders inside
      the ISO file when they do not exist.
  delete_files:
    type: list
    default: []
    description: Absolute paths for files inside the ISO file that should be removed.
  dest_iso:
    type: path
    required: true
    description: The path of the customized ISO file.
  src_iso:
    type: path
    required: true
    description: This is the path of source ISO file.
writes: true
runtime: starlark
source: translated
examples: "\n- name: \"Customize ISO file\"\n  community.general.iso_customize:\n    src_iso: \"/path/to/ubuntu-22.04-desktop-amd64.iso\"\
  \n    dest_iso: \"/path/to/ubuntu-22.04-desktop-amd64-customized.iso\"\n    delete_files:\n      - \"\
  /boot.catalog\"\n    add_files:\n      - src_file: \"/path/to/grub.cfg\"\n        dest_file: \"/boot/grub/grub.cfg\"\
  \n      - src_file: \"/path/to/ubuntu.seed\"\n        dest_file: \"/preseed/ubuntu.seed\"\n  register:\
  \ customize_iso_result\n"
