name: jabber
fqcn: community.general.jabber
collection: community.general
short_description: Send a message to jabber user or chat room
description: Send a message to jabber
options:
  encoding:
    type: str
    description: message encoding
  host:
    type: str
    description: host to connect, overrides user info
  msg:
    type: str
    required: true
    description: The message body.
  password:
    type: str
    required: true
    description: password for user to connect
  port:
    type: int
    default: 5222
    description: port to connect to, overrides default
  to:
    type: str
    required: true
    description: user ID or name of the room, when using room use a slash to indicate your nick.
  user:
    type: str
    required: true
    description: User as which to connect
writes: true
runtime: starlark
source: translated
examples: "\n- name: Send a message to a user\n  community.general.jabber:\n    user: mybot@example.net\n\
  \    password: secret\n    to: friend@example.net\n    msg: Ansible task finished\n\n- name: Send a\
  \ message to a room\n  community.general.jabber:\n    user: mybot@example.net\n    password: secret\n\
  \    to: mychaps@conference.example.net/ansiblebot\n    msg: Ansible task finished\n\n- name: Send a\
  \ message, specifying the host and port\n  community.general.jabber:\n    user: mybot@example.net\n\
  \    host: talk.example.net\n    port: 5223\n    password: secret\n    to: mychaps@example.net\n   \
  \ msg: Ansible task finished\n"
