name: kernel_blacklist
fqcn: community.general.kernel_blacklist
collection: community.general
short_description: Blacklist kernel modules
description: Add or remove kernel modules from blacklist.
options:
  blacklist_file:
    type: str
    default: /etc/modprobe.d/blacklist-ansible.conf
    description: If specified, use this blacklist file instead of C(/etc/modprobe.d/blacklist-ansible.conf).
  name:
    type: str
    required: true
    description: Name of kernel module to black- or whitelist.
  state:
    type: str
    default: present
    choices:
    - absent
    - present
    description: Whether the module should be present in the blacklist or absent.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Blacklist the nouveau driver module\n  community.general.kernel_blacklist:\n    name:\
  \ nouveau\n    state: present\n"
