name: keycloak_realm
fqcn: community.general.keycloak_realm
collection: community.general
short_description: Allows administration of Keycloak realm via Keycloak API
description: This module allows the administration of Keycloak realm via the Keycloak REST API. It requires
  access to the REST API via OpenID Connect; the user connecting and the realm being used must have the
  requisite access rights. In a default Keycloak installation, admin-cli and an admin user would work,
  as would a separate realm definition with the scope tailored to your needs and a user having the expected
  roles. The names of module options are snake_cased versions of the camelCase ones found in the Keycloak
  API and its documentation at U(https://www.keycloak.org/docs-api/8.0/rest-api/index.html). Aliases are
  provided so camelCased versions can be used as well. The Keycloak API does not always sanity check inputs
  e.g. you can set SAML-specific settings on an OpenID Connect client for instance and vice versa. Be
  careful. If you do not specify a setting, usually a sensible default is chosen.
options:
  access_code_lifespan:
    type: int
    aliases:
    - accessCodeLifespan
    description: The realm access code lifespan.
  access_code_lifespan_login:
    type: int
    aliases:
    - accessCodeLifespanLogin
    description: The realm access code lifespan login.
  access_code_lifespan_user_action:
    type: int
    aliases:
    - accessCodeLifespanUserAction
    description: The realm access code lifespan user action.
  access_token_lifespan:
    type: int
    aliases:
    - accessTokenLifespan
    description: The realm access token lifespan.
  access_token_lifespan_for_implicit_flow:
    type: int
    aliases:
    - accessTokenLifespanForImplicitFlow
    description: The realm access token lifespan for implicit flow.
  account_theme:
    type: str
    aliases:
    - accountTheme
    description: The realm account theme.
  action_token_generated_by_admin_lifespan:
    type: int
    aliases:
    - actionTokenGeneratedByAdminLifespan
    description: The realm action token generated by admin lifespan.
  action_token_generated_by_user_lifespan:
    type: int
    aliases:
    - actionTokenGeneratedByUserLifespan
    description: The realm action token generated by user lifespan.
  admin_events_details_enabled:
    type: bool
    aliases:
    - adminEventsDetailsEnabled
    description: The realm admin events details enabled.
  admin_events_enabled:
    type: bool
    aliases:
    - adminEventsEnabled
    description: The realm admin events enabled.
  admin_theme:
    type: str
    aliases:
    - adminTheme
    description: The realm admin theme.
  attributes:
    type: dict
    description: The realm attributes.
  auth_client_id:
    type: str
    default: admin-cli
    description: OpenID Connect C(client_id) to authenticate to the API with.
  auth_client_secret:
    type: str
    description: Client Secret to use in conjunction with O(auth_client_id) (if required).
  auth_keycloak_url:
    type: str
    required: true
    aliases:
    - url
    description: URL to the Keycloak instance.
  auth_password:
    type: str
    aliases:
    - password
    description: Password to authenticate for API access with.
  auth_realm:
    type: str
    description: Keycloak realm name to authenticate to for API access.
  auth_username:
    type: str
    aliases:
    - username
    description: Username to authenticate for API access with.
  browser_flow:
    type: str
    aliases:
    - browserFlow
    description: The realm browser flow.
  browser_security_headers:
    type: dict
    aliases:
    - browserSecurityHeaders
    description: The realm browser security headers.
  brute_force_protected:
    type: bool
    aliases:
    - bruteForceProtected
    description: The realm brute force protected.
  client_authentication_flow:
    type: str
    aliases:
    - clientAuthenticationFlow
    description: The realm client authentication flow.
  client_scope_mappings:
    type: dict
    aliases:
    - clientScopeMappings
    description: The realm client scope mappings.
  connection_timeout:
    type: int
    default: 10
    description: Controls the HTTP connections timeout period (in seconds) to Keycloak API.
  default_default_client_scopes:
    type: list
    aliases:
    - defaultDefaultClientScopes
    description: The realm default default client scopes.
  default_groups:
    type: list
    aliases:
    - defaultGroups
    description: The realm default groups.
  default_locale:
    type: str
    aliases:
    - defaultLocale
    description: The realm default locale.
  default_optional_client_scopes:
    type: list
    aliases:
    - defaultOptionalClientScopes
    description: The realm default optional client scopes.
  default_roles:
    type: list
    aliases:
    - defaultRoles
    description: The realm default roles.
  default_signature_algorithm:
    type: str
    aliases:
    - defaultSignatureAlgorithm
    description: The realm default signature algorithm.
  direct_grant_flow:
    type: str
    aliases:
    - directGrantFlow
    description: The realm direct grant flow.
  display_name:
    type: str
    aliases:
    - displayName
    description: The realm display name.
  display_name_html:
    type: str
    aliases:
    - displayNameHtml
    description: The realm display name HTML.
  docker_authentication_flow:
    type: str
    aliases:
    - dockerAuthenticationFlow
    description: The realm docker authentication flow.
  duplicate_emails_allowed:
    type: bool
    aliases:
    - duplicateEmailsAllowed
    description: The realm duplicate emails allowed option.
  edit_username_allowed:
    type: bool
    aliases:
    - editUsernameAllowed
    description: The realm edit username allowed option.
  email_theme:
    type: str
    aliases:
    - emailTheme
    description: The realm email theme.
  enabled:
    type: bool
    description: The realm enabled option.
  enabled_event_types:
    type: list
    aliases:
    - enabledEventTypes
    description: The realm enabled event types.
  events_enabled:
    type: bool
    aliases:
    - eventsEnabled
    description: Enables or disables login events for this realm.
  events_expiration:
    type: int
    aliases:
    - eventsExpiration
    description: The realm events expiration.
  events_listeners:
    type: list
    aliases:
    - eventsListeners
    description: The realm events listeners.
  failure_factor:
    type: int
    aliases:
    - failureFactor
    description: The realm failure factor.
  http_agent:
    type: str
    default: Ansible
    description: Configures the HTTP User-Agent header.
  id:
    type: str
    description: The realm to create.
  internationalization_enabled:
    type: bool
    aliases:
    - internationalizationEnabled
    description: The realm internationalization enabled option.
  login_theme:
    type: str
    aliases:
    - loginTheme
    description: The realm login theme.
  login_with_email_allowed:
    type: bool
    aliases:
    - loginWithEmailAllowed
    description: The realm login with email allowed option.
  max_delta_time_seconds:
    type: int
    aliases:
    - maxDeltaTimeSeconds
    description: The realm max delta time in seconds.
  max_failure_wait_seconds:
    type: int
    aliases:
    - maxFailureWaitSeconds
    description: The realm max failure wait in seconds.
  minimum_quick_login_wait_seconds:
    type: int
    aliases:
    - minimumQuickLoginWaitSeconds
    description: The realm minimum quick login wait in seconds.
  not_before:
    type: int
    aliases:
    - notBefore
    description: The realm not before.
  offline_session_idle_timeout:
    type: int
    aliases:
    - offlineSessionIdleTimeout
    description: The realm offline session idle timeout.
  offline_session_max_lifespan:
    type: int
    aliases:
    - offlineSessionMaxLifespan
    description: The realm offline session max lifespan.
  offline_session_max_lifespan_enabled:
    type: bool
    aliases:
    - offlineSessionMaxLifespanEnabled
    description: The realm offline session max lifespan enabled option.
  otp_policy_algorithm:
    type: str
    aliases:
    - otpPolicyAlgorithm
    description: The realm otp policy algorithm.
  otp_policy_digits:
    type: int
    aliases:
    - otpPolicyDigits
    description: The realm otp policy digits.
  otp_policy_initial_counter:
    type: int
    aliases:
    - otpPolicyInitialCounter
    description: The realm otp policy initial counter.
  otp_policy_look_ahead_window:
    type: int
    aliases:
    - otpPolicyLookAheadWindow
    description: The realm otp policy look ahead window.
  otp_policy_period:
    type: int
    aliases:
    - otpPolicyPeriod
    description: The realm otp policy period.
  otp_policy_type:
    type: str
    aliases:
    - otpPolicyType
    description: The realm otp policy type.
  otp_supported_applications:
    type: list
    aliases:
    - otpSupportedApplications
    description: The realm otp supported applications.
  password_policy:
    type: str
    aliases:
    - passwordPolicy
    description: The realm password policy.
  permanent_lockout:
    type: bool
    aliases:
    - permanentLockout
    description: The realm permanent lockout.
  quick_login_check_milli_seconds:
    type: int
    aliases:
    - quickLoginCheckMilliSeconds
    description: The realm quick login check in milliseconds.
  realm:
    type: str
    description: The realm name.
  refresh_token_max_reuse:
    type: int
    aliases:
    - refreshTokenMaxReuse
    description: The realm refresh token max reuse.
  registration_allowed:
    type: bool
    aliases:
    - registrationAllowed
    description: The realm registration allowed option.
  registration_email_as_username:
    type: bool
    aliases:
    - registrationEmailAsUsername
    description: The realm registration email as username option.
  registration_flow:
    type: str
    aliases:
    - registrationFlow
    description: The realm registration flow.
  remember_me:
    type: bool
    aliases:
    - rememberMe
    description: The realm remember me option.
  reset_credentials_flow:
    type: str
    aliases:
    - resetCredentialsFlow
    description: The realm reset credentials flow.
  reset_password_allowed:
    type: bool
    aliases:
    - resetPasswordAllowed
    description: The realm reset password allowed option.
  revoke_refresh_token:
    type: bool
    aliases:
    - revokeRefreshToken
    description: The realm revoke refresh token option.
  smtp_server:
    type: dict
    aliases:
    - smtpServer
    description: The realm smtp server.
  ssl_required:
    type: str
    choices:
    - all
    - external
    - none
    aliases:
    - sslRequired
    description: The realm ssl required option.
  sso_session_idle_timeout:
    type: int
    aliases:
    - ssoSessionIdleTimeout
    description: The realm sso session idle timeout.
  sso_session_idle_timeout_remember_me:
    type: int
    aliases:
    - ssoSessionIdleTimeoutRememberMe
    description: The realm sso session idle timeout remember me.
  sso_session_max_lifespan:
    type: int
    aliases:
    - ssoSessionMaxLifespan
    description: The realm sso session max lifespan.
  sso_session_max_lifespan_remember_me:
    type: int
    aliases:
    - ssoSessionMaxLifespanRememberMe
    description: The realm sso session max lifespan remember me.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: State of the realm. On V(present), the realm will be created (or updated if it exists
      already). On V(absent), the realm will be removed if it exists.
  supported_locales:
    type: list
    aliases:
    - supportedLocales
    description: The realm supported locales.
  token:
    type: str
    description: Authentication token for Keycloak API.
  user_managed_access_allowed:
    type: bool
    aliases:
    - userManagedAccessAllowed
    description: The realm user managed access allowed option.
  validate_certs:
    type: bool
    default: true
    description: Verify TLS certificates (do not disable this in production).
  verify_email:
    type: bool
    aliases:
    - verifyEmail
    description: The realm verify email option.
  wait_increment_seconds:
    type: int
    aliases:
    - waitIncrementSeconds
    description: The realm wait increment in seconds.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create or update Keycloak realm (minimal example)\n  community.general.keycloak_realm:\n\
  \    auth_client_id: admin-cli\n    auth_keycloak_url: https://auth.example.com/auth\n    auth_realm:\
  \ master\n    auth_username: USERNAME\n    auth_password: PASSWORD\n    id: realm\n    realm: realm\n\
  \    state: present\n\n- name: Delete a Keycloak realm\n  community.general.keycloak_realm:\n    auth_client_id:\
  \ admin-cli\n    auth_keycloak_url: https://auth.example.com/auth\n    auth_realm: master\n    auth_username:\
  \ USERNAME\n    auth_password: PASSWORD\n    id: test\n    state: absent\n\n"
