name: keycloak_clientsecret_info
fqcn: community.general.keycloak_clientsecret_info
collection: community.general
short_description: Retrieve client secret via Keycloak API
description: 'This module allows you to get a Keycloak client secret via the Keycloak REST API. It requires
  access to the REST API via OpenID Connect; the user connecting and the client being used must have the
  requisite access rights. In a default Keycloak installation, admin-cli and an admin user would work,
  as would a separate client definition with the scope tailored to your needs and a user having the expected
  roles. When retrieving a new client secret, where possible provide the client''s O(id) (not O(client_id))
  to the module. This removes a lookup to the API to translate the O(client_id) into the client ID. Note
  that this module returns the client secret. To avoid this showing up in the logs, please add C(no_log:
  true) to the task.'
options:
  auth_client_id:
    type: str
    default: admin-cli
    description: OpenID Connect C(client_id) to authenticate to the API with.
  auth_client_secret:
    type: str
    description: Client Secret to use in conjunction with O(auth_client_id) (if required).
  auth_keycloak_url:
    type: str
    required: true
    aliases:
    - url
    description: URL to the Keycloak instance.
  auth_password:
    type: str
    aliases:
    - password
    description: Password to authenticate for API access with.
  auth_realm:
    type: str
    description: Keycloak realm name to authenticate to for API access.
  auth_username:
    type: str
    aliases:
    - username
    description: Username to authenticate for API access with.
  client_id:
    type: str
    aliases:
    - clientId
    description: The O(client_id) of the client. Passing this instead of O(id) results in an extra API
      call.
  connection_timeout:
    type: int
    default: 10
    description: Controls the HTTP connections timeout period (in seconds) to Keycloak API.
  http_agent:
    type: str
    default: Ansible
    description: Configures the HTTP User-Agent header.
  id:
    type: str
    description: The unique identifier for this client. This parameter is not required for getting or
      generating a client secret but providing it will reduce the number of API calls required.
  realm:
    type: str
    default: master
    description: They Keycloak realm under which this client resides.
  token:
    type: str
    description: Authentication token for Keycloak API.
  validate_certs:
    type: bool
    default: true
    description: Verify TLS certificates (do not disable this in production).
writes: false
runtime: starlark
source: translated
examples: "\n- name: Get a Keycloak client secret, authentication with credentials\n  community.general.keycloak_clientsecret_info:\n\
  \    id: '9d59aa76-2755-48c6-b1af-beb70a82c3cd'\n    realm: MyCustomRealm\n    auth_client_id: admin-cli\n\
  \    auth_keycloak_url: https://auth.example.com/auth\n    auth_realm: master\n    auth_username: USERNAME\n\
  \    auth_password: PASSWORD\n  delegate_to: localhost\n  no_log: true\n\n- name: Get a new Keycloak\
  \ client secret, authentication with token\n  community.general.keycloak_clientsecret_info:\n    id:\
  \ '9d59aa76-2755-48c6-b1af-beb70a82c3cd'\n    realm: MyCustomRealm\n    auth_client_id: admin-cli\n\
  \    auth_keycloak_url: https://auth.example.com/auth\n    token: TOKEN\n  delegate_to: localhost\n\
  \  no_log: true\n\n- name: Get a new Keycloak client secret, passing client_id instead of id\n  community.general.keycloak_clientsecret_info:\n\
  \    client_id: 'myClientId'\n    realm: MyCustomRealm\n    auth_client_id: admin-cli\n    auth_keycloak_url:\
  \ https://auth.example.com/auth\n    token: TOKEN\n  delegate_to: localhost\n  no_log: true\n"
