name: keycloak_clientscope_type
fqcn: community.general.keycloak_clientscope_type
collection: community.general
short_description: Set the type of aclientscope in realm or client via Keycloak API
description: This module allows you to set the type (optional, default) of clientscopes via the Keycloak
  REST API. It requires access to the REST API via OpenID Connect; the user connecting and the client
  being used must have the requisite access rights. In a default Keycloak installation, admin-cli and
  an admin user would work, as would a separate client definition with the scope tailored to your needs
  and a user having the expected roles.
options:
  auth_client_id:
    type: str
    default: admin-cli
    description: OpenID Connect C(client_id) to authenticate to the API with.
  auth_client_secret:
    type: str
    description: Client Secret to use in conjunction with O(auth_client_id) (if required).
  auth_keycloak_url:
    type: str
    required: true
    aliases:
    - url
    description: URL to the Keycloak instance.
  auth_password:
    type: str
    aliases:
    - password
    description: Password to authenticate for API access with.
  auth_realm:
    type: str
    description: Keycloak realm name to authenticate to for API access.
  auth_username:
    type: str
    aliases:
    - username
    description: Username to authenticate for API access with.
  client_id:
    type: str
    aliases:
    - clientId
    description: The O(client_id) of the client. If not set the clientscop types are set as a default
      for the realm.
  connection_timeout:
    type: int
    default: 10
    description: Controls the HTTP connections timeout period (in seconds) to Keycloak API.
  default_clientscopes:
    type: list
    description: Client scopes that should be of type default.
  http_agent:
    type: str
    default: Ansible
    description: Configures the HTTP User-Agent header.
  optional_clientscopes:
    type: list
    description: Client scopes that should be of type optional.
  realm:
    type: str
    default: master
    description: The Keycloak realm.
  token:
    type: str
    description: Authentication token for Keycloak API.
  validate_certs:
    type: bool
    default: true
    description: Verify TLS certificates (do not disable this in production).
writes: true
runtime: starlark
source: translated
examples: "\n- name: Set default client scopes on realm level\n  community.general.keycloak_clientscope_type:\n\
  \    auth_client_id: admin-cli\n    auth_keycloak_url: https://auth.example.com/auth\n    auth_realm:\
  \ master\n    auth_username: USERNAME\n    auth_password: PASSWORD\n    realm: \"MyCustomRealm\"\n \
  \   default_clientscopes: ['profile', 'roles']\n  delegate_to: localhost\n\n\n- name: Set default and\
  \ optional client scopes on client level with token auth\n  community.general.keycloak_clientscope_type:\n\
  \    auth_client_id: admin-cli\n    auth_keycloak_url: https://auth.example.com/auth\n    token: TOKEN\n\
  \    realm: \"MyCustomRealm\"\n    client_id: \"MyCustomClient\"\n    default_clientscopes: ['profile',\
  \ 'roles']\n    optional_clientscopes: ['phone']\n  delegate_to: localhost\n"
