name: logentries_msg
fqcn: community.general.logentries_msg
collection: community.general
short_description: Send a message to logentries
description: Send a message to logentries
options:
  api:
    type: str
    default: data.logentries.com
    description: API endpoint
  msg:
    type: str
    required: true
    description: The message body.
  port:
    type: int
    default: 80
    description: API endpoint port
  token:
    type: str
    required: true
    description: Log token.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Send a message to logentries\n  community.general.logentries_msg:\n    token=00000000-0000-0000-0000-000000000000\n\
  \    msg=\"{{ ansible_hostname }}\"\n"
