name: make
fqcn: community.general.make
collection: community.general
short_description: Run targets in a Makefile
description: Run targets in a Makefile.
options:
  chdir:
    type: path
    required: true
    description: Change to this directory before running make.
  file:
    type: path
    description: Use a custom Makefile.
  jobs:
    type: int
    description: Set the number of make jobs to run concurrently. Typically if set, this would be the
      number of processors and/or threads available to the machine. This is not supported by all make
      implementations.
  make:
    type: path
    description: Use a specific make binary.
  params:
    type: dict
    description: Any extra parameters to pass to make. If the value is empty, only the key will be used.
      For example, V(FOO:) will produce V(FOO), not V(FOO=).
  target:
    type: str
    description: The target to run. Typically this would be something like V(install), V(test), or V(all).
      O(target) and O(targets) are mutually exclusive.
  targets:
    type: list
    description: The list of targets to run. Typically this would be something like V(install), V(test),
      or V(all). O(target) and O(targets) are mutually exclusive.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Build the default target\n  community.general.make:\n    chdir: /home/ubuntu/cool-project\n\
  \n- name: Run 'install' target as root\n  community.general.make:\n    chdir: /home/ubuntu/cool-project\n\
  \    target: install\n  become: true\n\n- name: Build 'all' target with extra arguments\n  community.general.make:\n\
  \    chdir: /home/ubuntu/cool-project\n    target: all\n    params:\n      NUM_THREADS: 4\n      BACKEND:\
  \ lapack\n\n- name: Build 'all' target with a custom Makefile\n  community.general.make:\n    chdir:\
  \ /home/ubuntu/cool-project\n    target: all\n    file: /some-project/Makefile\n\n- name: build arm64\
  \ kernel on FreeBSD, with 16 parallel jobs\n  community.general.make:\n    chdir: /usr/src\n    jobs:\
  \ 16\n    target: buildkernel\n    params:\n      # This adds -DWITH_FDT to the command line:\n    \
  \  -DWITH_FDT:\n      # The following adds TARGET=arm64 TARGET_ARCH=aarch64 to the command line:\n \
  \     TARGET: arm64\n      TARGET_ARCH: aarch64\n"
