name: manageiq_policies_info
fqcn: community.general.manageiq_policies_info
collection: community.general
short_description: Listing of resource policy_profiles in ManageIQ
description: The manageiq_policies module supports listing policy_profiles in ManageIQ.
options:
  manageiq_connection:
    type: dict
    description: ManageIQ connection configuration information.
  resource_id:
    type: int
    description: The ID of the resource to obtain the profile for. Must be specified if O(resource_name)
      is not set. Both options are mutually exclusive.
  resource_name:
    type: str
    description: The name of the resource to obtain the profile for. Must be specified if O(resource_id)
      is not set. Both options are mutually exclusive.
  resource_type:
    type: str
    required: true
    choices:
    - provider
    - host
    - vm
    - blueprint
    - category
    - cluster
    - data store
    - group
    - resource pool
    - service
    - service template
    - template
    - tenant
    - user
    description: The type of the resource to obtain the profile for.
writes: false
runtime: starlark
source: translated
examples: "\n- name: List current policy_profile and policies for a provider in ManageIQ\n  community.general.manageiq_policies_info:\n\
  \    resource_name: 'EngLab'\n    resource_type: 'provider'\n    manageiq_connection:\n      url: 'http://127.0.0.1:3000'\n\
  \      username: 'admin'\n      password: 'smartvm'\n  register: result\n"
