name: memset_server_info
fqcn: community.general.memset_server_info
collection: community.general
short_description: Retrieve server information
description: Retrieve server information.
options:
  api_key:
    type: str
    required: true
    description: The API key obtained from the Memset control panel.
  name:
    type: str
    required: true
    description: The server product name (that is, C(testyaa1)).
writes: false
runtime: starlark
source: translated
examples: "\n- name: Get details for testyaa1\n  community.general.memset_server_info:\n    name: testyaa1\n\
  \    api_key: 5eb86c9896ab03919abcf03857163741\n  delegate_to: localhost\n"
