name: nomad_token
fqcn: community.general.nomad_token
collection: community.general
short_description: Manage Nomad ACL tokens
description: This module allows to create Bootstrap tokens, create ACL tokens, update ACL tokens, and
  delete ACL tokens.
options:
  client_cert:
    type: path
    description: Path of certificate for TLS/SSL.
  client_key:
    type: path
    description: Path of certificate's private key for TLS/SSL.
  global_replicated:
    type: bool
    default: false
    description: Indicates whether or not the token was created with the C(--global).
  host:
    type: str
    required: true
    description: FQDN of Nomad server.
  name:
    type: str
    description: Name of ACL token to create.
  namespace:
    type: str
    description: Namespace for Nomad.
  policies:
    type: list
    default: []
    description: A list of the policies assigned to the token.
  port:
    type: int
    default: 4646
    description: Port of Nomad server.
  state:
    type: str
    required: true
    choices:
    - present
    - absent
    description: Create or remove ACL token.
  timeout:
    type: int
    default: 5
    description: Timeout (in seconds) for the request to Nomad.
  token:
    type: str
    description: ACL token for authentication.
  token_type:
    type: str
    default: client
    choices:
    - client
    - management
    - bootstrap
    description: The type of the token can be V(client), V(management), or V(bootstrap).
  use_ssl:
    type: bool
    default: true
    description: Use TLS/SSL connection.
  validate_certs:
    type: bool
    default: true
    description: Enable TLS/SSL certificate validation.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create boostrap token\n  community.general.nomad_token:\n    host: localhost\n  \
  \  token_type: bootstrap\n    state: present\n\n- name: Create ACL token\n  community.general.nomad_token:\n\
  \    host: localhost\n    name: \"Dev token\"\n    token_type: client\n    policies:\n        - readonly\n\
  \    global_replicated: false\n    state: absent\n\n- name: Update ACL token Dev token\n  community.general.nomad_token:\n\
  \    host: localhost\n    name: \"Dev token\"\n    token_type: client\n    policies:\n        - readonly\n\
  \        - devpolicy\n    global_replicated: false\n    state: absent\n\n- name: Delete ACL token\n\
  \  community.general.nomad_token:\n    host: localhost\n    name: \"Dev token\"\n    state: absent\n"
