name: one_vm
fqcn: community.general.one_vm
collection: community.general
short_description: Creates or terminates OpenNebula instances
description: Manages OpenNebula instances
options:
  api_password:
    type: str
    description: Password of the user to login into OpenNebula RPC server. If not set then the value of
      the E(ONE_PASSWORD) environment variable is used. if both O(api_username) or O(api_password) are
      not set, then it will try authenticate with ONE auth file. Default path is "~/.one/one_auth". Set
      environment variable E(ONE_AUTH) to override this path.
  api_url:
    type: str
    description: URL of the OpenNebula RPC server. It is recommended to use HTTPS so that the username/password
      are not transferred over the network unencrypted. If not set then the value of the E(ONE_URL) environment
      variable is used.
  api_username:
    type: str
    description: Name of the user to login into the OpenNebula RPC server. If not set then the value of
      the E(ONE_USERNAME) environment variable is used.
  attributes:
    type: dict
    default: {}
    description: A dictionary of key/value attributes to add to new instances, or for setting C(state)
      of instances with these attributes. Keys are case insensitive and OpenNebula automatically converts
      them to upper case. Be aware C(NAME) is a special attribute which sets the name of the VM when it's
      deployed. C(#) character(s) can be appended to the C(NAME) and the module will automatically add
      indexes to the names of VMs. For example':' C(NAME':' foo-###) would create VMs with names C(foo-000),
      C(foo-001),... When used with O(count_attributes) and O(exact_count) the module will match the base
      name without the index part.
  count:
    type: int
    default: 1
    description: Number of instances to launch
  count_attributes:
    type: dict
    description: A dictionary of key/value attributes that can only be used with O(exact_count) to determine
      how many nodes based on a specific attributes criteria should be deployed. This can be expressed
      in multiple ways and is shown in the EXAMPLES section.
  count_labels:
    type: list
    description: A list of labels that can only be used with O(exact_count) to determine how many nodes
      based on a specific labels criteria should be deployed. This can be expressed in multiple ways and
      is shown in the EXAMPLES section.
  cpu:
    type: float
    description: Percentage of CPU divided by 100 required for the new instance. Half a processor is written
      0.5.
  datastore_id:
    type: int
    description: Name of Datastore to use to create a new instance
  datastore_name:
    type: str
    description: Name of Datastore to use to create a new instance
  disk_saveas:
    type: dict
    description: Creates an image from a VM disk. It is a dictionary where you have to specify C(name)
      of the new image. Optionally you can specify C(disk_id) of the disk you want to save. By default
      C(disk_id) is 0. B(NOTE:) This operation will only be performed on the first VM (if more than one
      VM ID is passed) and the VM has to be in the C(poweredoff) state. Also this operation will fail
      if an image with specified C(name) already exists.
  disk_size:
    type: list
    description: The size of the disk created for new instances (in MB, GB, TB,...). B(NOTE:) If The Template
      hats Multiple Disks the Order of the Sizes is matched against the order specified in O(template_id)/O(template_name).
  exact_count:
    type: int
    description: Indicates how many instances that match O(count_attributes) and O(count_labels) parameters
      should be deployed. Instances are either created or terminated based on this value. B(NOTE:) Instances
      with the least IDs will be terminated first.
  group_id:
    type: int
    description: ID of the group which will be set as the group of the instance
  hard:
    type: bool
    default: false
    description: Reboot, power-off or terminate instances C(hard).
  instance_ids:
    type: list
    aliases:
    - ids
    description: 'A list of instance ids used for states: V(absent), V(running), V(rebooted), V(poweredoff).'
  labels:
    type: list
    default: []
    description: A list of labels to associate with new instances, or for setting C(state) of instances
      with these labels.
  memory:
    type: str
    description: The size of the memory for new instances (in MB, GB, ...)
  mode:
    type: str
    description: Set permission mode of the instance in octet format, for example V(0600) to give owner
      C(use) and C(manage) and nothing to group and others.
  networks:
    type: list
    default: []
    description: A list of dictionaries with network parameters. See examples for more details.
  owner_id:
    type: int
    description: ID of the user which will be set as the owner of the instance
  persistent:
    type: bool
    default: false
    description: Create a private persistent copy of the template plus any image defined in DISK, and
      instantiate that copy.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    - running
    - rebooted
    - poweredoff
    description: V(present) - create instances from a template specified with C(template_id)/C(template_name).
      V(running) - run instances V(poweredoff) - power-off instances V(rebooted) - reboot instances V(absent)
      - terminate instances
  template_id:
    type: int
    description: ID of a VM template to use to create a new instance
  template_name:
    type: str
    description: Name of VM template to use to create a new instance
  updateconf:
    type: dict
    description: When O(instance_ids) is provided, updates running VMs with the C(updateconf) API call.
      When new VMs are being created, emulates the C(updateconf) API call via direct template merge. Allows
      for complete modifications of the C(CONTEXT) attribute.
  vcpu:
    type: int
    description: Number of CPUs (cores) new VM will have.
  vm_start_on_hold:
    type: bool
    default: false
    description: Set to true to put vm on hold while creating
  wait:
    type: bool
    default: true
    description: Wait for the instance to reach its desired state before returning. Keep in mind if you
      are waiting for instance to be in running state it doesn't mean that you will be able to SSH on
      that machine only that boot process have started on that instance, see 'wait_for' example for details.
  wait_timeout:
    type: int
    default: 300
    description: How long before wait gives up, in seconds
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create a new instance\n  community.general.one_vm:\n    template_id: 90\n  register:\
  \ result\n\n- name: Print VM properties\n  ansible.builtin.debug:\n    msg: result\n\n- name: Deploy\
  \ a new VM on hold\n  community.general.one_vm:\n    template_name: 'app1_template'\n    vm_start_on_hold:\
  \ 'True'\n\n- name: Deploy a new VM and set its name to 'foo'\n  community.general.one_vm:\n    template_name:\
  \ 'app1_template'\n    attributes:\n      name: foo\n\n- name: Deploy a new VM and set its group_id\
  \ and mode\n  community.general.one_vm:\n    template_id: 90\n    group_id: 16\n    mode: 660\n\n- name:\
  \ Deploy a new VM  as persistent\n  community.general.one_vm:\n    template_id: 90\n    persistent:\
  \ true\n\n- name: Change VM's permissions to 640\n  community.general.one_vm:\n    instance_ids: 5\n\
  \    mode: 640\n\n- name: Deploy 2 new instances and set memory, vcpu, disk_size and 3 networks\n  community.general.one_vm:\n\
  \    template_id: 15\n    disk_size: 35.2 GB\n    memory: 4 GB\n    vcpu: 4\n    count: 2\n    networks:\n\
  \      - NETWORK_ID: 27\n      - NETWORK: \"default-network\"\n        NETWORK_UNAME: \"app-user\"\n\
  \        SECURITY_GROUPS: \"120,124\"\n      - NETWORK_ID: 27\n        SECURITY_GROUPS: \"10\"\n\n-\
  \ name: Deploy a new instance which uses a Template with two Disks\n  community.general.one_vm:\n  \
  \  template_id: 42\n    disk_size:\n      - 35.2 GB\n      - 50 GB\n    memory: 4 GB\n    vcpu: 4\n\
  \    count: 1\n    networks:\n      - NETWORK_ID: 27\n\n- name: \"Deploy an new instance with attribute\
  \ 'bar: bar1' and set its name to 'foo'\"\n  community.general.one_vm:\n    template_id: 53\n    attributes:\n\
  \      name: foo\n      bar: bar1\n\n- name: \"Enforce that 2 instances with attributes 'foo1: app1'\
  \ and 'foo2: app2' are deployed\"\n  community.general.one_vm:\n    template_id: 53\n    attributes:\n\
  \      foo1: app1\n      foo2: app2\n    exact_count: 2\n    count_attributes:\n      foo1: app1\n \
  \     foo2: app2\n\n- name: Enforce that 4 instances with an attribute 'bar' are deployed\n  community.general.one_vm:\n\
  \    template_id: 53\n    attributes:\n      name: app\n      bar: bar2\n    exact_count: 4\n    count_attributes:\n\
  \      bar:\n\n# Deploy 2 new instances with attribute 'foo: bar' and labels 'app1' and 'app2' and names\
  \ in format 'fooapp-##'\n# Names will be: fooapp-00 and fooapp-01\n- name: Deploy 2 new instances\n\
  \  community.general.one_vm:\n    template_id: 53\n    attributes:\n      name: fooapp-##\n      foo:\
  \ bar\n    labels:\n      - app1\n      - app2\n    count: 2\n\n# Deploy 2 new instances with attribute\
  \ 'app: app1' and names in format 'fooapp-###'\n# Names will be: fooapp-002 and fooapp-003\n- name:\
  \ Deploy 2 new instances\n  community.general.one_vm:\n    template_id: 53\n    attributes:\n      name:\
  \ fooapp-###\n      app: app1\n    count: 2\n\n# Reboot all instances with name in format 'fooapp-#'\n\
  # Instances 'fooapp-00', 'fooapp-01', 'fooapp-002' and 'fooapp-003' will be rebooted\n- name: Reboot\
  \ all instances with names in a certain format\n  community.general.one_vm:\n    attributes:\n     \
  \ name: fooapp-#\n    state: rebooted\n\n# Enforce that only 1 instance with name in format 'fooapp-#'\
  \ is deployed\n# The task will delete oldest instances, so only the 'fooapp-003' will remain\n- name:\
  \ Enforce that only 1 instance with name in a certain format is deployed\n  community.general.one_vm:\n\
  \    template_id: 53\n    exact_count: 1\n    count_attributes:\n      name: fooapp-#\n\n- name: Deploy\
  \ an new instance with a network\n  community.general.one_vm:\n    template_id: 53\n    networks:\n\
  \      - NETWORK_ID: 27\n  register: vm\n\n- name: Wait for SSH to come up\n  ansible.builtin.wait_for_connection:\n\
  \  delegate_to: '{{ vm.instances[0].networks[0].ip }}'\n\n- name: Terminate VMs by ids\n  community.general.one_vm:\n\
  \    instance_ids:\n      - 153\n      - 160\n    state: absent\n\n- name: Reboot all VMs that have\
  \ labels 'foo' and 'app1'\n  community.general.one_vm:\n    labels:\n      - foo\n      - app1\n   \
  \ state: rebooted\n\n- name: \"Fetch all VMs that have name 'foo' and attribute 'app: bar'\"\n  community.general.one_vm:\n\
  \    attributes:\n      name: foo\n      app: bar\n  register: results\n\n- name: Deploy 2 new instances\
  \ with labels 'foo1' and 'foo2'\n  community.general.one_vm:\n    template_name: app_template\n    labels:\n\
  \      - foo1\n      - foo2\n    count: 2\n\n- name: Enforce that only 1 instance with label 'foo1'\
  \ will be running\n  community.general.one_vm:\n    template_name: app_template\n    labels:\n     \
  \ - foo1\n    exact_count: 1\n    count_labels:\n      - foo1\n\n- name: Terminate all instances that\
  \ have attribute foo\n  community.general.one_vm:\n    template_id: 53\n    exact_count: 0\n    count_attributes:\n\
  \      foo:\n\n- name: \"Power-off the VM and save VM's disk with id=0 to the image with name 'foo-image'\"\
  \n  community.general.one_vm:\n    instance_ids: 351\n    state: poweredoff\n    disk_saveas:\n    \
  \  name: foo-image\n\n- name: \"Save VM's disk with id=1 to the image with name 'bar-image'\"\n  community.general.one_vm:\n\
  \    instance_ids: 351\n    disk_saveas:\n      name: bar-image\n      disk_id: 1\n\n- name: \"Deploy\
  \ 2 new instances with a custom 'start script'\"\n  community.general.one_vm:\n    template_name: app_template\n\
  \    count: 2\n    updateconf:\n      CONTEXT:\n        START_SCRIPT: ip r r 169.254.16.86/32 dev eth0\n\
  \n- name: \"Add a custom 'start script' to a running VM\"\n  community.general.one_vm:\n    instance_ids:\
  \ 351\n    updateconf:\n      CONTEXT:\n        START_SCRIPT: ip r r 169.254.16.86/32 dev eth0\n\n-\
  \ name: \"Update SSH public keys inside the VM's context\"\n  community.general.one_vm:\n    instance_ids:\
  \ 351\n    updateconf:\n      CONTEXT:\n        SSH_PUBLIC_KEY: |-\n          ssh-rsa ...\n        \
  \  ssh-ed25519 ...\n"
