name: oneview_network_set_info
fqcn: community.general.oneview_network_set_info
collection: community.general
short_description: Retrieve information about the OneView Network Sets
description: Retrieve information about the Network Sets from OneView.
options:
  api_version:
    type: int
    description: OneView API Version.
  config:
    type: path
    description: Path to a JSON configuration file containing the OneView client configuration. The configuration
      file is optional and when used should be present in the host running the ansible commands. If the
      file path is not provided, the configuration will be loaded from environment variables. For links
      to example configuration files or how to use the environment variables verify the notes section.
  hostname:
    type: str
    description: IP address or hostname for the appliance.
  image_streamer_hostname:
    type: str
    description: IP address or hostname for the HPE Image Streamer REST API.
  name:
    type: str
    description: Network Set name.
  options:
    type: list
    description: 'List with options to gather information about Network Set. Option allowed: V(withoutEthernet).
      The option V(withoutEthernet) retrieves the list of network_sets excluding Ethernet networks.'
  params:
    type: dict
    description: 'List of parameters to delimit, filter and sort the list of resources. Parameter keys
      allowed are: C(start): The first item to return, using 0-based indexing. C(count): The number of
      resources to return. C(filter): A general filter/query string to narrow the list of items returned.
      C(sort): The sort order of the returned data set.'
  password:
    type: str
    description: Password for API authentication.
  username:
    type: str
    description: Username for API authentication.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Gather information about all Network Sets\n  community.general.oneview_network_set_info:\n\
  \    hostname: 172.16.101.48\n    username: administrator\n    password: my_password\n    api_version:\
  \ 500\n  no_log: true\n  delegate_to: localhost\n  register: result\n\n- name: Print fetched information\
  \ about Network Sets\n  ansible.builtin.debug:\n    msg: \"{{ result.network_sets }}\"\n\n- name: Gather\
  \ paginated, filtered and sorted information about Network Sets\n  community.general.oneview_network_set_info:\n\
  \    hostname: 172.16.101.48\n    username: administrator\n    password: my_password\n    api_version:\
  \ 500\n    params:\n      start: 0\n      count: 3\n      sort: 'name:descending'\n      filter: name='netset001'\n\
  \  no_log: true\n  delegate_to: localhost\n  register: result\n\n- name: Print fetched information about\
  \ paginated, filtered and sorted list of Network Sets\n  ansible.builtin.debug:\n    msg: \"{{ result.network_sets\
  \ }}\"\n\n- name: Gather information about all Network Sets, excluding Ethernet networks\n  community.general.oneview_network_set_info:\n\
  \    hostname: 172.16.101.48\n    username: administrator\n    password: my_password\n    api_version:\
  \ 500\n    options:\n        - withoutEthernet\n  no_log: true\n  delegate_to: localhost\n  register:\
  \ result\n\n- name: Print fetched information about Network Sets, excluding Ethernet networks\n  ansible.builtin.debug:\n\
  \    msg: \"{{ result.network_sets }}\"\n\n- name: Gather information about a Network Set by name\n\
  \  community.general.oneview_network_set_info:\n    hostname: 172.16.101.48\n    username: administrator\n\
  \    password: my_password\n    api_version: 500\n    name: Name of the Network Set\n  no_log: true\n\
  \  delegate_to: localhost\n  register: result\n\n- name: Print fetched information about Network Set\
  \ found by name\n  ansible.builtin.debug:\n    msg: \"{{ result.network_sets }}\"\n\n- name: Gather\
  \ information about a Network Set by name, excluding Ethernet networks\n  community.general.oneview_network_set_info:\n\
  \    hostname: 172.16.101.48\n    username: administrator\n    password: my_password\n    api_version:\
  \ 500\n    name: Name of the Network Set\n    options:\n        - withoutEthernet\n  no_log: true\n\
  \  delegate_to: localhost\n  register: result\n\n- name: Print fetched information about Network Set\
  \ found by name, excluding Ethernet networks\n  ansible.builtin.debug:\n    msg: \"{{ result.network_sets\
  \ }}\"\n"
