name: oneview_san_manager
fqcn: community.general.oneview_san_manager
collection: community.general
short_description: Manage OneView SAN Manager resources
description: Provides an interface to manage SAN Manager resources. Can create, update, or delete.
options:
  api_version:
    type: int
    description: OneView API Version.
  config:
    type: path
    description: Path to a JSON configuration file containing the OneView client configuration. The configuration
      file is optional and when used should be present in the host running the ansible commands. If the
      file path is not provided, the configuration will be loaded from environment variables. For links
      to example configuration files or how to use the environment variables verify the notes section.
  data:
    type: dict
    required: true
    description: List with SAN Manager properties.
  hostname:
    type: str
    description: IP address or hostname for the appliance.
  image_streamer_hostname:
    type: str
    description: IP address or hostname for the HPE Image Streamer REST API.
  password:
    type: str
    description: Password for API authentication.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    - connection_information_set
    description: Indicates the desired state for the Uplink Set resource. - V(present) ensures data properties
      are compliant with OneView. - V(absent) removes the resource from OneView, if it exists. - V(connection_information_set)
      updates the connection information for the SAN Manager. This operation is non-idempotent.
  username:
    type: str
    description: Username for API authentication.
  validate_etag:
    type: bool
    default: true
    description: When the ETag Validation is enabled, the request will be conditionally processed only
      if the current ETag for the resource matches the ETag provided in the data.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Creates a Device Manager for the Brocade SAN provider with the given hostname and\
  \ credentials\n  community.general.oneview_san_manager:\n    config: /etc/oneview/oneview_config.json\n\
  \    state: present\n    data:\n      providerDisplayName: Brocade Network Advisor\n      connectionInfo:\n\
  \        - name: Host\n          value: 172.18.15.1\n        - name: Port\n          value: 5989\n \
  \       - name: Username\n          value: username\n        - name: Password\n          value: password\n\
  \        - name: UseSsl\n          value: true\n  delegate_to: localhost\n\n- name: Ensure a Device\
  \ Manager for the Cisco SAN Provider is present\n  community.general.oneview_san_manager:\n    config:\
  \ /etc/oneview/oneview_config.json\n    state: present\n    data:\n      name: 172.18.20.1\n      providerDisplayName:\
  \ Cisco\n      connectionInfo:\n        - name: Host\n          value: 172.18.20.1\n        - name:\
  \ SnmpPort\n          value: 161\n        - name: SnmpUserName\n          value: admin\n        - name:\
  \ SnmpAuthLevel\n          value: authnopriv\n        - name: SnmpAuthProtocol\n          value: sha\n\
  \        - name: SnmpAuthString\n          value: password\n  delegate_to: localhost\n\n- name: Sets\
  \ the SAN Manager connection information\n  community.general.oneview_san_manager:\n    config: /etc/oneview/oneview_config.json\n\
  \    state: connection_information_set\n    data:\n      connectionInfo:\n        - name: Host\n   \
  \       value: '172.18.15.1'\n        - name: Port\n          value: '5989'\n        - name: Username\n\
  \          value: 'username'\n        - name: Password\n          value: 'password'\n        - name:\
  \ UseSsl\n          value: true\n  delegate_to: localhost\n\n- name: Refreshes the SAN Manager\n  community.general.oneview_san_manager:\n\
  \    config: /etc/oneview/oneview_config.json\n    state: present\n    data:\n      name: 172.18.15.1\n\
  \      refreshState: RefreshPending\n  delegate_to: localhost\n\n- name: Delete the SAN Manager recently\
  \ created\n  community.general.oneview_san_manager:\n    config: /etc/oneview/oneview_config.json\n\
  \    state: absent\n    data:\n      name: '172.18.15.1'\n  delegate_to: localhost\n"
