name: oneview_enclosure_info
fqcn: community.general.oneview_enclosure_info
collection: community.general
short_description: Retrieve information about one or more Enclosures
description: Retrieve information about one or more of the Enclosures from OneView.
options:
  api_version:
    type: int
    description: OneView API Version.
  config:
    type: path
    description: Path to a JSON configuration file containing the OneView client configuration. The configuration
      file is optional and when used should be present in the host running the ansible commands. If the
      file path is not provided, the configuration will be loaded from environment variables. For links
      to example configuration files or how to use the environment variables verify the notes section.
  hostname:
    type: str
    description: IP address or hostname for the appliance.
  image_streamer_hostname:
    type: str
    description: IP address or hostname for the HPE Image Streamer REST API.
  name:
    type: str
    description: Enclosure name.
  options:
    type: list
    description: 'List with options to gather additional information about an Enclosure and related resources.
      Options allowed: V(script), V(environmentalConfiguration), and V(utilization). For the option V(utilization),
      you can provide specific parameters.'
  params:
    type: dict
    description: 'List of parameters to delimit, filter and sort the list of resources. Parameter keys
      allowed are: C(start): The first item to return, using 0-based indexing. C(count): The number of
      resources to return. C(filter): A general filter/query string to narrow the list of items returned.
      C(sort): The sort order of the returned data set.'
  password:
    type: str
    description: Password for API authentication.
  username:
    type: str
    description: Username for API authentication.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Gather information about all Enclosures\n  community.general.oneview_enclosure_info:\n\
  \    hostname: 172.16.101.48\n    username: administrator\n    password: my_password\n    api_version:\
  \ 500\n  no_log: true\n  delegate_to: localhost\n  register: result\n\n- name: Print fetched information\
  \ about Enclosures\n  ansible.builtin.debug:\n    msg: \"{{ result.enclosures }}\"\n\n- name: Gather\
  \ paginated, filtered and sorted information about Enclosures\n  community.general.oneview_enclosure_info:\n\
  \    params:\n      start: 0\n      count: 3\n      sort: name:descending\n      filter: status=OK\n\
  \    hostname: 172.16.101.48\n    username: administrator\n    password: my_password\n    api_version:\
  \ 500\n  no_log: true\n  delegate_to: localhost\n  register: result\n\n- name: Print fetched information\
  \ about paginated, filtered and sorted list of Enclosures\n  ansible.builtin.debug:\n    msg: \"{{ result.enclosures\
  \ }}\"\n\n- name: Gather information about an Enclosure by name\n  community.general.oneview_enclosure_info:\n\
  \    name: Enclosure-Name\n    hostname: 172.16.101.48\n    username: administrator\n    password: my_password\n\
  \    api_version: 500\n  no_log: true\n  delegate_to: localhost\n  register: result\n\n- name: Print\
  \ fetched information about Enclosure found by name\n  ansible.builtin.debug:\n    msg: \"{{ result.enclosures\
  \ }}\"\n\n- name: Gather information about an Enclosure by name with options\n  community.general.oneview_enclosure_info:\n\
  \    name: Test-Enclosure\n    options:\n      - script                       # optional\n      - environmentalConfiguration\
  \   # optional\n      - utilization                  # optional\n    hostname: 172.16.101.48\n    username:\
  \ administrator\n    password: my_password\n    api_version: 500\n  no_log: true\n  delegate_to: localhost\n\
  \  register: result\n\n- name: Print fetched information about Enclosure found by name\n  ansible.builtin.debug:\n\
  \    msg: \"{{ result.enclosures }}\"\n\n- name: Print fetched information about Enclosure Script\n\
  \  ansible.builtin.debug:\n    msg: \"{{ result.enclosure_script }}\"\n\n- name: Print fetched information\
  \ about Enclosure Environmental Configuration\n  ansible.builtin.debug:\n    msg: \"{{ result.enclosure_environmental_configuration\
  \ }}\"\n\n- name: Print fetched information about Enclosure Utilization\n  ansible.builtin.debug:\n\
  \    msg: \"{{ result.enclosure_utilization }}\"\n\n- name: \"Gather information about an Enclosure\
  \ with temperature data at a resolution of one sample per day, between two\n         specified dates\"\
  \n  community.general.oneview_enclosure_info:\n    name: Test-Enclosure\n    options:\n      - utilization:\
  \                   # optional\n          fields: AmbientTemperature\n          filter:\n          \
  \  - startDate=2016-07-01T14:29:42.000Z\n            - endDate=2017-07-01T03:29:42.000Z\n          view:\
  \ day\n          refresh: false\n    hostname: 172.16.101.48\n    username: administrator\n    password:\
  \ my_password\n    api_version: 500\n  no_log: true\n  delegate_to: localhost\n  register: result\n\n\
  - name: Print fetched information about Enclosure found by name\n  ansible.builtin.debug:\n    msg:\
  \ \"{{ result.enclosures }}\"\n\n- name: Print fetched information about Enclosure Utilization\n  ansible.builtin.debug:\n\
  \    msg: \"{{ result.enclosure_utilization }}\"\n"
