name: osx_defaults
fqcn: community.general.osx_defaults
collection: community.general
short_description: Manage macOS user defaults
description: osx_defaults allows users to read, write, and delete macOS user defaults from Ansible scripts.
  macOS applications and other programs use the defaults system to record user preferences and other information
  that must be maintained when the applications are not running (such as default font for new documents,
  or the position of an Info panel).
options:
  array_add:
    type: bool
    default: false
    description: Add new elements to the array for a key which has an array as its value.
  domain:
    type: str
    default: NSGlobalDomain
    description: The domain is a domain name of the form C(com.companyname.appname).
  host:
    type: str
    description: The host on which the preference should apply. The special value V(currentHost) corresponds
      to the C(-currentHost) switch of the defaults commandline tool.
  key:
    type: str
    description: The key of the user preference.
  path:
    type: str
    default: /usr/bin:/usr/local/bin
    description: The path in which to search for C(defaults).
  state:
    type: str
    default: present
    choices:
    - absent
    - list
    - present
    description: The state of the user defaults. If set to V(list) will query the given parameter specified
      by O(key). Returns V(null) is nothing found or mis-spelled.
  type:
    type: str
    default: string
    choices:
    - array
    - bool
    - boolean
    - date
    - float
    - int
    - integer
    - string
    description: The type of value to write.
  value:
    type: raw
    description: The value to write. Only required when O(state=present).
writes: true
runtime: starlark
source: translated
examples: "\n- name: Set boolean valued key for application domain\n  community.general.osx_defaults:\n\
  \    domain: com.apple.Safari\n    key: IncludeInternalDebugMenu\n    type: bool\n    value: true\n\
  \    state: present\n\n- name: Set string valued key for global domain\n  community.general.osx_defaults:\n\
  \    domain: NSGlobalDomain\n    key: AppleMeasurementUnits\n    type: string\n    value: Centimeters\n\
  \    state: present\n\n- name: Set int valued key for arbitrary plist\n  community.general.osx_defaults:\n\
  \    domain: /Library/Preferences/com.apple.SoftwareUpdate\n    key: AutomaticCheckEnabled\n    type:\
  \ int\n    value: 1\n  become: true\n\n- name: Set int valued key only for the current host\n  community.general.osx_defaults:\n\
  \    domain: com.apple.screensaver\n    host: currentHost\n    key: showClock\n    type: int\n    value:\
  \ 1\n\n- name: Defaults to global domain and setting value\n  community.general.osx_defaults:\n    key:\
  \ AppleMeasurementUnits\n    type: string\n    value: Centimeters\n\n- name: Setting an array valued\
  \ key\n  community.general.osx_defaults:\n    key: AppleLanguages\n    type: array\n    value:\n   \
  \   - en\n      - nl\n\n- name: Removing a key\n  community.general.osx_defaults:\n    domain: com.geekchimp.macable\n\
  \    key: ExampleKeyToRemove\n    state: absent\n"
