name: packet_volume
fqcn: community.general.packet_volume
collection: community.general
short_description: Create/delete a volume in Packet host
description: Create/delete a volume in Packet host. API is documented at U(https://www.packet.com/developers/api/#volumes).
options:
  auth_token:
    type: str
    description: Packet API token. You can also supply it in environment variable E(PACKET_API_TOKEN).
  billing_cycle:
    type: str
    default: hourly
    choices:
    - hourly
    - monthly
    description: Billing cycle for new volume.
  description:
    type: str
    description: User-defined description attribute for Packet volume. It is used used as idempotent identifier
      - if volume with given description exists, new one is not created.
  facility:
    type: str
    description: Location of the volume. Volumes can only be attached to device in the same location.
  id:
    type: str
    description: UUID of a volume.
  locked:
    type: bool
    default: false
    description: Create new volume locked.
  name:
    type: str
    description: Selector for API-generated name of the volume
  plan:
    type: str
    default: storage_1
    choices:
    - storage_1
    - storage_2
    description: storage_1 for standard tier, storage_2 for premium (performance) tier. Tiers are described
      at U(https://www.packet.com/cloud/storage/).
  project_id:
    type: str
    required: true
    description: ID of project of the device.
  size:
    type: int
    description: Size of the volume in gigabytes.
  snapshot_policy:
    type: dict
    description: Snapshot policy for new volume.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Desired state of the volume.
writes: true
runtime: starlark
source: translated
examples: "\n# All the examples assume that you have your Packet API token in env var PACKET_API_TOKEN.\n\
  # You can also pass the api token in module param auth_token.\n\n- hosts: localhost\n  vars:\n    volname:\
  \ testvol123\n    project_id: 53000fb2-ee46-4673-93a8-de2c2bdba33b\n\n  tasks:\n    - name: Create volume\n\
  \      community.general.packet_volume:\n        description: \"{{ volname }}\"\n        project_id:\
  \ \"{{ project_id }}\"\n        facility: 'ewr1'\n        plan: 'storage_1'\n        state: present\n\
  \        size: 10\n        snapshot_policy:\n          snapshot_count: 10\n          snapshot_frequency:\
  \ 1day\n      register: result_create\n\n    - name: Delete volume\n      community.general.packet_volume:\n\
  \        id: \"{{ result_create.id }}\"\n        project_id: \"{{ project_id }}\"\n        state: absent\n"
