name: pamd
fqcn: community.general.pamd
collection: community.general
short_description: Manage PAM Modules
description: Edit PAM service's type, control, module path and module arguments. In order for a PAM rule
  to be modified, the type, control and module_path must match an existing rule. See man(5) pam.d for
  details.
options:
  backup:
    type: bool
    default: false
    description: Create a backup file including the timestamp information so you can get the original
      file back if you somehow clobbered it incorrectly.
  control:
    type: str
    required: true
    description: The control of the PAM rule being modified. This may be a complicated control with brackets.
      If this is the case, be sure to put "[bracketed controls]" in quotes. The O(type), O(control), and
      O(module_path) options all must match a rule to be modified.
  module_arguments:
    type: list
    description: When O(state=updated), the O(module_arguments) will replace existing module_arguments.
      When O(state=args_absent) args matching those listed in O(module_arguments) will be removed. When
      O(state=args_present) any args listed in O(module_arguments) are added if missing from the existing
      rule. Furthermore, if the module argument takes a value denoted by C(=), the value will be changed
      to that specified in module_arguments.
  module_path:
    type: str
    required: true
    description: The module path of the PAM rule being modified. The O(type), O(control), and O(module_path)
      options all must match a rule to be modified.
  name:
    type: str
    required: true
    description: The name generally refers to the PAM service file to change, for example system-auth.
  new_control:
    type: str
    description: The new control to assign to the new rule.
  new_module_path:
    type: str
    description: The new module path to be assigned to the new rule.
  new_type:
    type: str
    choices:
    - account
    - -account
    - auth
    - -auth
    - password
    - -password
    - session
    - -session
    description: The new type to assign to the new rule.
  path:
    type: path
    default: /etc/pam.d
    description: This is the path to the PAM service files.
  state:
    type: str
    default: updated
    choices:
    - absent
    - before
    - after
    - args_absent
    - args_present
    - updated
    description: The default of V(updated) will modify an existing rule if type, control and module_path
      all match an existing rule. With V(before), the new rule will be inserted before a rule matching
      type, control and module_path. Similarly, with V(after), the new rule will be inserted after an
      existing rulematching type, control and module_path. With either V(before) or V(after) O(new_type),
      O(new_control), and O(new_module_path) must all be specified. If state is V(args_absent) or V(args_present),
      O(new_type), O(new_control), and O(new_module_path) will be ignored. State V(absent) will remove
      the rule.
  type:
    type: str
    required: true
    choices:
    - account
    - -account
    - auth
    - -auth
    - password
    - -password
    - session
    - -session
    description: The type of the PAM rule being modified. The O(type), O(control), and O(module_path)
      options all must match a rule to be modified.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Update pamd rule's control in /etc/pam.d/system-auth\n  community.general.pamd:\n\
  \    name: system-auth\n    type: auth\n    control: required\n    module_path: pam_faillock.so\n  \
  \  new_control: sufficient\n\n- name: Update pamd rule's complex control in /etc/pam.d/system-auth\n\
  \  community.general.pamd:\n    name: system-auth\n    type: session\n    control: '[success=1 default=ignore]'\n\
  \    module_path: pam_succeed_if.so\n    new_control: '[success=2 default=ignore]'\n\n- name: Insert\
  \ a new rule before an existing rule\n  community.general.pamd:\n    name: system-auth\n    type: auth\n\
  \    control: required\n    module_path: pam_faillock.so\n    new_type: auth\n    new_control: sufficient\n\
  \    new_module_path: pam_faillock.so\n    state: before\n\n- name: Insert a new rule pam_wheel.so with\
  \ argument 'use_uid' after an \\\n        existing rule pam_rootok.so\n  community.general.pamd:\n \
  \   name: su\n    type: auth\n    control: sufficient\n    module_path: pam_rootok.so\n    new_type:\
  \ auth\n    new_control: required\n    new_module_path: pam_wheel.so\n    module_arguments: 'use_uid'\n\
  \    state: after\n\n- name: Remove module arguments from an existing rule\n  community.general.pamd:\n\
  \    name: system-auth\n    type: auth\n    control: required\n    module_path: pam_faillock.so\n  \
  \  module_arguments: ''\n    state: updated\n\n- name: Replace all module arguments in an existing rule\n\
  \  community.general.pamd:\n    name: system-auth\n    type: auth\n    control: required\n    module_path:\
  \ pam_faillock.so\n    module_arguments: 'preauth\n        silent\n        deny=3\n        unlock_time=604800\n\
  \        fail_interval=900'\n    state: updated\n\n- name: Remove specific arguments from a rule\n \
  \ community.general.pamd:\n    name: system-auth\n    type: session\n    control: '[success=1 default=ignore]'\n\
  \    module_path: pam_succeed_if.so\n    module_arguments: crond,quiet\n    state: args_absent\n\n-\
  \ name: Ensure specific arguments are present in a rule\n  community.general.pamd:\n    name: system-auth\n\
  \    type: session\n    control: '[success=1 default=ignore]'\n    module_path: pam_succeed_if.so\n\
  \    module_arguments: crond,quiet\n    state: args_present\n\n- name: Ensure specific arguments are\
  \ present in a rule (alternative)\n  community.general.pamd:\n    name: system-auth\n    type: session\n\
  \    control: '[success=1 default=ignore]'\n    module_path: pam_succeed_if.so\n    module_arguments:\n\
  \    - crond\n    - quiet\n    state: args_present\n\n- name: Module arguments requiring commas must\
  \ be listed as a Yaml list\n  community.general.pamd:\n    name: special-module\n    type: account\n\
  \    control: required\n    module_path: pam_access.so\n    module_arguments:\n    - listsep=,\n   \
  \ state: args_present\n\n- name: Update specific argument value in a rule\n  community.general.pamd:\n\
  \    name: system-auth\n    type: auth\n    control: required\n    module_path: pam_faillock.so\n  \
  \  module_arguments: 'fail_interval=300'\n    state: args_present\n\n- name: Add pam common-auth rule\
  \ for duo\n  community.general.pamd:\n    name: common-auth\n    new_type: auth\n    new_control: '[success=1\
  \ default=ignore]'\n    new_module_path: '/lib64/security/pam_duo.so'\n    state: after\n    type: auth\n\
  \    module_path: pam_sss.so\n    control: 'requisite'\n"
