name: pingdom
fqcn: community.general.pingdom
collection: community.general
short_description: Pause/unpause Pingdom alerts
description: This module will let you pause/unpause Pingdom alerts
options:
  checkid:
    type: str
    required: true
    description: Pingdom ID of the check.
  key:
    type: str
    required: true
    description: Pingdom API key.
  passwd:
    type: str
    required: true
    description: Pingdom user password.
  state:
    type: str
    required: true
    choices:
    - running
    - paused
    - started
    - stopped
    description: Define whether or not the check should be running or paused.
  uid:
    type: str
    required: true
    description: Pingdom user ID.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Pause the check with the ID of 12345\n  community.general.pingdom:\n    uid: example@example.com\n\
  \    passwd: password123\n    key: apipassword123\n    checkid: 12345\n    state: paused\n\n- name:\
  \ Unpause the check with the ID of 12345\n  community.general.pingdom:\n    uid: example@example.com\n\
  \    passwd: password123\n    key: apipassword123\n    checkid: 12345\n    state: running\n"
