name: pkgin
fqcn: community.general.pkgin
collection: community.general
short_description: Package manager for SmartOS, NetBSD, et al
description: 'The standard package manager for SmartOS, but also usable on NetBSD or any OS that uses
  C(pkgsrc).  (Home: U(http://pkgin.net/))'
options:
  clean:
    type: bool
    default: false
    description: Clean packages cache
  force:
    type: bool
    default: false
    description: Force package reinstall
  full_upgrade:
    type: bool
    default: false
    description: Upgrade all packages to their newer versions
  name:
    type: list
    aliases:
    - pkg
    description: Name of package to install/remove; multiple names may be given, separated by commas
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Intended state of the package
  update_cache:
    type: bool
    default: false
    description: Update repository database. Can be run with other steps or on it's own.
  upgrade:
    type: bool
    default: false
    description: Upgrade main packages to their newer versions
writes: true
runtime: starlark
source: translated
examples: "\n- name: Install package foo\n  community.general.pkgin:\n    name: foo\n    state: present\n\
  \n- name: Install specific version of foo package\n  community.general.pkgin:\n    name: foo-2.0.1\n\
  \    state: present\n\n- name: Update cache and install foo package\n  community.general.pkgin:\n  \
  \  name: foo\n    update_cache: true\n\n- name: Remove package foo\n  community.general.pkgin:\n   \
  \ name: foo\n    state: absent\n\n- name: Remove packages foo and bar\n  community.general.pkgin:\n\
  \    name: foo,bar\n    state: absent\n\n- name: Update repositories as a separate step\n  community.general.pkgin:\n\
  \    update_cache: true\n\n- name: Upgrade main packages (equivalent to pkgin upgrade)\n  community.general.pkgin:\n\
  \    upgrade: true\n\n- name: Upgrade all packages (equivalent to pkgin full-upgrade)\n  community.general.pkgin:\n\
  \    full_upgrade: true\n\n- name: Force-upgrade all packages (equivalent to pkgin -F full-upgrade)\n\
  \  community.general.pkgin:\n    full_upgrade: true\n    force: true\n\n- name: Clean packages cache\
  \ (equivalent to pkgin clean)\n  community.general.pkgin:\n    clean: true\n"
