name: portinstall
fqcn: community.general.portinstall
collection: community.general
short_description: Installing packages from FreeBSD's ports system
description: Manage packages for FreeBSD using 'portinstall'.
options:
  name:
    type: str
    required: true
    aliases:
    - pkg
    description: name of package to install/remove
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: state of the package
  use_packages:
    type: bool
    default: true
    description: use packages instead of ports whenever available
writes: true
runtime: starlark
source: translated
examples: "\n- name: Install package foo\n  community.general.portinstall:\n    name: foo\n    state:\
  \ present\n\n- name: Install package security/cyrus-sasl2-saslauthd\n  community.general.portinstall:\n\
  \    name: security/cyrus-sasl2-saslauthd\n    state: present\n\n- name: Remove packages foo and bar\n\
  \  community.general.portinstall:\n    name: foo,bar\n    state: absent\n"
