name: portage
fqcn: community.general.portage
collection: community.general
short_description: Package manager for Gentoo
description: Manages Gentoo packages
options:
  backtrack:
    type: int
    description: Set backtrack value (C(--backtrack)).
  changed_use:
    type: bool
    default: false
    description: Include installed packages where USE flags have changed, except when flags that the user
      has not enabled are added or removed (--changed-use)
  deep:
    type: bool
    default: false
    description: Consider the entire dependency tree of packages (--deep)
  depclean:
    type: bool
    default: false
    description: Remove packages not needed by explicitly merged packages (--depclean) If no package is
      specified, clean up the world's dependencies Otherwise, --depclean serves as a dependency aware
      version of --unmerge
  getbinpkg:
    type: bool
    default: false
    description: Prefer packages specified at C(PORTAGE_BINHOST) in C(make.conf).
  getbinpkgonly:
    type: bool
    default: false
    description: Merge only packages specified at C(PORTAGE_BINHOST) in C(make.conf).
  jobs:
    type: int
    description: 'Specifies the number of packages to build simultaneously. Since version 2.6: Value of
      0 or False resets any previously added --jobs setting values'
  keepgoing:
    type: bool
    default: false
    description: Continue as much as possible after an error.
  loadavg:
    type: float
    description: 'Specifies that no new builds should be started if there are other builds running and
      the load average is at least LOAD Since version 2.6: Value of 0 or False resets any previously added
      --load-average setting values'
  newuse:
    type: bool
    default: false
    description: Include installed packages where USE flags have changed (--newuse)
  nodeps:
    type: bool
    default: false
    description: Only merge packages but not their dependencies (--nodeps)
  noreplace:
    type: bool
    default: true
    description: Do not re-emerge installed packages (--noreplace)
  oneshot:
    type: bool
    default: false
    description: Do not add the packages to the world file (--oneshot)
  onlydeps:
    type: bool
    default: false
    description: Only merge packages' dependencies but not the packages (--onlydeps)
  package:
    type: list
    aliases:
    - name
    description: Package atom or set, for example V(sys-apps/foo) or V(>foo-2.13) or V(@world)
  quiet:
    type: bool
    default: false
    description: Run emerge in quiet mode (--quiet)
  quietbuild:
    type: bool
    default: false
    description: Redirect all build output to logs alone, and do not display it on stdout (--quiet-build)
  quietfail:
    type: bool
    default: false
    description: Suppresses display of the build log on stdout (--quiet-fail) Only the die message and
      the path of the build log will be displayed on stdout.
  state:
    type: str
    default: present
    choices:
    - present
    - installed
    - emerged
    - absent
    - removed
    - unmerged
    - latest
    description: State of the package atom
  sync:
    type: str
    choices:
    - web
    - 'yes'
    - 'no'
    description: Sync package repositories first If V(yes), perform "emerge --sync" If V(web), perform
      "emerge-webrsync"
  update:
    type: bool
    default: false
    description: Update packages to the best version available (--update)
  usepkg:
    type: bool
    default: false
    description: Tries to use the binary package(s) in the locally available packages directory.
  usepkgonly:
    type: bool
    default: false
    description: Merge only binaries (no compiling).
  verbose:
    type: bool
    default: false
    description: Run emerge in verbose mode (--verbose)
  withbdeps:
    type: bool
    description: Specifies that build time dependencies should be installed.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Make sure package foo is installed\n  community.general.portage:\n    package: foo\n\
  \    state: present\n\n- name: Make sure package foo is not installed\n  community.general.portage:\n\
  \    package: foo\n    state: absent\n\n- name: Update package foo to the latest version (os specific\
  \ alternative to latest)\n  community.general.portage:\n    package: foo\n    update: true\n\n- name:\
  \ Install package foo using PORTAGE_BINHOST setup\n  community.general.portage:\n    package: foo\n\
  \    getbinpkg: true\n\n- name: Re-install world from binary packages only and do not allow any compiling\n\
  \  community.general.portage:\n    package: '@world'\n    usepkgonly: true\n\n- name: Sync repositories\
  \ and update world\n  community.general.portage:\n    package: '@world'\n    update: true\n    deep:\
  \ true\n    sync: true\n\n- name: Remove unneeded packages\n  community.general.portage:\n    depclean:\
  \ true\n\n- name: Remove package foo if it is not explicitly needed\n  community.general.portage:\n\
  \    package: foo\n    state: absent\n    depclean: true\n"
