name: profitbricks_volume_attachments
fqcn: community.general.profitbricks_volume_attachments
collection: community.general
short_description: Attach or detach a volume
description: Allows you to attach or detach a volume from a ProfitBricks server. This module has a dependency
  on profitbricks >= 1.0.0
options:
  datacenter:
    type: str
    description: The datacenter in which to operate.
  server:
    type: str
    description: The name of the server you wish to detach or attach the volume.
  state:
    type: str
    default: present
    description: 'Indicate desired state of the resource The available choices are: V(present), V(absent).'
  subscription_password:
    type: str
    description: THe ProfitBricks password. Overrides the PB_PASSWORD environment variable.
  subscription_user:
    type: str
    description: The ProfitBricks username. Overrides the PB_SUBSCRIPTION_ID environment variable.
  volume:
    type: str
    description: The volume name or ID.
  wait:
    type: bool
    default: true
    description: wait for the operation to complete before returning
  wait_timeout:
    type: int
    default: 600
    description: how long before wait gives up, in seconds
writes: true
runtime: starlark
source: translated
examples: "\n- name: Attach a volume\n  community.general.profitbricks_volume_attachments:\n    datacenter:\
  \ Tardis One\n    server: node002\n    volume: vol01\n    wait_timeout: 500\n    state: present\n\n\
  - name: Detach a volume\n  community.general.profitbricks_volume_attachments:\n    datacenter: Tardis\
  \ One\n    server: node002\n    volume: vol01\n    wait_timeout: 500\n    state: absent\n"
