name: proxmox_node_info
fqcn: community.general.proxmox_node_info
collection: community.general
short_description: Retrieve information about one or more Proxmox VE nodes
description: Retrieve information about one or more Proxmox VE nodes.
options:
  api_host:
    type: str
    required: true
    description: Specify the target host of the Proxmox VE cluster.
  api_password:
    type: str
    description: Specify the password to authenticate with. You can use E(PROXMOX_PASSWORD) environment
      variable.
  api_token_id:
    type: str
    description: Specify the token ID. Requires C(proxmoxer>=1.1.0) to work.
  api_token_secret:
    type: str
    description: Specify the token secret. Requires C(proxmoxer>=1.1.0) to work.
  api_user:
    type: str
    required: true
    description: Specify the user to authenticate with.
  validate_certs:
    type: bool
    default: false
    description: If V(false), SSL certificates will not be validated. This should only be used on personally
      controlled sites using self-signed certificates.
writes: false
runtime: starlark
source: translated
examples: "\n- name: List existing nodes\n  community.general.proxmox_node_info:\n    api_host: proxmox1\n\
  \    api_user: root@pam\n    api_password: \"{{ password | default(omit) }}\"\n    api_token_id: \"\
  {{ token_id | default(omit) }}\"\n    api_token_secret: \"{{ token_secret | default(omit) }}\"\n  register:\
  \ proxmox_nodes\n"
