name: pushbullet
fqcn: community.general.pushbullet
collection: community.general
short_description: Sends notifications to Pushbullet
description: This module sends push notifications via Pushbullet to channels or devices.
options:
  api_key:
    type: str
    required: true
    description: Push bullet API token
  body:
    type: str
    description: Body of the notification, e.g. Details of the fault you're alerting.
  channel:
    type: str
    description: The channel TAG you wish to broadcast a push notification, as seen on the "My Channels"
      > "Edit your channel" at Pushbullet page.
  device:
    type: str
    description: The device NAME you wish to send a push notification, as seen on the Pushbullet main
      page.
  push_type:
    type: str
    default: note
    choices:
    - note
    - link
    description: Thing you wish to push.
  title:
    type: str
    required: true
    description: Title of the notification.
  url:
    type: str
    description: URL field, used when O(push_type=link).
writes: true
runtime: starlark
source: translated
examples: "\n- name: Sends a push notification to a device\n  community.general.pushbullet:\n    api_key:\
  \ \"ABC123abc123ABC123abc123ABC123ab\"\n    device: \"Chrome\"\n    title: \"You may see this on Google\
  \ Chrome\"\n\n- name: Sends a link to a device\n  community.general.pushbullet:\n    api_key: ABC123abc123ABC123abc123ABC123ab\n\
  \    device: Chrome\n    push_type: link\n    title: Ansible Documentation\n    body: https://docs.ansible.com/\n\
  \n- name: Sends a push notification to a channel\n  community.general.pushbullet:\n    api_key: ABC123abc123ABC123abc123ABC123ab\n\
  \    channel: my-awesome-channel\n    title: Broadcasting a message to the #my-awesome-channel folks\n\
  \n- name: Sends a push notification with title and body to a channel\n  community.general.pushbullet:\n\
  \    api_key: ABC123abc123ABC123abc123ABC123ab\n    channel: my-awesome-channel\n    title: ALERT! Signup\
  \ service is down\n    body: Error rate on signup service is over 90% for more than 2 minutes\n"
