name: python_requirements_info
fqcn: community.general.python_requirements_info
collection: community.general
short_description: Show python path and assert dependency versions
description: Get info about available Python requirements on the target host, including listing required
  libraries and gathering versions.
options:
  dependencies:
    type: list
    default: []
    description: 'A list of version-likes or module names to check for installation. Supported operators:
      <, >, <=, >=, or ==. The bare module name like V(ansible), the module with a specific version like
      V(boto3==1.6.1), or a partial version like V(requests>2) are all valid specifications.

      '
writes: false
runtime: starlark
source: translated
examples: "\n- name: Show python lib/site paths\n  community.general.python_requirements_info:\n\n- name:\
  \ Check for modern boto3 and botocore versions\n  community.general.python_requirements_info:\n    dependencies:\n\
  \      - boto3>1.6\n      - botocore<2\n"
