name: rax_cbs_attachments
fqcn: community.general.rax_cbs_attachments
collection: community.general
short_description: Manipulate Rackspace Cloud Block Storage Volume Attachments
description: Manipulate Rackspace Cloud Block Storage Volume Attachments
options:
  api_key:
    type: str
    aliases:
    - password
    description: Rackspace API key, overrides O(credentials).
  auth_endpoint:
    type: str
    description: The URI of the authentication service. If not specified will be set to U(https://identity.api.rackspacecloud.com/v2.0/).
  credentials:
    type: path
    aliases:
    - creds_file
    description: File to find the Rackspace credentials in. Ignored if O(api_key) and O(username) are
      provided.
  device:
    type: str
    description: The device path to attach the volume to, e.g. /dev/xvde. Before 2.4 this was a required
      field. Now it can be left to null to auto assign the device name.
  env:
    type: str
    description: Environment as configured in C(~/.pyrax.cfg), see U(https://github.com/rackspace/pyrax/blob/master/docs/getting_started.md#pyrax-configuration).
  identity_type:
    type: str
    default: rackspace
    description: Authentication mechanism to use, such as rackspace or keystone.
  region:
    type: str
    description: Region to create an instance in.
  server:
    type: str
    required: true
    description: Name or id of the server to attach/detach
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Indicate desired state of the resource
  tenant_id:
    type: str
    description: The tenant ID used for authentication.
  tenant_name:
    type: str
    description: The tenant name used for authentication.
  username:
    type: str
    description: Rackspace username, overrides O(credentials).
  validate_certs:
    type: bool
    aliases:
    - verify_ssl
    description: Whether or not to require SSL validation of API endpoints.
  volume:
    type: str
    required: true
    description: Name or id of the volume to attach/detach
  wait:
    type: bool
    default: false
    description: wait for the volume to be in 'in-use'/'available' state before returning
  wait_timeout:
    type: int
    default: 300
    description: how long before wait gives up, in seconds
writes: true
runtime: starlark
source: translated
examples: "\n- name: Attach a Block Storage Volume\n  gather_facts: false\n  hosts: local\n  connection:\
  \ local\n  tasks:\n    - name: Storage volume attach request\n      local_action:\n        module: rax_cbs_attachments\n\
  \        credentials: ~/.raxpub\n        volume: my-volume\n        server: my-server\n        device:\
  \ /dev/xvdd\n        region: DFW\n        wait: true\n        state: present\n      register: my_volume\n"
