name: rax_facts
fqcn: community.general.rax_facts
collection: community.general
short_description: Gather facts for Rackspace Cloud Servers
description: Gather facts for Rackspace Cloud Servers.
options:
  address:
    type: str
    description: Server IP address to retrieve facts for, will match any IP assigned to the server
  api_key:
    type: str
    aliases:
    - password
    description: Rackspace API key, overrides O(credentials).
  auth_endpoint:
    type: str
    description: The URI of the authentication service. If not specified will be set to U(https://identity.api.rackspacecloud.com/v2.0/).
  credentials:
    type: path
    aliases:
    - creds_file
    description: File to find the Rackspace credentials in. Ignored if O(api_key) and O(username) are
      provided.
  env:
    type: str
    description: Environment as configured in C(~/.pyrax.cfg), see U(https://github.com/rackspace/pyrax/blob/master/docs/getting_started.md#pyrax-configuration).
  id:
    type: str
    description: Server ID to retrieve facts for
  identity_type:
    type: str
    default: rackspace
    description: Authentication mechanism to use, such as rackspace or keystone.
  name:
    type: str
    description: Server name to retrieve facts for
  region:
    type: str
    description: Region to create an instance in.
  tenant_id:
    type: str
    description: The tenant ID used for authentication.
  tenant_name:
    type: str
    description: The tenant name used for authentication.
  username:
    type: str
    description: Rackspace username, overrides O(credentials).
  validate_certs:
    type: bool
    aliases:
    - verify_ssl
    description: Whether or not to require SSL validation of API endpoints.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Gather info about servers\n  hosts: all\n  gather_facts: false\n  tasks:\n    - name:\
  \ Get facts about servers\n      local_action:\n        module: rax_facts\n        credentials: ~/.raxpub\n\
  \        name: \"{{ inventory_hostname }}\"\n        region: DFW\n    - name: Map some facts\n     \
  \ ansible.builtin.set_fact:\n        ansible_ssh_host: \"{{ rax_accessipv4 }}\"\n"
