name: rhsm_release
fqcn: community.general.rhsm_release
collection: community.general
short_description: Set or Unset RHSM Release version
description: Sets or unsets the release version used by RHSM repositories.
options:
  release:
    type: str
    description: RHSM release version to use. To unset either pass V(null) for this option, or omit this
      option.
writes: true
runtime: starlark
source: translated
examples: "\n# Set release version to 7.1\n- name: Set RHSM release version\n  community.general.rhsm_release:\n\
  \    release: \"7.1\"\n\n# Set release version to 6Server\n- name: Set RHSM release version\n  community.general.rhsm_release:\n\
  \    release: \"6Server\"\n\n# Unset release version\n- name: Unset RHSM release release\n  community.general.rhsm_release:\n\
  \    release: null\n"
