name: rundeck_project
fqcn: community.general.rundeck_project
collection: community.general
short_description: Manage Rundeck projects
description: Create and remove Rundeck projects through HTTP API.
options:
  api_token:
    type: str
    required: true
    aliases:
    - token
    description: Sets the token to authenticate against Rundeck API.
  api_version:
    type: int
    default: 39
    description: Rundeck API version to be used. API version must be at least 14.
  client_cert:
    type: path
    description: PEM formatted certificate chain file to be used for SSL client authentication. This file
      can also include the key as well, and if the key is included, O(client_key) is not required.
  client_key:
    type: path
    description: PEM formatted file that contains your private key to be used for SSL client authentication.
      If O(client_cert) contains both the certificate and key, this option is not required.
  force:
    type: bool
    default: false
    description: If V(yes) do not get a cached copy.
  force_basic_auth:
    type: bool
    default: false
    description: Credentials specified with O(url_username) and O(url_password) should be passed in HTTP
      Header.
  http_agent:
    type: str
    default: ansible-httpget
    description: Header to identify as, generally appears in web server logs.
  name:
    type: str
    required: true
    description: Sets the project name.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Create or remove Rundeck project.
  url:
    type: str
    required: true
    description: HTTP, HTTPS, or FTP URL in the form (http|https|ftp)://[user[:pass]]@host.domain[:port]/path
  url_password:
    type: str
    description: The password for use in HTTP basic authentication. If the O(url_username) parameter is
      not specified, the O(url_password) parameter will not be used.
  url_username:
    type: str
    description: The username for use in HTTP basic authentication. This parameter can be used without
      O(url_password) for sites that allow empty passwords
  use_gssapi:
    type: bool
    default: false
    description: Use GSSAPI to perform the authentication, typically this is for Kerberos or Kerberos
      through Negotiate authentication. Requires the Python library L(gssapi,https://github.com/pythongssapi/python-gssapi)
      to be installed. Credentials for GSSAPI can be specified with O(url_username)/O(url_password) or
      with the GSSAPI env var C(KRB5CCNAME) that specified a custom Kerberos credential cache. NTLM authentication
      is B(not) supported even if the GSSAPI mech for NTLM has been installed.
  use_proxy:
    type: bool
    default: true
    description: If V(no), it will not use a proxy, even if one is defined in an environment variable
      on the target hosts.
  validate_certs:
    type: bool
    default: true
    description: If V(no), SSL certificates will not be validated. This should only be used on personally
      controlled sites using self-signed certificates.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create a rundeck project\n  community.general.rundeck_project:\n    name: \"Project_01\"\
  \n    label: \"Project 01\"\n    description: \"My Project 01\"\n    url: \"https://rundeck.example.org\"\
  \n    api_version: 39\n    api_token: \"mytoken\"\n    state: present\n\n- name: Remove a rundeck project\n\
  \  community.general.rundeck_project:\n    name: \"Project_01\"\n    url: \"https://rundeck.example.org\"\
  \n    api_token: \"mytoken\"\n    state: absent\n"
