name: scaleway_organization_info
fqcn: community.general.scaleway_organization_info
collection: community.general
short_description: Gather information about the Scaleway organizations available
description: Gather information about the Scaleway organizations available.
options:
  api_timeout:
    type: int
    default: 30
    aliases:
    - timeout
    description: HTTP timeout to Scaleway API in seconds.
  api_token:
    type: str
    required: true
    aliases:
    - oauth_token
    description: Scaleway OAuth token.
  api_url:
    type: str
    default: https://account.scaleway.com
    aliases:
    - base_url
    description: Scaleway API URL.
  query_parameters:
    type: dict
    default: {}
    description: List of parameters passed to the query string.
  validate_certs:
    type: bool
    default: true
    description: Validate SSL certs of the Scaleway API.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Gather Scaleway organizations information\n  community.general.scaleway_organization_info:\n\
  \  register: result\n\n- ansible.builtin.debug:\n    msg: \"{{ result.scaleway_organization_info }}\"\
  \n"
