name: scaleway_security_group_info
fqcn: community.general.scaleway_security_group_info
collection: community.general
short_description: Gather information about the Scaleway security groups available
description: Gather information about the Scaleway security groups available.
options:
  api_timeout:
    type: int
    default: 30
    aliases:
    - timeout
    description: HTTP timeout to Scaleway API in seconds.
  api_token:
    type: str
    required: true
    aliases:
    - oauth_token
    description: Scaleway OAuth token.
  api_url:
    type: str
    default: https://api.scaleway.com
    aliases:
    - base_url
    description: Scaleway API URL.
  query_parameters:
    type: dict
    default: {}
    description: List of parameters passed to the query string.
  region:
    type: str
    required: true
    choices:
    - ams1
    - EMEA-NL-EVS
    - par1
    - EMEA-FR-PAR1
    - par2
    - EMEA-FR-PAR2
    - waw1
    - EMEA-PL-WAW1
    description: Scaleway region to use (for example C(par1)).
  validate_certs:
    type: bool
    default: true
    description: Validate SSL certs of the Scaleway API.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Gather Scaleway security groups information\n  community.general.scaleway_security_group_info:\n\
  \    region: par1\n  register: result\n\n- ansible.builtin.debug:\n    msg: \"{{ result.scaleway_security_group_info\
  \ }}\"\n"
