name: scaleway_container_info
fqcn: community.general.scaleway_container_info
collection: community.general
short_description: Retrieve information on Scaleway Container
description: This module return information about a container on Scaleway account.
options:
  api_timeout:
    type: int
    default: 30
    aliases:
    - timeout
    description: HTTP timeout to Scaleway API in seconds.
  api_token:
    type: str
    required: true
    aliases:
    - oauth_token
    description: Scaleway OAuth token.
  api_url:
    type: str
    default: https://api.scaleway.com
    aliases:
    - base_url
    description: Scaleway API URL.
  name:
    type: str
    required: true
    description: Name of the container.
  namespace_id:
    type: str
    required: true
    description: Container namespace identifier.
  query_parameters:
    type: dict
    default: {}
    description: List of parameters passed to the query string.
  region:
    type: str
    required: true
    choices:
    - fr-par
    - nl-ams
    - pl-waw
    description: Scaleway region to use (for example C(fr-par)).
  validate_certs:
    type: bool
    default: true
    description: Validate SSL certs of the Scaleway API.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Get a container info\n  community.general.scaleway_container_info:\n    namespace_id:\
  \ '{{ scw_container_namespace }}'\n    region: fr-par\n    name: my-awesome-container\n  register: container_info_task\n"
