name: snap_alias
fqcn: community.general.snap_alias
collection: community.general
short_description: Manages snap aliases
description: Manages snaps aliases.
options:
  alias:
    type: list
    aliases:
    - aliases
    description: Aliases to be created or removed.
  name:
    type: str
    description: Name of the snap.
  state:
    type: str
    default: present
    choices:
    - absent
    - present
    description: Desired state of the alias.
writes: true
runtime: starlark
source: translated
examples: "\n# Install \"foo\" and \"bar\" snap\n- name: Create snap alias\n  community.general.snap_alias:\n\
  \    name: hello-world\n    alias: hw\n\n- name: Create multiple aliases\n  community.general.snap_alias:\n\
  \    name: hello-world\n    aliases:\n      - hw\n      - hw2\n      - hw3\n    state: present   # optional\n\
  \n- name: Remove one specific aliases\n  community.general.snap_alias:\n    name: hw\n    state: absent\n\
  \n- name: Remove all aliases for snap\n  community.general.snap_alias:\n    name: hello-world\n    state:\
  \ absent\n"
