name: terraform
fqcn: community.general.terraform
collection: community.general
short_description: Manages a Terraform deployment (and plans)
description: Provides support for deploying resources with Terraform and pulling resource information
  back into Ansible.
options:
  backend_config:
    type: dict
    description: A group of key-values to provide at init stage to the -backend-config parameter.
  backend_config_files:
    type: list
    description: The path to a configuration file to provide at init state to the -backend-config parameter.
      This can accept a list of paths to multiple configuration files.
  binary_path:
    type: path
    description: The path of a terraform binary to use, relative to the 'service_path' unless you supply
      an absolute path.
  check_destroy:
    type: bool
    default: false
    description: Apply only when no resources are destroyed. Note that this only prevents "destroy" actions,
      but not "destroy and re-create" actions. This option is ignored when O(state=absent).
  complex_vars:
    type: bool
    default: false
    description: Enable/disable capability to handle complex variable structures for C(terraform). If
      V(true) the O(variables) also accepts dictionaries, lists, and booleans to be passed to C(terraform).
      Strings that are passed are correctly quoted. When disabled, supports only simple variables (strings,
      integers, and floats), and passes them on unquoted.
  force_init:
    type: bool
    default: false
    description: To avoid duplicating infra, if a state file can't be found this will force a C(terraform
      init). Generally, this should be turned off unless you intend to provision an entirely new Terraform
      deployment.
  init_reconfigure:
    type: bool
    default: false
    description: Forces backend reconfiguration during init.
  lock:
    type: bool
    default: true
    description: Enable statefile locking, if you use a service that accepts locks (such as S3+DynamoDB)
      to store your statefile.
  lock_timeout:
    type: int
    description: How long to maintain the lock on the statefile, if you use a service that accepts locks
      (such as S3+DynamoDB).
  overwrite_init:
    type: bool
    default: true
    description: Run init even if C(.terraform/terraform.tfstate) already exists in O(project_path).
  parallelism:
    type: int
    description: Restrict concurrent operations when Terraform applies the plan.
  plan_file:
    type: path
    description: The path to an existing Terraform plan file to apply. If this is not specified, Ansible
      will build a new TF plan and execute it. Note that this option is required if 'state' has the 'planned'
      value.
  plugin_paths:
    type: list
    description: List of paths containing Terraform plugin executable files. Plugin executables can be
      downloaded from U(https://releases.hashicorp.com/). When set, the plugin discovery and auto-download
      behavior of Terraform is disabled. The directory structure in the plugin path can be tricky. The
      Terraform docs U(https://learn.hashicorp.com/tutorials/terraform/automate-terraform#pre-installed-plugins)
      show a simple directory of files, but actually, the directory structure has to follow the same structure
      you would see if Terraform auto-downloaded the plugins. See the examples below for a tree output
      of an example plugin directory.
  project_path:
    type: path
    required: true
    description: The path to the root of the Terraform directory with the vars.tf/main.tf/etc to use.
  provider_upgrade:
    type: bool
    default: false
    description: Allows Terraform init to upgrade providers to versions specified in the project's version
      constraints.
  purge_workspace:
    type: bool
    default: false
    description: Only works with state = absent If true, the workspace will be deleted after the "terraform
      destroy" action. The 'default' workspace will not be deleted.
  state:
    type: str
    default: present
    choices:
    - planned
    - present
    - absent
    description: Goal state of given stage/project
  state_file:
    type: path
    description: The path to an existing Terraform state file to use when building plan. If this is not
      specified, the default C(terraform.tfstate) will be used. This option is ignored when plan is specified.
  targets:
    type: list
    default: []
    description: A list of specific resources to target in this plan/application. The resources selected
      here will also auto-include any dependencies.
  variables:
    type: dict
    description: A group of key-values pairs to override template variables or those in variables files.
      By default, only string and number values are allowed, which are passed on unquoted. Support complex
      variable structures (lists, dictionaries, numbers, and booleans) to reflect terraform variable syntax
      when O(complex_vars=true). Ansible integers or floats are mapped to terraform numbers. Ansible strings
      are mapped to terraform strings. Ansible dictionaries are mapped to terraform objects. Ansible lists
      are mapped to terraform lists. Ansible booleans are mapped to terraform booleans. B(Note) passwords
      passed as variables will be visible in the log output. Make sure to use C(no_log=true) in production!
  variables_files:
    type: list
    aliases:
    - variables_file
    description: The path to a variables file for Terraform to fill into the TF configurations. This can
      accept a list of paths to multiple variables files.
  workspace:
    type: str
    default: default
    description: The terraform workspace to work with. This sets the E(TF_WORKSPACE) environmental variable
      that is used to override workspace selection. For more information about workspaces have a look
      at U(https://developer.hashicorp.com/terraform/language/state/workspaces).
writes: true
runtime: starlark
source: translated
examples: "\n- name: Basic deploy of a service\n  community.general.terraform:\n    project_path: '{{\
  \ project_dir }}'\n    state: present\n\n- name: Define the backend configuration at init\n  community.general.terraform:\n\
  \    project_path: 'project/'\n    state: \"{{ state }}\"\n    force_init: true\n    backend_config:\n\
  \      region: \"eu-west-1\"\n      bucket: \"some-bucket\"\n      key: \"random.tfstate\"\n\n- name:\
  \ Define the backend configuration with one or more files at init\n  community.general.terraform:\n\
  \    project_path: 'project/'\n    state: \"{{ state }}\"\n    force_init: true\n    backend_config_files:\n\
  \      - /path/to/backend_config_file_1\n      - /path/to/backend_config_file_2\n\n- name: Disable plugin\
  \ discovery and auto-download by setting plugin_paths\n  community.general.terraform:\n    project_path:\
  \ 'project/'\n    state: \"{{ state }}\"\n    force_init: true\n    plugin_paths:\n      - /path/to/plugins_dir_1\n\
  \      - /path/to/plugins_dir_2\n\n- name: Complex variables example\n  community.general.terraform:\n\
  \    project_path: '{{ project_dir }}'\n    state: present\n    complex_vars: true\n    variables:\n\
  \      vm_name: \"{{ inventory_hostname }}\"\n      vm_vcpus: 2\n      vm_mem: 2048\n      vm_additional_disks:\n\
  \        - label: \"Third Disk\"\n          size: 40\n          thin_provisioned: true\n          unit_number:\
  \ 2\n        - label: \"Fourth Disk\"\n          size: 22\n          thin_provisioned: true\n      \
  \    unit_number: 3\n    force_init: true\n\n### Example directory structure for plugin_paths example\n\
  # $ tree /path/to/plugins_dir_1\n# /path/to/plugins_dir_1/\n# └── registry.terraform.io\n#     └── hashicorp\n\
  #         └── vsphere\n#             ├── 1.24.0\n#             │   └── linux_amd64\n#             │\
  \       └── terraform-provider-vsphere_v1.24.0_x4\n#             └── 1.26.0\n#                 └── linux_amd64\n\
  #                     └── terraform-provider-vsphere_v1.26.0_x4\n"
