name: typetalk
fqcn: community.general.typetalk
collection: community.general
short_description: Send a message to typetalk
description: Send a message to typetalk using typetalk API
options:
  client_id:
    type: str
    required: true
    description: OAuth2 client ID
  client_secret:
    type: str
    required: true
    description: OAuth2 client secret
  msg:
    type: str
    required: true
    description: message body
  topic:
    type: int
    required: true
    description: topic id to post message
writes: true
runtime: starlark
source: translated
examples: "\n- name: Send a message to typetalk\n  community.general.typetalk:\n    client_id: 12345\n\
  \    client_secret: 12345\n    topic: 1\n    msg: install completed\n"
