name: udm_share
fqcn: community.general.udm_share
collection: community.general
short_description: Manage samba shares on a univention corporate server
description: This module allows to manage samba shares on a univention corporate server (UCS). It uses
  the python API of the UCS to create a new object or edit it.
options:
  directorymode:
    type: str
    default: '00755'
    description: Permissions for the share's root directory.
  group:
    type: str
    default: '0'
    description: Directory owner group of the share's root directory.
  host:
    type: str
    description: Host FQDN (server which provides the share), for example V({{ ansible_fqdn }}). Required
      if O(state=present).
  name:
    type: str
    required: true
    description: Name
  nfsCustomSettings:
    type: list
    default: []
    aliases:
    - nfs_custom_settings
    description: Option name in exports file.
  nfs_hosts:
    type: list
    default: []
    description: Only allow access for this host, IP address or network.
  ou:
    type: str
    required: true
    description: Organisational unit, inside the LDAP Base DN.
  owner:
    type: str
    default: '0'
    description: Directory owner of the share's root directory.
  path:
    type: path
    description: Directory on the providing server, for example V(/home). Required if O(state=present).
  root_squash:
    type: bool
    default: true
    description: Modify user ID for root user (root squashing).
  sambaBlockSize:
    type: str
    aliases:
    - samba_block_size
    description: Blocking size.
  sambaBlockingLocks:
    type: bool
    default: true
    aliases:
    - samba_blocking_locks
    description: Blocking locks.
  sambaBrowseable:
    type: bool
    default: true
    aliases:
    - samba_browsable
    description: Show in Windows network environment.
  sambaCreateMode:
    type: str
    default: '0744'
    aliases:
    - samba_create_mode
    description: File mode.
  sambaCscPolicy:
    type: str
    default: manual
    aliases:
    - samba_csc_policy
    description: Client-side caching policy.
  sambaCustomSettings:
    type: list
    default: []
    aliases:
    - samba_custom_settings
    description: Option name in smb.conf and its value.
  sambaDirectoryMode:
    type: str
    default: '0755'
    aliases:
    - samba_directory_mode
    description: Directory mode.
  sambaDirectorySecurityMode:
    type: str
    default: '0777'
    aliases:
    - samba_directory_security_mode
    description: Directory security mode.
  sambaDosFilemode:
    type: bool
    default: false
    aliases:
    - samba_dos_filemode
    description: Users with write access may modify permissions.
  sambaFakeOplocks:
    type: bool
    default: false
    aliases:
    - samba_fake_oplocks
    description: Fake oplocks.
  sambaForceCreateMode:
    type: bool
    default: false
    aliases:
    - samba_force_create_mode
    description: Force file mode.
  sambaForceDirectoryMode:
    type: bool
    default: false
    aliases:
    - samba_force_directory_mode
    description: Force directory mode.
  sambaForceDirectorySecurityMode:
    type: bool
    default: false
    aliases:
    - samba_force_directory_security_mode
    description: Force directory security mode.
  sambaForceGroup:
    type: str
    aliases:
    - samba_force_group
    description: Force group.
  sambaForceSecurityMode:
    type: bool
    default: false
    aliases:
    - samba_force_security_mode
    description: Force security mode.
  sambaForceUser:
    type: str
    aliases:
    - samba_force_user
    description: Force user.
  sambaHideFiles:
    type: str
    aliases:
    - samba_hide_files
    description: Hide files.
  sambaHideUnreadable:
    type: bool
    default: false
    aliases:
    - samba_hide_unreadable
    description: Hide unreadable files/directories.
  sambaHostsAllow:
    type: list
    default: []
    aliases:
    - samba_hosts_allow
    description: Allowed host/network.
  sambaHostsDeny:
    type: list
    default: []
    aliases:
    - samba_hosts_deny
    description: Denied host/network.
  sambaInheritAcls:
    type: bool
    default: true
    aliases:
    - samba_inherit_acls
    description: Inherit ACLs.
  sambaInheritOwner:
    type: bool
    default: false
    aliases:
    - samba_inherit_owner
    description: Create files/directories with the owner of the parent directory.
  sambaInheritPermissions:
    type: bool
    default: false
    aliases:
    - samba_inherit_permissions
    description: Create files/directories with permissions of the parent directory.
  sambaInvalidUsers:
    type: str
    aliases:
    - samba_invalid_users
    description: Invalid users or groups.
  sambaLevel2Oplocks:
    type: bool
    default: true
    aliases:
    - samba_level_2_oplocks
    description: Level 2 oplocks.
  sambaLocking:
    type: bool
    default: true
    aliases:
    - samba_locking
    description: Locking.
  sambaMSDFSRoot:
    type: bool
    default: false
    aliases:
    - samba_msdfs_root
    description: MSDFS root.
  sambaName:
    type: str
    aliases:
    - samba_name
    description: Windows name. Required if O(state=present).
  sambaNtAclSupport:
    type: bool
    default: true
    aliases:
    - samba_nt_acl_support
    description: NT ACL support.
  sambaOplocks:
    type: bool
    default: true
    aliases:
    - samba_oplocks
    description: Oplocks.
  sambaPostexec:
    type: str
    aliases:
    - samba_postexec
    description: Postexec script.
  sambaPreexec:
    type: str
    aliases:
    - samba_preexec
    description: Preexec script.
  sambaPublic:
    type: bool
    default: false
    aliases:
    - samba_public
    description: Allow anonymous read-only access with a guest user.
  sambaSecurityMode:
    type: str
    default: '0777'
    aliases:
    - samba_security_mode
    description: Security mode.
  sambaStrictLocking:
    type: str
    default: Auto
    aliases:
    - samba_strict_locking
    description: Strict locking.
  sambaVFSObjects:
    type: str
    aliases:
    - samba_vfs_objects
    description: VFS objects.
  sambaValidUsers:
    type: str
    aliases:
    - samba_valid_users
    description: Valid users or groups.
  sambaWriteList:
    type: str
    aliases:
    - samba_write_list
    description: Restrict write access to these users/groups.
  sambaWriteable:
    type: bool
    default: true
    aliases:
    - samba_writeable
    description: Samba write access.
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Whether the share is present or not.
  subtree_checking:
    type: bool
    default: true
    description: Subtree checking.
  sync:
    type: str
    default: sync
    description: NFS synchronisation.
  writeable:
    type: bool
    default: true
    description: NFS write access.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create a share named home on the server ucs.example.com with the path /home\n  community.general.udm_share:\n\
  \    name: home\n    path: /home\n    host: ucs.example.com\n    sambaName: Home\n"
