name: acme_challenge_cert_helper
fqcn: community.crypto.acme_challenge_cert_helper
collection: community.crypto
short_description: Prepare certificates required for ACME challenges such as C(tls-alpn-01)
description: Prepares certificates for ACME challenges such as C(tls-alpn-01). The raw data is provided
  by the M(community.crypto.acme_certificate) module, and needs to be converted to a certificate to be
  used for challenge validation. This module provides a simple way to generate the required certificates.
options:
  challenge:
    type: str
    required: true
    choices:
    - tls-alpn-01
    description: The challenge type.
  challenge_data:
    type: dict
    required: true
    description: The RV(community.crypto.acme_certificate#module:challenge_data) entry provided by M(community.crypto.acme_certificate)
      for the challenge.
  private_key_content:
    type: str
    description: Content of the private key to use for this challenge certificate. Mutually exclusive
      with O(private_key_src).
  private_key_passphrase:
    type: str
    description: Phassphrase to use to decode the private key.
  private_key_src:
    type: path
    description: Path to a file containing the private key file to use for this challenge certificate.
      Mutually exclusive with O(private_key_content).
writes: true
runtime: starlark
source: translated
examples: "\n- name: Create challenges for a given CRT for sample.com\n  community.crypto.acme_certificate:\n\
  \    account_key_src: /etc/pki/cert/private/account.key\n    challenge: tls-alpn-01\n    csr: /etc/pki/cert/csr/sample.com.csr\n\
  \    dest: /etc/httpd/ssl/sample.com.crt\n  register: sample_com_challenge\n\n- name: Create certificates\
  \ for challenges\n  community.crypto.acme_challenge_cert_helper:\n    challenge: tls-alpn-01\n    challenge_data:\
  \ \"{{ item.value['tls-alpn-01'] }}\"\n    private_key_src: /etc/pki/cert/key/sample.com.key\n  loop:\
  \ \"{{ sample_com_challenge.challenge_data | dictsort }}\"\n  register: sample_com_challenge_certs\n\
  \n- name: Install challenge certificates\n  # We need to set up HTTPS such that for the domain,\n  #\
  \ regular_certificate is delivered for regular connections,\n  # except if ALPN selects the \"acme-tls/1\"\
  ; then, the\n  # challenge_certificate must be delivered.\n  # This can for example be achieved with\
  \ very new versions\n  # of NGINX; search for ssl_preread and\n  # ssl_preread_alpn_protocols for information\
  \ on how to\n  # route by ALPN protocol.\n  ...:\n    domain: \"{{ item.domain }}\"\n    challenge_certificate:\
  \ \"{{ item.challenge_certificate }}\"\n    regular_certificate: \"{{ item.regular_certificate }}\"\n\
  \    private_key: /etc/pki/cert/key/sample.com.key\n  loop: \"{{ sample_com_challenge_certs.results\
  \ }}\"\n\n- name: Create certificate for a given CSR for sample.com\n  community.crypto.acme_certificate:\n\
  \    account_key_src: /etc/pki/cert/private/account.key\n    challenge: tls-alpn-01\n    csr: /etc/pki/cert/csr/sample.com.csr\n\
  \    dest: /etc/httpd/ssl/sample.com.crt\n    data: \"{{ sample_com_challenge }}\"\n"
