name: crypto_info
fqcn: community.crypto.crypto_info
collection: community.crypto
short_description: Retrieve cryptographic capabilities
description: Retrieve information on cryptographic capabilities. The current version retrieves information
  on the L(Python cryptography library, https://cryptography.io/) available to Ansible modules, and on
  the OpenSSL binary C(openssl) found in the path.
options: {}
writes: false
runtime: starlark
source: translated
examples: "\n- name: Retrieve information\n  community.crypto.crypto_info:\n    account_key_src: /etc/pki/cert/private/account.key\n\
  \  register: crypto_information\n\n- name: Show retrieved information\n  ansible.builtin.debug:\n  \
  \  var: crypto_information\n"
