name: openssl_privatekey_info
fqcn: community.crypto.openssl_privatekey_info
collection: community.crypto
short_description: Provide information for OpenSSL private keys
description: This module allows one to query information on OpenSSL private keys. In case the key consistency
  checks fail, the module will fail as this indicates a faked private key. In this case, all return variables
  are still returned. Note that key consistency checks are not available all key types; if none is available,
  V(none) is returned for RV(key_is_consistent). It uses the cryptography python library to interact with
  OpenSSL.
options:
  check_consistency:
    type: bool
    default: false
    description: Whether to check consistency of the private key. In community.crypto < 2.0.0, consistency
      was always checked. Since community.crypto 2.0.0, the consistency check has been disabled by default
      to avoid private key material to be transported around and computed with, and only do so when requested
      explicitly. This can potentially prevent L(side-channel attacks,https://en.wikipedia.org/wiki/Side-channel_attack).
      Note that consistency checks only work for certain key types, and might depend on the version of
      the cryptography library. For example, with cryptography 42.0.0 and newer consistency of RSA keys
      can no longer be checked.
  content:
    type: str
    description: Content of the private key file. Either O(path) or O(content) must be specified, but
      not both.
  passphrase:
    type: str
    description: The passphrase for the private key.
  path:
    type: path
    description: Remote absolute path where the private key file is loaded from.
  return_private_key_data:
    type: bool
    default: false
    description: Whether to return private key data. Only set this to V(true) when you want private information
      about this key to leave the remote machine. B(WARNING:) you have to make sure that private key data
      is not accidentally logged!
  select_crypto_backend:
    type: str
    default: auto
    choices:
    - auto
    - cryptography
    description: Determines which crypto backend to use. The default choice is V(auto), which tries to
      use C(cryptography) if available. If set to V(cryptography), will try to use the L(cryptography,https://cryptography.io/)
      library.
writes: false
runtime: starlark
source: translated
examples: "\n- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)\n  community.crypto.openssl_privatekey:\n\
  \    path: /etc/ssl/private/ansible.com.pem\n\n- name: Get information on generated key\n  community.crypto.openssl_privatekey_info:\n\
  \    path: /etc/ssl/private/ansible.com.pem\n  register: result\n\n- name: Dump information\n  ansible.builtin.debug:\n\
  \    var: result\n"
