name: openssh_cert
fqcn: community.crypto.openssh_cert
collection: community.crypto
short_description: Generate OpenSSH host or user certificates.
description: Generate and regenerate OpenSSH host or user certificates.
options:
  attributes:
    type: str
    aliases:
    - attr
    description: The attributes the resulting filesystem object should have. To get supported flags look
      at the man page for I(chattr) on the target system. This string should contain the attributes in
      the same order as the one displayed by I(lsattr). The C(=) operator is assumed as default, otherwise
      C(+) or C(-) operators need to be included in the string.
  force:
    type: bool
    default: false
    description: Should the certificate be regenerated even if it already exists and is valid. Equivalent
      to O(regenerate=always).
  group:
    type: str
    description: Name of the group that should own the filesystem object, as would be fed to I(chown).
      When left unspecified, it uses the current group of the current user unless you are root, in which
      case it can preserve the previous ownership.
  identifier:
    type: str
    description: Specify the key identity when signing a public key. The identifier that is logged by
      the server when the certificate is used for authentication.
  ignore_timestamps:
    type: bool
    default: false
    description: Whether the O(valid_from) and O(valid_to) timestamps should be ignored for idempotency
      checks. However, the values will still be applied to a new certificate if it meets any other necessary
      conditions for generation/regeneration.
  mode:
    type: raw
    description: The permissions the resulting filesystem object should have. For those used to I(/usr/bin/chmod)
      remember that modes are actually octal numbers. You must give Ansible enough information to parse
      them correctly. For consistent results, quote octal numbers (for example, V('644') or V('1777'))
      so Ansible receives a string and can do its own conversion from string into number. Adding a leading
      zero (for example, V(0755)) works sometimes, but can fail in loops and some other circumstances.
      Giving Ansible a number without following either of these rules will end up with a decimal number
      which will have unexpected results. As of Ansible 1.8, the mode may be specified as a symbolic mode
      (for example, V(u+rwx) or V(u=rw,g=r,o=r)). If O(mode) is not specified and the destination filesystem
      object B(does not) exist, the default C(umask) on the system will be used when setting the mode
      for the newly created filesystem object. If O(mode) is not specified and the destination filesystem
      object B(does) exist, the mode of the existing filesystem object will be used. Specifying O(mode)
      is the best way to ensure filesystem objects are created with the correct permissions. See CVE-2020-1736
      for further details.
  options:
    type: list
    description: 'Specify certificate options when signing a key. The option that are valid for user certificates
      are: V(clear): Clear all enabled permissions.  This is useful for clearing the default set of permissions
      so permissions may be added individually. V(force-command=command): Forces the execution of command
      instead of any shell or command specified by the user when the certificate is used for authentication.
      V(no-agent-forwarding): Disable ssh-agent forwarding (permitted by default). V(no-port-forwarding):
      Disable port forwarding (permitted by default). V(no-pty): Disable PTY allocation (permitted by
      default). V(no-user-rc): Disable execution of C(~/.ssh/rc) by sshd (permitted by default). V(no-x11-forwarding):
      Disable X11 forwarding (permitted by default) V(permit-agent-forwarding): Allows ssh-agent forwarding.
      V(permit-port-forwarding): Allows port forwarding. V(permit-pty): Allows PTY allocation. V(permit-user-rc):
      Allows execution of C(~/.ssh/rc) by sshd. V(permit-x11-forwarding): Allows X11 forwarding. V(source-address=address_list):
      Restrict the source addresses from which the certificate is considered valid. The C(address_list)
      is a comma-separated list of one or more address/netmask pairs in CIDR format. At present, no options
      are valid for host keys.'
  owner:
    type: str
    description: Name of the user that should own the filesystem object, as would be fed to I(chown).
      When left unspecified, it uses the current user unless you are root, in which case it can preserve
      the previous ownership. Specifying a numeric username will be assumed to be a user ID and not a
      username. Avoid numeric usernames to avoid this confusion.
  path:
    type: path
    required: true
    description: Path of the file containing the certificate.
  pkcs11_provider:
    type: str
    description: To use a signing key that resides on a PKCS#11 token, set this to the name (or full path)
      of the shared library to use with the token. Usually C(libpkcs11.so). If this is set, O(signing_key)
      needs to point to a file containing the public key of the CA.
  principals:
    type: list
    description: Certificates may be limited to be valid for a set of principal (user/host) names. By
      default, generated certificates are valid for all users or hosts.
  public_key:
    type: path
    description: The path to the public key that will be signed with the signing key in order to generate
      the certificate. Required if O(state) is V(present).
  regenerate:
    type: str
    default: partial_idempotence
    choices:
    - never
    - fail
    - partial_idempotence
    - full_idempotence
    - always
    description: When V(never) the task will fail if a certificate already exists at O(path) and is unreadable
      otherwise a new certificate will only be generated if there is no existing certificate. When V(fail)
      the task will fail if a certificate already exists at O(path) and does not match the module's options.
      When V(partial_idempotence) an existing certificate will be regenerated based on O(serial_number),
      O(signature_algorithm), O(type), O(valid_from), O(valid_to), O(valid_at), and O(principals). O(valid_from)
      and O(valid_to) can be excluded by O(ignore_timestamps=true). When V(full_idempotence) O(identifier),
      O(options), O(public_key), and O(signing_key) are also considered when compared against an existing
      certificate. V(always) is equivalent to O(force=true).
  selevel:
    type: str
    description: The level part of the SELinux filesystem object context. This is the MLS/MCS attribute,
      sometimes known as the C(range). When set to V(_default), it will use the C(level) portion of the
      policy if available.
  serial_number:
    type: int
    description: 'Specify the certificate serial number. The serial number is logged by the server when
      the certificate is used for authentication. The certificate serial number may be used in a KeyRevocationList.
      The serial number may be omitted for checks, but must be specified again for a new certificate.
      Note: The default value set by ssh-keygen is 0.'
  serole:
    type: str
    description: The role part of the SELinux filesystem object context. When set to V(_default), it will
      use the C(role) portion of the policy if available.
  setype:
    type: str
    description: The type part of the SELinux filesystem object context. When set to V(_default), it will
      use the C(type) portion of the policy if available.
  seuser:
    type: str
    description: The user part of the SELinux filesystem object context. By default it uses the V(system)
      policy, where applicable. When set to V(_default), it will use the C(user) portion of the policy
      if available.
  signature_algorithm:
    type: str
    choices:
    - ssh-rsa
    - rsa-sha2-256
    - rsa-sha2-512
    description: 'As of OpenSSH 8.2 the SHA-1 signature algorithm for RSA keys has been disabled and C(ssh)
      will refuse host certificates signed with the SHA-1 algorithm. OpenSSH 8.1 made V(rsa-sha2-512)
      the default algorithm when acting as a CA and signing certificates with a RSA key. However, for
      OpenSSH versions less than 8.1 the SHA-2 signature algorithms, V(rsa-sha2-256) or V(rsa-sha2-512),
      must be specified using this option if compatibility with newer C(ssh) clients is required. Conversely
      if hosts using OpenSSH version 8.2 or greater must remain compatible with C(ssh) clients using OpenSSH
      less than 7.2, then V(ssh-rsa) can be used when generating host certificates (a corresponding change
      to the sshd_config to add V(ssh-rsa) to the C(CASignatureAlgorithms) keyword is also required).
      Using any value for this option with a non-RSA O(signing_key) will cause this module to fail. Note:
      OpenSSH versions prior to 7.2 do not support SHA-2 signature algorithms for RSA keys and OpenSSH
      versions prior to 7.3 do not support SHA-2 signature algorithms for certificates. See U(https://www.openssh.com/txt/release-8.2)
      for more information.'
  signing_key:
    type: path
    description: The path to the private openssh key that is used for signing the public key in order
      to generate the certificate. If the private key is on a PKCS#11 token (O(pkcs11_provider)), set
      this to the path to the public key instead. Required if O(state) is V(present).
  state:
    type: str
    default: present
    choices:
    - present
    - absent
    description: Whether the host or user certificate should exist or not, taking action if the state
      is different from what is stated.
  type:
    type: str
    choices:
    - host
    - user
    description: Whether the module should generate a host or a user certificate. Required if O(state)
      is V(present).
  unsafe_writes:
    type: bool
    default: false
    description: Influence when to use atomic operation to prevent data corruption or inconsistent reads
      from the target filesystem object. By default this module uses atomic operations to prevent data
      corruption or inconsistent reads from the target filesystem objects, but sometimes systems are configured
      or just broken in ways that prevent this. One example is docker mounted filesystem objects, which
      cannot be updated atomically from inside the container and can only be written in an unsafe manner.
      This option allows Ansible to fall back to unsafe methods of updating filesystem objects when atomic
      operations fail (however, it doesn't force Ansible to perform unsafe writes). IMPORTANT! Unsafe
      writes are subject to race conditions and can lead to data corruption.
  use_agent:
    type: bool
    default: false
    description: Should the ssh-keygen use a CA key residing in a ssh-agent.
  valid_at:
    type: str
    description: Check if the certificate is valid at a certain point in time. If it is not the certificate
      will be regenerated. Time will always be interpreted as UTC. Mainly to be used with relative timespec
      for O(valid_from) and / or O(valid_to). Note that if using relative time this module is NOT idempotent.
  valid_from:
    type: str
    description: 'The point in time the certificate is valid from. Time can be specified either as relative
      time or as absolute timestamp. Time will always be interpreted as UTC. Valid formats are: C([+-]timespec
      | YYYY-MM-DD | YYYY-MM-DDTHH:MM:SS | YYYY-MM-DD HH:MM:SS | always) where timespec can be an integer
      + C([w | d | h | m | s]) (for example V(+32w1d2h)). Note that if using relative time this module
      is NOT idempotent. The value V(always) is only supported for OpenSSH 7.7 and greater, however, the
      value V(1970-01-01T00:00:01) can be used with earlier versions as an equivalent expression. To ignore
      this value during comparison with an existing certificate set O(ignore_timestamps=true). Required
      if O(state) is V(present).'
  valid_to:
    type: str
    description: 'The point in time the certificate is valid to. Time can be specified either as relative
      time or as absolute timestamp. Time will always be interpreted as UTC. Valid formats are: C([+-]timespec
      | YYYY-MM-DD | YYYY-MM-DDTHH:MM:SS | YYYY-MM-DD HH:MM:SS | forever) where timespec can be an integer
      + C([w | d | h | m | s]) (for example V(+32w1d2h)). Note that if using relative time this module
      is NOT idempotent. To ignore this value during comparison with an existing certificate set O(ignore_timestamps=true).
      Required if O(state) is V(present).'
writes: true
runtime: starlark
source: translated
examples: "\n- name: Generate an OpenSSH user certificate that is valid forever and for all users\n  community.crypto.openssh_cert:\n\
  \    type: user\n    signing_key: /path/to/private_key\n    public_key: /path/to/public_key.pub\n  \
  \  path: /path/to/certificate\n    valid_from: always\n    valid_to: forever\n\n# Generate an OpenSSH\
  \ host certificate that is valid for 32 weeks from now and will be regenerated\n# if it is valid for\
  \ less than 2 weeks from the time the module is being run\n- name: Generate an OpenSSH host certificate\
  \ with valid_from, valid_to and valid_at parameters\n  community.crypto.openssh_cert:\n    type: host\n\
  \    signing_key: /path/to/private_key\n    public_key: /path/to/public_key.pub\n    path: /path/to/certificate\n\
  \    valid_from: +0s\n    valid_to: +32w\n    valid_at: +2w\n    ignore_timestamps: true\n\n- name:\
  \ Generate an OpenSSH host certificate that is valid forever and only for example.com and examplehost\n\
  \  community.crypto.openssh_cert:\n    type: host\n    signing_key: /path/to/private_key\n    public_key:\
  \ /path/to/public_key.pub\n    path: /path/to/certificate\n    valid_from: always\n    valid_to: forever\n\
  \    principals:\n        - example.com\n        - examplehost\n\n- name: Generate an OpenSSH host Certificate\
  \ that is valid from 21.1.2001 to 21.1.2019\n  community.crypto.openssh_cert:\n    type: host\n    signing_key:\
  \ /path/to/private_key\n    public_key: /path/to/public_key.pub\n    path: /path/to/certificate\n  \
  \  valid_from: \"2001-01-21\"\n    valid_to: \"2019-01-21\"\n\n- name: Generate an OpenSSH user Certificate\
  \ with clear and force-command option\n  community.crypto.openssh_cert:\n    type: user\n    signing_key:\
  \ /path/to/private_key\n    public_key: /path/to/public_key.pub\n    path: /path/to/certificate\n  \
  \  valid_from: always\n    valid_to: forever\n    options:\n        - \"clear\"\n        - \"force-command=/tmp/bla/foo\"\
  \n\n- name: Generate an OpenSSH user certificate using a PKCS#11 token\n  community.crypto.openssh_cert:\n\
  \    type: user\n    signing_key: /path/to/ca_public_key.pub\n    pkcs11_provider: libpkcs11.so\n  \
  \  public_key: /path/to/public_key.pub\n    path: /path/to/certificate\n    valid_from: always\n   \
  \ valid_to: forever\n\n"
