name: x509_crl
fqcn: community.crypto.x509_crl
collection: community.crypto
short_description: Generate Certificate Revocation Lists (CRLs)
description: This module allows one to (re)generate or update Certificate Revocation Lists (CRLs). Certificates
  on the revocation list can be either specified by serial number and (optionally) their issuer, or as
  a path to a certificate file in PEM format.
options:
  attributes:
    type: str
    aliases:
    - attr
    description: The attributes the resulting filesystem object should have. To get supported flags look
      at the man page for I(chattr) on the target system. This string should contain the attributes in
      the same order as the one displayed by I(lsattr). The C(=) operator is assumed as default, otherwise
      C(+) or C(-) operators need to be included in the string.
  backup:
    type: bool
    default: false
    description: Create a backup file including a timestamp so you can get the original CRL back if you
      overwrote it with a new one by accident.
  crl_mode:
    type: str
    choices:
    - generate
    - update
    description: Defines how to process entries of existing CRLs. If set to V(generate), makes sure that
      the CRL has the exact set of revoked certificates as specified in O(revoked_certificates). If set
      to V(update), makes sure that the CRL contains the revoked certificates from O(revoked_certificates),
      but can also contain other revoked certificates. If the CRL file already exists, all entries from
      the existing CRL will also be included in the new CRL. When using V(update), you might be interested
      in setting O(ignore_timestamps) to V(true). The default value is V(generate). This parameter was
      called O(mode) before community.crypto 2.13.0. It has been renamed to avoid a collision with the
      common O(mode) parameter for setting the CRL file's access mode.
  digest:
    type: str
    default: sha256
    description: Digest algorithm to be used when signing the CRL.
  force:
    type: bool
    default: false
    description: Should the CRL be forced to be regenerated.
  format:
    type: str
    default: pem
    choices:
    - pem
    - der
    description: Whether the CRL file should be in PEM or DER format. If an existing CRL file does match
      everything but O(format), it will be converted to the correct format instead of regenerated.
  group:
    type: str
    description: Name of the group that should own the filesystem object, as would be fed to I(chown).
      When left unspecified, it uses the current group of the current user unless you are root, in which
      case it can preserve the previous ownership.
  ignore_timestamps:
    type: bool
    default: false
    description: Whether the timestamps O(last_update), O(next_update) and O(revoked_certificates[].revocation_date)
      should be ignored for idempotency checks. The timestamp O(revoked_certificates[].invalidity_date)
      will never be ignored. Use this in combination with relative timestamps for these values to get
      idempotency.
  issuer:
    type: dict
    description: Key/value pairs that will be present in the issuer name field of the CRL. If you need
      to specify more than one value with the same key, use a list as value. If the order of the components
      is important, use O(issuer_ordered). One of O(issuer) and O(issuer_ordered) is required if O(state)
      is V(present). Mutually exclusive with O(issuer_ordered).
  issuer_ordered:
    type: list
    description: A list of dictionaries, where every dictionary must contain one key/value pair. This
      key/value pair will be present in the issuer name field of the CRL. If you want to specify more
      than one value with the same key in a row, you can use a list as value. One of O(issuer) and O(issuer_ordered)
      is required if O(state) is V(present). Mutually exclusive with O(issuer).
  last_update:
    type: str
    default: +0s
    description: The point in time from which this CRL can be trusted. Time can be specified either as
      relative time or as absolute timestamp. Time will always be interpreted as UTC. Valid format is
      C([+-]timespec | ASN.1 TIME) where timespec can be an integer + C([w | d | h | m | s]) (for example
      V(+32w1d2h)). Note that if using relative time this module is NOT idempotent, except when O(ignore_timestamps)
      is set to V(true).
  mode:
    type: str
    choices:
    - generate
    - update
    description: This parameter has been renamed to O(crl_mode). The old name O(mode) is now deprecated
      and will be removed in community.crypto 3.0.0. Replace usage of this parameter with O(crl_mode).
      Note that from community.crypto 3.0.0 on, O(mode) will be used for the CRL file's mode.
  name_encoding:
    type: str
    default: ignore
    choices:
    - ignore
    - idna
    - unicode
    description: How to encode names (DNS names, URIs, email addresses) in return values. V(ignore) will
      use the encoding returned by the backend. V(idna) will convert all labels of domain names to IDNA
      encoding. IDNA2008 will be preferred, and IDNA2003 will be used if IDNA2008 encoding fails. V(unicode)
      will convert all labels of domain names to Unicode. IDNA2008 will be preferred, and IDNA2003 will
      be used if IDNA2008 decoding fails. B(Note) that V(idna) and V(unicode) require the L(idna Python
      library,https://pypi.org/project/idna/) to be installed.
  next_update:
    type: str
    description: The absolute latest point in time by which this O(issuer) is expected to have issued
      another CRL. Many clients will treat a CRL as expired once O(next_update) occurs. Time can be specified
      either as relative time or as absolute timestamp. Time will always be interpreted as UTC. Valid
      format is C([+-]timespec | ASN.1 TIME) where timespec can be an integer + C([w | d | h | m | s])
      (for example V(+32w1d2h)). Note that if using relative time this module is NOT idempotent, except
      when O(ignore_timestamps) is set to V(true). Required if O(state) is V(present).
  owner:
    type: str
    description: Name of the user that should own the filesystem object, as would be fed to I(chown).
      When left unspecified, it uses the current user unless you are root, in which case it can preserve
      the previous ownership. Specifying a numeric username will be assumed to be a user ID and not a
      username. Avoid numeric usernames to avoid this confusion.
  path:
    type: path
    required: true
    description: Remote absolute path where the generated CRL file should be created or is already located.
  privatekey_content:
    type: str
    description: The content of the CA's private key to use when signing the CRL. Either O(privatekey_path)
      or O(privatekey_content) must be specified if O(state) is V(present), but not both.
  privatekey_passphrase:
    type: str
    description: The passphrase for the O(privatekey_path). This is required if the private key is password
      protected.
  privatekey_path:
    type: path
    description: Path to the CA's private key to use when signing the CRL. Either O(privatekey_path) or
      O(privatekey_content) must be specified if O(state) is V(present), but not both.
  return_content:
    type: bool
    default: false
    description: If set to V(true), will return the (current or generated) CRL's content as RV(crl).
  revoked_certificates:
    type: list
    description: List of certificates to be revoked. Required if O(state) is V(present).
  selevel:
    type: str
    description: The level part of the SELinux filesystem object context. This is the MLS/MCS attribute,
      sometimes known as the C(range). When set to V(_default), it will use the C(level) portion of the
      policy if available.
  serole:
    type: str
    description: The role part of the SELinux filesystem object context. When set to V(_default), it will
      use the C(role) portion of the policy if available.
  setype:
    type: str
    description: The type part of the SELinux filesystem object context. When set to V(_default), it will
      use the C(type) portion of the policy if available.
  seuser:
    type: str
    description: The user part of the SELinux filesystem object context. By default it uses the V(system)
      policy, where applicable. When set to V(_default), it will use the C(user) portion of the policy
      if available.
  state:
    type: str
    default: present
    choices:
    - absent
    - present
    description: Whether the CRL file should exist or not, taking action if the state is different from
      what is stated.
  unsafe_writes:
    type: bool
    default: false
    description: Influence when to use atomic operation to prevent data corruption or inconsistent reads
      from the target filesystem object. By default this module uses atomic operations to prevent data
      corruption or inconsistent reads from the target filesystem objects, but sometimes systems are configured
      or just broken in ways that prevent this. One example is docker mounted filesystem objects, which
      cannot be updated atomically from inside the container and can only be written in an unsafe manner.
      This option allows Ansible to fall back to unsafe methods of updating filesystem objects when atomic
      operations fail (however, it doesn't force Ansible to perform unsafe writes). IMPORTANT! Unsafe
      writes are subject to race conditions and can lead to data corruption.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Generate a CRL\n  community.crypto.x509_crl:\n    path: /etc/ssl/my-ca.crl\n    privatekey_path:\
  \ /etc/ssl/private/my-ca.pem\n    issuer:\n      CN: My CA\n    last_update: \"+0s\"\n    next_update:\
  \ \"+7d\"\n    revoked_certificates:\n      - serial_number: 1234\n        revocation_date: 20190331202428Z\n\
  \        issuer:\n          CN: My CA\n      - serial_number: 2345\n        revocation_date: 20191013152910Z\n\
  \        reason: affiliation_changed\n        invalidity_date: 20191001000000Z\n      - path: /etc/ssl/crt/revoked-cert.pem\n\
  \        revocation_date: 20191010010203Z\n"
