package server

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/mutkluge/agentic-mcp/internal/audit"
	"github.com/mutkluge/agentic-mcp/internal/authz"
	"github.com/mutkluge/agentic-mcp/internal/upload"
)

// maxMCPUploadBytes bounds the upload_file MCP tool independently of
// config.MaxUploadSize (which bounds the REST path instead) — see
// docs/plan.md's "File upload (staging)" for why: an MCP tool call driven by
// an LLM client has its arguments generated by the model itself, token by
// token, so embedding file content there only makes sense for content an AI
// would plausibly compose (a small config snippet), never a multi-hundred-
// megabyte package.
const maxMCPUploadBytes = 64 * 1024

// UploadFileInput is the input schema for the upload_file MCP tool.
type UploadFileInput struct {
	Name          string `json:"name" jsonschema:"destination filename only (no path) inside the staging directory"`
	ContentBase64 string `json:"content_base64" jsonschema:"file content, base64-encoded; capped at 64KiB — for larger files use the PUT /api/v1/upload REST endpoint instead"`
}

// UploadFileOutput is the output schema for the upload_file MCP tool.
type UploadFileOutput struct {
	Path         string `json:"path"`
	BytesWritten int64  `json:"bytes_written"`
}

// RegisterUploadFile adds the upload_file MCP tool: stages a small,
// base64-encoded file into config.UploadsDir. Only registered when write is
// true (it mutates the filesystem, same write gate as every other write
// tool). acl and al may be nil (see RegisterModules).
func RegisterUploadFile(s *mcp.Server, uploadsDir string, write bool, acl *authz.ACL, al *audit.Logger) {
	if !write {
		return
	}
	mcp.AddTool(s, &mcp.Tool{
		Name: "upload_file",
		Description: "" +
			"Stage a small file (config snippet, short script — up to 64KiB) into this agent's " +
			"upload staging directory, so it can then be placed at its real destination via the " +
			"copy module (src: the returned path, dest: the target path, with owner/group/mode). " +
			"This tool only stages the transport; it never writes to an arbitrary destination " +
			"path itself. For files larger than 64KiB (packages, binaries), use the REST endpoint " +
			"PUT /api/v1/upload instead — a plain HTTP body upload meant for a script or the " +
			"future Fleet Commander to call directly, not for an AI to generate inline.\n\n" +
			"Cross-tool equivalents: analogous to how ansible.builtin.copy's src file is expected " +
			"to already exist on the control node before the module runs — this tool is what gets " +
			"it there in the first place when there is no separate control-node filesystem, " +
			"comparable to Chef's cookbook_file/remote_file staging, Puppet's source => " +
			"puppet:/// file server mechanism, or Salt's cp.get_file / fileserver.",
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"name":           map[string]any{"type": "string", "description": "Destination filename only (no path)."},
				"content_base64": map[string]any{"type": "string", "description": "File content, base64-encoded. Capped at 64KiB."},
			},
			"required": []string{"name", "content_base64"},
		},
	}, func(ctx context.Context, req *mcp.CallToolRequest, in UploadFileInput) (*mcp.CallToolResult, UploadFileOutput, error) {
		start := time.Now()
		params := map[string]any{"name": in.Name}
		if err := checkACL(ctx, acl, "upload_file", true); err != nil {
			al.LogCall(identityLabel(authz.TokenIdentity), "upload_file", true, false, params, start, err)
			return nil, UploadFileOutput{}, err
		}

		data, err := base64.StdEncoding.DecodeString(in.ContentBase64)
		if err != nil {
			err = fmt.Errorf("content_base64: %w", err)
			al.LogCall(identityLabel(authz.TokenIdentity), "upload_file", true, false, params, start, err)
			return nil, UploadFileOutput{}, err
		}

		n, err := upload.WriteStaged(uploadsDir, in.Name, bytes.NewReader(data), maxMCPUploadBytes)
		al.LogCall(identityLabel(authz.TokenIdentity), "upload_file", true, err == nil, params, start, err)
		if err != nil {
			return nil, UploadFileOutput{}, err
		}
		return nil, UploadFileOutput{Path: uploadsDir + "/" + in.Name, BytesWritten: n}, nil
	})
}

// handleUpload serves PUT /api/v1/upload?name=<filename>: the raw-body,
// no-base64 large-file path (see docs/plan.md's "File upload (staging)").
// The entire request body is streamed directly into the staging directory.
func handleUpload(w http.ResponseWriter, r *http.Request, cfg RESTConfig) {
	start := time.Now()
	identity := identityLabel(identityFromContext(r.Context()))
	name := r.URL.Query().Get("name")
	params := map[string]any{"name": name}

	if !cfg.Write {
		writeError(w, http.StatusForbidden, fmt.Errorf("upload_file is disabled (write=false)"))
		return
	}
	if !authorizeTool(w, r, cfg, "upload_file", true) {
		return
	}

	if r.ContentLength > 0 && r.ContentLength > cfg.MaxUploadSize {
		err := fmt.Errorf("upload exceeds max_upload_size (%d bytes)", cfg.MaxUploadSize)
		cfg.Audit.LogCall(identity, "upload_file", true, false, params, start, err)
		writeError(w, http.StatusRequestEntityTooLarge, err)
		return
	}

	n, err := upload.WriteStaged(cfg.UploadsDir, name, r.Body, cfg.MaxUploadSize)
	cfg.Audit.LogCall(identity, "upload_file", true, err == nil, params, start, err)
	if err != nil {
		writeError(w, http.StatusUnprocessableEntity, err)
		return
	}
	writeJSON(w, http.StatusOK, UploadFileOutput{Path: cfg.UploadsDir + "/" + name, BytesWritten: n})
}
