def main(ctx, params):
    sql_block = [
        "set heading off",
        "set feedback off",
        "set pagesize 0",
        "set trimspool on",
        "set linesize 32767",
        "set verify off",
        "set echo off",
        "SELECT",
        "  B1.SID,",
        "  B1.SERIAL#,",
        "  B1.MACHINE,",
        "  B1.PROGRAM,",
        "  B1.PROCESS,",
        "  B1.OSUSER,",
        "  B1.USERNAME,",
        "  (SYSDATE - B1.LOGON_TIME) * 86400,",
        "  B1.BLOCK,",
        "  B1.BLOCK_INSTANCE,",
        "  B1.BLOCK_SID,",
        "  B1.BLOCK_SERIAL#,",
        "  B2.MACHINE,",
        "  B2.PROGRAM,",
        "  B2.PROCESS,",
        "  B2.OSUSER,",
        "  B2.USERNAME,",
        "  O.OWNER,",
        "  O.OBJECT_NAME",
        "FROM V$LOCK B1, V$LOCK B2, DBA_OBJECTS O",
        "WHERE B1.BLOCK > 0 AND B2.REQUEST > 0",
        "  AND B1.SID = B2.BLOCK_SID AND B1.ID1 = B2.ID1 AND B1.ID2 = B2.ID2",
        "  AND B1.REQUEST = 0 AND B2.BLOCK = 0",
        "  AND O.OBJECT_ID = B1.ID1",
        ";",
        "exit",
    ]
    sql_text = "\n".join(sql_block)
    return {"changed": False, "msg": "oracle_locks check module loaded", "data": {"sql": sql_text}}