name: uniserv
fqcn: checkmk.uniserv
collection: checkmk
short_description: ''
description: Checkmk active check 'uniserv', translated to a read-only on-host Starlark
  check module.
options:
  host:
    type: string
    description: host (from the check's parameters).
  port:
    type: string
    description: port (from the check's parameters).
  service:
    type: string
    description: service (from the check's parameters).
  check_version:
    type: bool
    default: 'False'
    description: check_version (from the check's parameters).
  check_address:
    type: list
    description: check_address (from the check's parameters).
writes: false
runtime: starlark
source: translated
kind: check
execution: local
prompt_version: c21f0f5a7229
