name: current_container_facts
fqcn: community.docker.current_container_facts
collection: community.docker
short_description: Return facts about whether the module runs in a container
description: Return facts about whether the module runs in a Docker or podman container. This module attempts
  a best-effort detection. There might be special cases where it does not work; if you encounter one,
  L(please file an issue, https://github.com/ansible-collections/community.docker/issues/new?assignees=&labels=&template=bug_report.md).
options: {}
writes: false
runtime: starlark
source: translated
examples: "\n- name: Get facts on current container\n  community.docker.current_container_facts:\n\n-\
  \ name: Print information on current container when running in a container\n  ansible.builtin.debug:\n\
  \    msg: \"Container ID is {{ ansible_module_container_id }}\"\n  when: ansible_module_running_in_container\n"
