name: docker_swarm
fqcn: community.docker.docker_swarm
collection: community.docker
short_description: Manage Swarm cluster
description: Create a new Swarm cluster. Add/Remove nodes or managers to an existing cluster.
options:
  advertise_addr:
    type: str
    description: Externally reachable address advertised to other nodes. This can either be an address/port
      combination in the form V(192.168.1.1:4567), or an interface followed by a port number, like V(eth0:4567).
      If the port number is omitted, the port number from the listen address is used. If O(advertise_addr)
      is not specified, it will be automatically detected when possible. Only used when swarm is initialised
      or joined. Because of this it's not considered for idempotency checking.
  api_version:
    type: str
    default: auto
    aliases:
    - docker_api_version
    description: The version of the Docker API running on the Docker Host. Defaults to the latest version
      of the API supported by Docker SDK for Python and the docker daemon. If the value is not specified
      in the task, the value of environment variable E(DOCKER_API_VERSION) will be used instead. If the
      environment variable is not set, the default value will be used.
  autolock_managers:
    type: bool
    description: If set, generate a key and use it to lock data stored on the managers. Docker default
      value is V(false). M(community.docker.docker_swarm_info) can be used to retrieve the unlock key.
  ca_force_rotate:
    type: int
    description: An integer whose purpose is to force swarm to generate a new signing CA certificate and
      key, if none have been specified. Docker default value is V(0). Requires API version >= 1.30.
  ca_path:
    type: path
    aliases:
    - ca_cert
    - tls_ca_cert
    - cacert_path
    description: Use a CA certificate when performing server verification by providing the path to a CA
      certificate file. If the value is not specified in the task and the environment variable E(DOCKER_CERT_PATH)
      is set, the file C(ca.pem) from the directory specified in the environment variable E(DOCKER_CERT_PATH)
      will be used. This option was called O(ca_cert) and got renamed to O(ca_path) in community.docker
      3.6.0. The old name has been added as an alias and can still be used.
  client_cert:
    type: path
    aliases:
    - tls_client_cert
    - cert_path
    description: Path to the client's TLS certificate file. If the value is not specified in the task
      and the environment variable E(DOCKER_CERT_PATH) is set, the file C(cert.pem) from the directory
      specified in the environment variable E(DOCKER_CERT_PATH) will be used.
  client_key:
    type: path
    aliases:
    - tls_client_key
    - key_path
    description: Path to the client's TLS key file. If the value is not specified in the task and the
      environment variable E(DOCKER_CERT_PATH) is set, the file C(key.pem) from the directory specified
      in the environment variable E(DOCKER_CERT_PATH) will be used.
  data_path_addr:
    type: str
    description: Address or interface to use for data path traffic. This can either be an address in the
      form V(192.168.1.1), or an interface, like V(eth0). Only used when swarm is initialised or joined.
      Because of this it is not considered for idempotency checking. Requires API version >= 1.30.
  data_path_port:
    type: int
    description: Port to use for data path traffic. This needs to be a port number like V(9789). Only
      used when swarm is initialised. Because of this it is not considered for idempotency checking. Requires
      API version >= 1.40.
  debug:
    type: bool
    default: false
    description: Debug mode
  default_addr_pool:
    type: list
    description: Default address pool in CIDR format. Only used when swarm is initialised. Because of
      this it's not considered for idempotency checking. Requires API version >= 1.39.
  dispatcher_heartbeat_period:
    type: int
    description: The delay (in nanoseconds) for an agent to send a heartbeat to the dispatcher. Docker
      default value is 5 seconds, which corresponds to a value of V(5000000000).
  docker_host:
    type: str
    default: unix:///var/run/docker.sock
    aliases:
    - docker_url
    description: The URL or Unix socket path used to connect to the Docker API. To connect to a remote
      host, provide the TCP connection string. For example, V(tcp://192.0.2.23:2376). If TLS is used to
      encrypt the connection, the module will automatically replace C(tcp) in the connection URL with
      C(https). If the value is not specified in the task, the value of environment variable E(DOCKER_HOST)
      will be used instead. If the environment variable is not set, the default value will be used.
  election_tick:
    type: int
    description: Amount of ticks (in seconds) needed without a leader to trigger a new election. Docker
      default value is V(10) seconds.
  force:
    type: bool
    default: false
    description: Use with state V(present) to force creating a new Swarm, even if already part of one.
      Use with state V(absent) to Leave the swarm even if this node is a manager.
  heartbeat_tick:
    type: int
    description: Amount of ticks (in seconds) between each heartbeat. Docker default value is V(1) seconds.
  join_token:
    type: str
    description: Swarm token used to join a swarm cluster. Used with O(state=join). If this value is specified,
      the corresponding value in the return values will be censored by Ansible. This is a side-effect
      of this value not being logged.
  keep_old_snapshots:
    type: int
    description: Number of snapshots to keep beyond the current snapshot. Docker default value is V(0).
  labels:
    type: dict
    description: User-defined key/value metadata. Label operations in this module apply to the docker
      swarm cluster. Use M(community.docker.docker_node) module to add/modify/remove swarm node labels.
      Requires API version >= 1.32.
  listen_addr:
    type: str
    default: 0.0.0.0:2377
    description: Listen address used for inter-manager communication. This can either be an address/port
      combination in the form V(192.168.1.1:4567), or an interface followed by a port number, like V(eth0:4567).
      If the port number is omitted, the default swarm listening port is used. Only used when swarm is
      initialised or joined. Because of this it's not considered for idempotency checking.
  log_entries_for_slow_followers:
    type: int
    description: Number of log entries to keep around to sync up slow followers after a snapshot is created.
  name:
    type: str
    description: The name of the swarm.
  node_cert_expiry:
    type: int
    description: Automatic expiry for nodes certificates, given in nanoseconds. Docker default value is
      90 days, which corresponds to a value of V(7776000000000000).
  node_id:
    type: str
    description: Swarm id of the node to remove. Used with O(state=remove).
  remote_addrs:
    type: list
    description: Remote address of one or more manager nodes of an existing Swarm to connect to. Used
      with O(state=join).
  rotate_manager_token:
    type: bool
    default: false
    description: Rotate the manager join token.
  rotate_worker_token:
    type: bool
    default: false
    description: Rotate the worker join token.
  signing_ca_cert:
    type: str
    description: The desired signing CA certificate for all swarm node TLS leaf certificates, in PEM format.
      This must not be a path to a certificate, but the contents of the certificate. Requires API version
      >= 1.30.
  signing_ca_key:
    type: str
    description: The desired signing CA key for all swarm node TLS leaf certificates, in PEM format. This
      must not be a path to a key, but the contents of the key. Requires API version >= 1.30.
  snapshot_interval:
    type: int
    description: Number of logs entries between snapshot. Docker default value is V(10000).
  ssl_version:
    type: str
    description: Provide a valid SSL version number. Default value determined by L(SSL Python module,
      https://docs.python.org/3/library/ssl.html). If the value is not specified in the task, the value
      of environment variable E(DOCKER_SSL_VERSION) will be used instead. B(Note:) this option is no longer
      supported for Docker SDK for Python 7.0.0+. Specifying it with Docker SDK for Python 7.0.0 or newer
      will lead to an error.
  state:
    type: str
    default: present
    choices:
    - present
    - join
    - absent
    - remove
    description: Set to V(present), to create/update a new cluster. Set to V(join), to join an existing
      cluster. Set to V(absent), to leave an existing cluster. Set to V(remove), to remove an absent node
      from the cluster. Note that removing requires Docker SDK for Python >= 2.4.0. M(community.docker.docker_node)
      can be used to demote a manager before removal.
  subnet_size:
    type: int
    description: Default address pool subnet mask length. Only used when swarm is initialised. Because
      of this it's not considered for idempotency checking. Requires API version >= 1.39.
  task_history_retention_limit:
    type: int
    description: Maximum number of tasks history stored. Docker default value is V(5).
  timeout:
    type: int
    default: 60
    description: The maximum amount of time in seconds to wait on a response from the API. If the value
      is not specified in the task, the value of environment variable E(DOCKER_TIMEOUT) will be used instead.
      If the environment variable is not set, the default value will be used.
  tls:
    type: bool
    default: false
    description: Secure the connection to the API by using TLS without verifying the authenticity of the
      Docker host server. Note that if O(validate_certs) is set to V(true) as well, it will take precedence.
      If the value is not specified in the task, the value of environment variable E(DOCKER_TLS) will
      be used instead. If the environment variable is not set, the default value will be used.
  tls_hostname:
    type: str
    description: When verifying the authenticity of the Docker Host server, provide the expected name
      of the server. If the value is not specified in the task, the value of environment variable E(DOCKER_TLS_HOSTNAME)
      will be used instead. If the environment variable is not set, the default value will be used. Note
      that this option had a default value V(localhost) in older versions. It was removed in community.docker
      3.0.0. B(Note:) this option is no longer supported for Docker SDK for Python 7.0.0+. Specifying
      it with Docker SDK for Python 7.0.0 or newer will lead to an error.
  use_ssh_client:
    type: bool
    default: false
    description: For SSH transports, use the C(ssh) CLI tool instead of paramiko. Requires Docker SDK
      for Python 4.4.0 or newer.
  validate_certs:
    type: bool
    default: false
    aliases:
    - tls_verify
    description: Secure the connection to the API by using TLS and verifying the authenticity of the Docker
      host server. If the value is not specified in the task, the value of environment variable E(DOCKER_TLS_VERIFY)
      will be used instead. If the environment variable is not set, the default value will be used.
writes: true
runtime: starlark
source: translated
examples: "\n\n- name: Init a new swarm with default parameters\n  community.docker.docker_swarm:\n  \
  \  state: present\n\n- name: Update swarm configuration\n  community.docker.docker_swarm:\n    state:\
  \ present\n    election_tick: 5\n\n- name: Add nodes\n  community.docker.docker_swarm:\n    state: join\n\
  \    advertise_addr: 192.168.1.2\n    join_token: SWMTKN-1--xxxxx\n    remote_addrs: [ '192.168.1.1:2377'\
  \ ]\n\n- name: Leave swarm for a node\n  community.docker.docker_swarm:\n    state: absent\n\n- name:\
  \ Remove a swarm manager\n  community.docker.docker_swarm:\n    state: absent\n    force: true\n\n-\
  \ name: Remove node from swarm\n  community.docker.docker_swarm:\n    state: remove\n    node_id: mynode\n\
  \n- name: Init a new swarm with different data path interface\n  community.docker.docker_swarm:\n  \
  \  state: present\n    advertise_addr: eth0\n    data_path_addr: ens10\n\n- name: Init a new swarm with\
  \ a different data path port\n  community.docker.docker_swarm:\n    state: present\n    data_path_port:\
  \ 9789\n"
