name: firewalld
fqcn: posix.firewalld
collection: posix
short_description: Manage arbitrary ports/services with firewalld
description: This module allows for addition or deletion of services and ports (either TCP or UDP) in
  either running or permanent firewalld rules.
options:
  icmp_block:
    type: str
    description: The ICMP block you would like to add/remove to/from a zone in firewalld.
  icmp_block_inversion:
    type: str
    description: Enable/Disable inversion of ICMP blocks for a zone in firewalld.
  immediate:
    type: bool
    default: false
    description: Should this configuration be applied immediately, if set as permanent.
  interface:
    type: str
    description: The interface you would like to add/remove to/from a zone in firewalld.
  masquerade:
    type: str
    description: The masquerade setting you would like to enable/disable to/from zones within firewalld.
  offline:
    type: bool
    description: Whether to run this module even when firewalld is offline.
  permanent:
    type: bool
    description: Should this configuration be in the running firewalld configuration or persist across
      reboots. As of Ansible 2.3, permanent operations can operate on firewalld configs when it is not
      running (requires firewalld >= 0.3.9). Note that if this is C(false), immediate is assumed C(true).
  port:
    type: str
    description: Name of a port or port range to add/remove to/from firewalld. Must be in the form PORT/PROTOCOL
      or PORT-PORT/PROTOCOL for port ranges.
  port_forward:
    type: list
    description: Port and protocol to forward using firewalld.
  protocol:
    type: str
    description: Name of a protocol to add/remove to/from firewalld.
  rich_rule:
    type: str
    description: Rich rule to add/remove to/from firewalld. See L(Syntax for firewalld rich language rules,https://firewalld.org/documentation/man-pages/firewalld.richlanguage.html).
  service:
    type: str
    description: Name of a service to add/remove to/from firewalld. The service must be listed in output
      of firewall-cmd --get-services.
  source:
    type: str
    description: The source/network you would like to add/remove to/from firewalld.
  state:
    type: str
    required: true
    choices:
    - absent
    - disabled
    - enabled
    - present
    description: 'Enable or disable a setting. For ports: Should this port accept (enabled) or reject
      (disabled) connections. The states C(present) and C(absent) can only be used in zone level operations
      (i.e. when no other parameters but zone and state are set).'
  target:
    type: str
    choices:
    - default
    - ACCEPT
    - DROP
    - '%%REJECT%%'
    description: firewalld Zone target If state is set to C(absent), this will reset the target to default
  timeout:
    type: int
    default: 0
    description: The amount of time in seconds the rule should be in effect for when non-permanent.
  zone:
    type: str
    description: The firewalld zone to add/remove to/from. Note that the default zone can be configured
      per system but C(public) is default from upstream. Available choices can be extended based on per-system
      configs, listed here are "out of the box" defaults. Possible values include C(block), C(dmz), C(drop),
      C(external), C(home), C(internal), C(public), C(trusted), C(work).
writes: true
runtime: starlark
source: translated
examples: "\n- name: permit traffic in default zone for https service\n  posix.firewalld:\n  \
  \  service: https\n    permanent: true\n    state: enabled\n\n- name: permit ospf traffic\n  posix.firewalld:\n\
  \    protocol: ospf\n    permanent: true\n    state: enabled\n\n- name: do not permit traffic in default\
  \ zone on port 8081/tcp\n  posix.firewalld:\n    port: 8081/tcp\n    permanent: true\n    state:\
  \ disabled\n\n- posix.firewalld:\n    port: 161-162/udp\n    permanent: true\n    state: enabled\n\
  \n- posix.firewalld:\n    zone: dmz\n    service: http\n    permanent: true\n    state: enabled\n\
  \n- posix.firewalld:\n    rich_rule: rule service name=\"ftp\" audit limit value=\"1/m\" accept\n\
  \    permanent: true\n    state: enabled\n\n- posix.firewalld:\n    source: 192.0.2.0/24\n \
  \   zone: internal\n    state: enabled\n\n- posix.firewalld:\n    zone: trusted\n    interface:\
  \ eth2\n    permanent: true\n    state: enabled\n\n- posix.firewalld:\n    masquerade: true\n\
  \    state: enabled\n    permanent: true\n    zone: dmz\n\n- posix.firewalld:\n    zone: custom\n\
  \    state: present\n    permanent: true\n\n- posix.firewalld:\n    zone: drop\n    state: enabled\n\
  \    permanent: true\n    icmp_block_inversion: true\n\n- posix.firewalld:\n    zone: drop\n\
  \    state: enabled\n    permanent: true\n    icmp_block: echo-request\n\n- posix.firewalld:\n\
  \    zone: internal\n    state: present\n    permanent: true\n    target: ACCEPT\n\n- name: Redirect\
  \ port 443 to 8443 with Rich Rule\n  posix.firewalld:\n    rich_rule: rule family=ipv4 forward-port\
  \ port=443 protocol=tcp to-port=8443\n    zone: public\n    permanent: true\n    immediate: true\n \
  \   state: enabled\n"
