"""monitoring core

Revision ID: 50e78cc78c2a
Revises: f095218bdf99
Create Date: 2026-07-05 17:30:40.957397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50e78cc78c2a'
down_revision: Union[str, Sequence[str], None] = 'f095218bdf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('comparison', sa.String(), nullable=False),
    sa.Column('warn_threshold', sa.Float(), nullable=True),
    sa.Column('crit_threshold', sa.Float(), nullable=True),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_value', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope_type = 'global' AND scope_value IS NULL) OR (scope_type IN ('group', 'host') AND scope_value IS NOT NULL)", name='ck_check_rules_scope_value_matches_type'),
    sa.CheckConstraint("comparison IN ('gt', 'lt', 'ge', 'le', 'eq', 'ne')", name='ck_check_rules_comparison'),
    sa.CheckConstraint("scope_type IN ('global', 'group', 'host')", name='ck_check_rules_scope_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downtimes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_downtimes_agent_window', 'downtimes', ['agent_id', 'starts_at', 'ends_at'], unique=False)
    op.create_table('service_state_history',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('time', 'agent_id', 'service_name')
    )
    op.create_index('idx_service_state_history_agent_service_time', 'service_state_history', ['agent_id', 'service_name', 'time'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('last_state_change', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('ack_comment', sa.Text(), nullable=True),
    sa.Column('ack_by', sa.String(), nullable=True),
    sa.CheckConstraint("state IN ('OK', 'WARN', 'CRIT', 'UNKNOWN')", name='ck_services_state'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['check_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='uq_services_agent_name')
    )
    op.create_index('idx_services_agent', 'services', ['agent_id'], unique=False)
    # server_default (not just the model's Python-side default=list) so
    # existing agent rows get a real value instead of violating NOT NULL.
    op.add_column(
        'agents', sa.Column('groups', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False)
    )

    # service_state_history is a hypertable — the Zustands-Zeitleiste
    # counterpart to metrics/connection_events, same retention pattern.
    op.execute("SELECT create_hypertable('service_state_history', 'time')")
    op.execute("SELECT add_retention_policy('service_state_history', INTERVAL '30 days')")

    # Autogenerate also proposed dropping idx_chunk_embeddings_hnsw_cosine,
    # connection_events_time_idx, metrics_time_idx, and
    # idx_plan_embeddings_hnsw_cosine — deliberately NOT applied. These are
    # either TimescaleDB's own auto-created indexes (invisible to
    # SQLAlchemy's model introspection, the same false positive already
    # documented in 8ddf50da59f5_agent_poll_cursors.py) or pgvector's HNSW
    # indexes (created via raw SQL in their own migrations, likewise
    # invisible to autogenerate's model-based diffing).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'groups')
    op.drop_index('idx_services_agent', table_name='services')
    op.drop_table('services')
    op.drop_index('idx_service_state_history_agent_service_time', table_name='service_state_history')
    op.drop_table('service_state_history')
    op.drop_index('idx_downtimes_agent_window', table_name='downtimes')
    op.drop_table('downtimes')
    op.drop_table('check_rules')
    # ### end Alembic commands ###
