"""initial schema

Revision ID: f17d664762b0
Revises: 
Create Date: 2026-07-04 14:17:10.297484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f17d664762b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('enrollment_state', sa.String(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("enrollment_state IN ('pending', 'enrolled', 'revoked')", name='ck_agents_enrollment_state'),
    sa.CheckConstraint("mode IN ('standalone', 'satellite', 'proxy')", name='ck_agents_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('bossman_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'operator')", name='ck_bossman_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('connection_events',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('src_agent_id', sa.UUID(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('comm', sa.String(), nullable=True),
    sa.Column('src_addr', postgresql.INET(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_addr', postgresql.INET(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('old_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['src_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('time', 'src_agent_id')
    )
    op.create_index('idx_conn_events_src_agent_time', 'connection_events', ['src_agent_id', 'time'], unique=False)

    # connection_events is a hypertable: raw, high-volume history pulled
    # from each agent's GET /api/v1/net/connections/dump. Not expressible
    # via SQLAlchemy DDL, hence the raw SQL here.
    op.execute("SELECT create_hypertable('connection_events', 'time')")
    op.execute("SELECT add_retention_policy('connection_events', INTERVAL '30 days')")

    op.create_table('host_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('src_agent_id', sa.UUID(), nullable=False),
    sa.Column('src_comm', sa.String(), nullable=False),
    sa.Column('dst_addr', postgresql.INET(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('dst_agent_id', sa.UUID(), nullable=True),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms_p50', sa.Float(), nullable=True),
    sa.Column('latency_ms_p99', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dst_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['src_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_agent_id', 'src_comm', 'dst_addr', 'dst_port', name='uq_host_edges_identity')
    )
    op.create_index('idx_host_edges_dst_agent', 'host_edges', ['dst_agent_id'], unique=False)
    op.create_index('idx_host_edges_last_seen', 'host_edges', ['last_seen_at'], unique=False)
    op.create_table('metrics',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('time', 'agent_id', 'metric')
    )
    op.create_index('idx_metrics_agent_metric_time', 'metrics', ['agent_id', 'metric', 'time'], unique=False)

    # metrics is a hypertable — the direct RRD replacement (see
    # docs/plan.md). metrics_hourly is a continuous aggregate: the rollup
    # CheckMK does with fixed-resolution RRAs, computed incrementally by
    # TimescaleDB's background worker instead of a cron job walking raw rows.
    op.execute("SELECT create_hypertable('metrics', 'time')")
    # WITH NO DATA: the initial materialization TimescaleDB would otherwise
    # do immediately requires running outside a transaction block (it hits
    # "CREATE MATERIALIZED VIEW ... WITH DATA cannot run inside a
    # transaction block", a real error encountered while writing this
    # migration — Alembic wraps each migration in a transaction by
    # default). Skipping it here is harmless: the continuous aggregate
    # policy below refreshes it on its own schedule regardless.
    op.execute("""
        CREATE MATERIALIZED VIEW metrics_hourly
        WITH (timescaledb.continuous) AS
        SELECT time_bucket('1 hour', time) AS bucket,
               agent_id, metric, labels,
               avg(value) AS avg_value, max(value) AS max_value, min(value) AS min_value
        FROM metrics
        GROUP BY bucket, agent_id, metric, labels
        WITH NO DATA
    """)
    op.execute("""
        SELECT add_continuous_aggregate_policy('metrics_hourly',
            start_offset => INTERVAL '3 hours',
            end_offset => INTERVAL '1 hour',
            schedule_interval => INTERVAL '1 hour')
    """)
    op.execute("SELECT add_retention_policy('metrics', INTERVAL '14 days')")

    op.create_table('plan_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('plan_version', sa.String(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'aborted')", name='ck_plan_runs_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_run_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_run_id'], ['plan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_run_steps_run', 'plan_run_steps', ['plan_run_id', 'step_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plan_run_steps_run', table_name='plan_run_steps')
    op.drop_table('plan_run_steps')
    op.drop_table('plan_runs')

    # metrics_hourly depends on metrics — must go first, or DROP TABLE
    # metrics fails with a dependent-object error.
    op.execute("DROP MATERIALIZED VIEW IF EXISTS metrics_hourly")
    op.drop_index('idx_metrics_agent_metric_time', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('idx_host_edges_last_seen', table_name='host_edges')
    op.drop_index('idx_host_edges_dst_agent', table_name='host_edges')
    op.drop_table('host_edges')
    op.drop_index('idx_conn_events_src_agent_time', table_name='connection_events')
    op.drop_table('connection_events')
    op.drop_table('bossman_users')
    op.drop_table('api_tokens')
    op.drop_table('agents')
    # ### end Alembic commands ###
