name: dnf
fqcn: ansible.builtin.dnf
collection: ansible.builtin
short_description: Manages packages with the I(dnf) package manager
description: Installs, upgrade, removes, and lists packages and groups with the I(dnf) package manager.
options:
  allow_downgrade:
    type: bool
    default: 'no'
    description: Specify if the named package and version is allowed to downgrade a maybe already installed
      higher version of that package. Note that setting allow_downgrade=True can make this module behave
      in a non-idempotent way. The task could end up with a set of packages that does not match the complete
      list of specified packages to install (because dependencies between the downgraded package and others
      can cause changes to the packages which were in the earlier transaction).
  allowerasing:
    type: bool
    default: 'no'
    description: If V(true) it allows  erasing  of  installed  packages to resolve dependencies.
  autoremove:
    type: bool
    default: 'no'
    description: If V(true), removes all "leaf" packages from the system that were originally installed
      as dependencies of user-installed packages but which are no longer required by any such package.
      Should be used alone or when O(state) is V(absent)
  bugfix:
    type: bool
    default: 'no'
    description: If set to V(true), and O(state=latest) then only installs updates that have been marked
      bugfix related. Note that, similar to C(dnf upgrade-minimal), this filter applies to dependencies
      as well.
  cacheonly:
    type: bool
    default: 'no'
    description: Tells dnf to run entirely from system cache; does not download or update metadata.
  conf_file:
    type: str
    description: The remote dnf configuration file to use for the transaction.
  disable_excludes:
    type: str
    description: Disable the excludes defined in DNF config files. If set to V(all), disables all excludes.
      If set to V(main), disable excludes defined in [main] in dnf.conf. If set to V(repoid), disable
      excludes defined for given repo id.
  disable_gpg_check:
    type: bool
    default: 'no'
    description: Whether to disable the GPG checking of signatures of packages being installed. Has an
      effect only if O(state) is V(present) or V(latest). This setting affects packages installed from
      a repository as well as "local" packages installed from the filesystem or a URL.
  disable_plugin:
    type: list
    default: []
    description: I(Plugin) name to disable for the install/update operation. The disabled plugins will
      not persist beyond the transaction.
  disablerepo:
    type: list
    default: []
    description: I(Repoid) of repositories to disable for the install/update operation. These repos will
      not persist beyond the transaction. When specifying multiple repos, separate them with a ",".
  download_dir:
    type: str
    description: Specifies an alternate directory to store packages. Has an effect only if O(download_only)
      is specified.
  download_only:
    type: bool
    default: 'no'
    description: Only download the packages, do not install them.
  enable_plugin:
    type: list
    default: []
    description: I(Plugin) name to enable for the install/update operation. The enabled plugin will not
      persist beyond the transaction.
  enablerepo:
    type: list
    default: []
    description: I(Repoid) of repositories to enable for the install/update operation. These repos will
      not persist beyond the transaction. When specifying multiple repos, separate them with a ",".
  exclude:
    type: list
    default: []
    description: Package name(s) to exclude when state=present, or latest. This can be a list or a comma
      separated string.
  install_repoquery:
    type: bool
    default: 'yes'
    description: This is effectively a no-op in DNF as it is not needed with DNF, but is an accepted parameter
      for feature parity/compatibility with the M(ansible.builtin.yum) module.
  install_weak_deps:
    type: bool
    default: 'yes'
    description: Will also install all packages linked by a weak dependency relation.
  installroot:
    type: str
    default: /
    description: Specifies an alternative installroot, relative to which all packages will be installed.
  list:
    type: str
    description: Various (non-idempotent) commands for usage with C(/usr/bin/ansible) and I(not) playbooks.
      Use M(ansible.builtin.package_facts) instead of the O(list) argument as a best practice.
  lock_timeout:
    type: int
    default: 30
    description: Amount of time to wait for the dnf lockfile to be freed.
  name:
    type: list
    default: []
    aliases:
    - pkg
    description: 'A package name or package specifier with version, like C(name-1.0). When using state=latest,
      this can be ''*'' which means run: dnf -y update. You can also pass a url or a local path to an
      rpm file. To operate on several packages this can accept a comma separated string of packages or
      a list of packages. Comparison operators for package version are valid here C(>), C(<), C(>=), C(<=).
      Example - C(name >= 1.0). Spaces around the operator are required. You can also pass an absolute
      path for a binary which is provided by the package to install. See examples for more information.'
  nobest:
    type: bool
    default: 'no'
    description: Set best option to False, so that transactions are not limited to best candidates only.
  releasever:
    type: str
    description: Specifies an alternative release from which all packages will be installed.
  security:
    type: bool
    default: 'no'
    description: If set to V(true), and O(state=latest) then only installs updates that have been marked
      security related. Note that, similar to C(dnf upgrade-minimal), this filter applies to dependencies
      as well.
  skip_broken:
    type: bool
    default: 'no'
    description: Skip all unavailable packages or packages with broken dependencies without raising an
      error. Equivalent to passing the --skip-broken option.
  sslverify:
    type: bool
    default: 'yes'
    description: Disables SSL validation of the repository server for this transaction. This should be
      set to V(false) if one of the configured repositories is using an untrusted or self-signed certificate.
  state:
    type: str
    choices:
    - absent
    - present
    - installed
    - removed
    - latest
    description: Whether to install (V(present), V(latest)), or remove (V(absent)) a package. Default
      is V(None), however in effect the default action is V(present) unless the O(autoremove) option is
      enabled for this module, then V(absent) is inferred.
  update_cache:
    type: bool
    default: 'no'
    aliases:
    - expire-cache
    description: Force dnf to check if cache is out of date and redownload if needed. Has an effect only
      if O(state) is V(present) or V(latest).
  update_only:
    type: bool
    default: 'no'
    description: When using latest, only update installed packages. Do not install packages. Has an effect
      only if O(state) is V(latest)
  use_backend:
    type: str
    default: auto
    choices:
    - auto
    - dnf4
    - dnf5
    description: By default, this module will select the backend based on the C(ansible_pkg_mgr) fact.
  validate_certs:
    type: bool
    default: 'yes'
    description: This only applies if using a https url as the source of the rpm. e.g. for localinstall.
      If set to V(false), the SSL certificates will not be validated. This should only set to V(false)
      used on personally controlled sites using self-signed certificates as it avoids verifying the source
      site.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Install the latest version of Apache\n  ansible.builtin.dnf:\n    name: httpd\n \
  \   state: latest\n\n- name: Install Apache >= 2.4\n  ansible.builtin.dnf:\n    name: httpd >= 2.4\n\
  \    state: present\n\n- name: Install the latest version of Apache and MariaDB\n  ansible.builtin.dnf:\n\
  \    name:\n      - httpd\n      - mariadb-server\n    state: latest\n\n- name: Remove the Apache package\n\
  \  ansible.builtin.dnf:\n    name: httpd\n    state: absent\n\n- name: Install the latest version of\
  \ Apache from the testing repo\n  ansible.builtin.dnf:\n    name: httpd\n    enablerepo: testing\n \
  \   state: present\n\n- name: Upgrade all packages\n  ansible.builtin.dnf:\n    name: \"*\"\n    state:\
  \ latest\n\n- name: Update the webserver, depending on which is installed on the system. Do not install\
  \ the other one\n  ansible.builtin.dnf:\n    name:\n      - httpd\n      - nginx\n    state: latest\n\
  \    update_only: yes\n\n- name: Install the nginx rpm from a remote repo\n  ansible.builtin.dnf:\n\
  \    name: 'http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm'\n\
  \    state: present\n\n- name: Install nginx rpm from a local file\n  ansible.builtin.dnf:\n    name:\
  \ /usr/local/src/nginx-release-centos-6-0.el6.ngx.noarch.rpm\n    state: present\n\n- name: Install\
  \ Package based upon the file it provides\n  ansible.builtin.dnf:\n    name: /usr/bin/cowsay\n    state:\
  \ present\n\n- name: Install the 'Development tools' package group\n  ansible.builtin.dnf:\n    name:\
  \ '@Development tools'\n    state: present\n\n- name: Autoremove unneeded packages installed as dependencies\n\
  \  ansible.builtin.dnf:\n    autoremove: yes\n\n- name: Uninstall httpd but keep its dependencies\n\
  \  ansible.builtin.dnf:\n    name: httpd\n    state: absent\n    autoremove: no\n\n- name: Install a\
  \ modularity appstream with defined stream and profile\n  ansible.builtin.dnf:\n    name: '@postgresql:9.6/client'\n\
  \    state: present\n\n- name: Install a modularity appstream with defined stream\n  ansible.builtin.dnf:\n\
  \    name: '@postgresql:9.6'\n    state: present\n\n- name: Install a modularity appstream with defined\
  \ profile\n  ansible.builtin.dnf:\n    name: '@postgresql/client'\n    state: present\n"
