name: fail
fqcn: ansible.builtin.fail
collection: ansible.builtin
short_description: Fail with custom message
description: This module fails the progress with a custom message. It can be useful for bailing out when
  a certain condition is met using C(when). This module is also supported for Windows targets.
options:
  msg:
    type: str
    default: Failed as requested from task
    description: The customized message used for failing execution. If omitted, fail will simply bail
      out with a generic message.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Example using fail and when together\n  ansible.builtin.fail:\n    msg: The system\
  \ may not be provisioned according to the CMDB status.\n  when: cmdb_status != \"to-be-staged\"\n"
