- name: install-user-dirs.conf
  hosts: all
  become: true
  vars:
    dirs: []
    fallback_dir: "$HOME"
    locale_aware: true
    enable_custom_names: true
    _dest: "/etc/xdg/user-dirs.conf"
    _service: ""
    _packages:
      - "xdg-user-dirs"
  tasks:
    - name: Install User Dirs Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: user-dirs.conf.j2
        dest: "{{ _dest }}"
      vars:
        dirs: "{{ dirs }}"
        fallback_dir: "{{ fallback_dir }}"
        locale_aware: "{{ locale_aware }}"
        enable_custom_names: "{{ enable_custom_names }}"

    - name: Enable and restart User Dirs Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
