- name: install-certmonger.conf
  hosts: all
  become: true
  vars:
    cas: []
    debug: false
    state_dir: /var/lib/certmonger
    ca_cert_dir: /var/lib/certmonger/cas
    renewal_window: 30
    enable_autorenew: true
    max_tracking_cas: 0
    intermediate_cert_dir: /var/lib/certmonger/intermediates
    enable_tracking_daemon: true
    _dest: /etc/certmonger/certmonger.conf
    _service: ""
    _packages:
      - certmonger
  tasks:
    - name: Install Certmonger Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: certmonger.conf.j2
        dest: "{{ _dest }}"
        mode: '0644'
      vars:
        cas: "{{ cas }}"
        debug: "{{ debug }}"
        state_dir: "{{ state_dir }}"
        ca_cert_dir: "{{ ca_cert_dir }}"
        renewal_window: "{{ renewal_window }}"
        enable_autorenew: "{{ enable_autorenew }}"
        max_tracking_cas: "{{ max_tracking_cas }}"
        intermediate_cert_dir: "{{ intermediate_cert_dir }}"
        enable_tracking_daemon: "{{ enable_tracking_daemon }}"

    - name: Enable and restart Certmonger Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
