- name: install-update-initramfs.conf
  hosts: all
  become: true
  vars:
    ARCH: ""
    HOOKS: ""
    BACKUP: "1"
    UPDATE: "yes"
    BOOTDIR: "/boot"
    MODULES: ""
    VERBOSE: "0"
    COMPRESS: "gzip"
  tasks:
    - name: Install Update Initramfs Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: update-initramfs.conf.j2
        dest: "{{ _dest }}"
        mode: "0644"
      vars:
        ARCH: "{{ ARCH }}"
        HOOKS: "{{ HOOKS }}"
        BACKUP: "{{ BACKUP }}"
        UPDATE: "{{ UPDATE }}"
        BOOTDIR: "{{ BOOTDIR }}"
        MODULES: "{{ MODULES }}"
        VERBOSE: "{{ VERBOSE }}"
        COMPRESS: "{{ COMPRESS }}"

    - name: Enable and restart Update Initramfs Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
