- name: install-namespace.conf
  hosts: all
  become: true
  vars:
    _dest: "/etc/security/namespace.conf"
    _service: ""
    _packages:
      - "libpam-modules"
    poly_dirs: []
    home_template: "/home/polyinst."
    polyinstance_dir: "/tmp/polyinst."
    polyinstantiation_enabled: false
  tasks:
    - name: Install Namespace Conf
      ansible.builtin.apt:
        name: "{{ _packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Namespace Conf
      ansible.builtin.dnf:
        name: "{{ _packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Render configuration
      ansible.builtin.template:
        src: namespace.conf.j2
        dest: "{{ _dest }}"
        owner: root
        group: root
        mode: "0644"
      vars:
        poly_dirs: "{{ poly_dirs }}"
        home_template: "{{ home_template }}"
        polyinstance_dir: "{{ polyinstance_dir }}"
        polyinstantiation_enabled: "{{ polyinstantiation_enabled }}"

    - name: Enable and restart Namespace Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
