- name: install-host.conf
  hosts: all
  become: true
  vars:
    _dest: "/etc/host.conf"
    multi: false
    order: "files,bind"
    dnssec: false
    retries: 3
    timeout: 3
    _service: ""
    _packages: ["base-files"]
    ip4_first: false
  tasks:
    - name: Install Host Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: host.conf.j2
        dest: "{{ _dest }}"
      vars:
        multi: "{{ multi }}"
        order: "{{ order }}"
        dnssec: "{{ dnssec }}"
        retries: "{{ retries }}"
        timeout: "{{ timeout }}"
        ip4_first: "{{ ip4_first }}"

    - name: Enable and restart Host Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
