- name: install-caddy
  hosts: all
  become: true
  vars:
    _dest: /etc/caddy/Caddyfile
    _service: caddy
    _packages:
      - caddy
    admin_off: false
    acme_email: ""
    sites: []
  tasks:
    - name: Install Caddy Web Server
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: caddy.j2
        dest: "{{ _dest }}"
        owner: root
        group: root
        mode: "0644"
      vars:
        sites: "{{ sites }}"
        admin_off: "{{ admin_off }}"
        acme_email: "{{ acme_email }}"

    - name: Validate configuration
      ansible.builtin.command: caddy validate --adapter caddyfile --config /etc/caddy/Caddyfile

    - name: Enable and restart Caddy Web Server
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
