- name: install-libao.conf
  hosts: all
  become: true
  vars:
    _dest: "/etc/libao.conf"
    _service: ""
    _packages:
      - "libao-common"
    drivers:
      - driver: alsa
        options:
          - "global=1"
  tasks:
    - name: Install Libao Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: libao.conf.j2
        dest: "{{ _dest }}"
      vars:
        drivers: "{{ drivers }}"

    - name: Enable and restart Libao Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
