- name: install-limits.conf
  hosts: all
  become: true
  vars:
    _dest: "/etc/security/limits.conf"
    limits: []
    _service: ""
    _packages:
      - gamemode
      - libpam-modules
      - pipewire-bin
  tasks:
    - name: Install Limits Conf
      ansible.builtin.apt:
        name: "{{ _packages }}"
        state: present
        update_cache: true

    - name: Render configuration
      ansible.builtin.template:
        src: limits.conf.j2
        dest: "{{ _dest }}"
        owner: root
        group: root
        mode: "0644"
      vars:
        limits: "{{ limits }}"

    - name: Enable and restart Limits Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
