- name: install-geoclue.conf
  hosts: all
  become: true
  vars:
    _dest: "/etc/geoclue/geoclue.conf"
    enable: false
    _service: ""
    _packages:
      - "geoclue-2.0"
    log_level: 2
    log_domains: "all"
    time_server: "pool.ntp.org"
    allowed_apps: []
    gps_provider: true
    max_cache_age: 30
    geoip_provider: true
    log_destination: "systemd"
    network_provider: true
    log_uptime_format: "iso8601"
    min_time_between_updates: 5
    min_distance_between_updates: 10
  tasks:
    - name: Install Geoclue Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: geoclue.conf.j2
        dest: "{{ _dest }}"
        mode: '0644'
      vars:
        enable: "{{ enable }}"
        log_level: "{{ log_level }}"
        log_domains: "{{ log_domains }}"
        time_server: "{{ time_server }}"
        allowed_apps: "{{ allowed_apps }}"
        gps_provider: "{{ gps_provider }}"
        max_cache_age: "{{ max_cache_age }}"
        geoip_provider: "{{ geoip_provider }}"
        log_destination: "{{ log_destination }}"
        network_provider: "{{ network_provider }}"
        log_uptime_format: "{{ log_uptime_format }}"
        min_time_between_updates: "{{ min_time_between_updates }}"
        min_distance_between_updates: "{{ min_distance_between_updates }}"

    - name: Enable and restart Geoclue Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
