- name: install-libaudit.conf
  hosts: all
  become: true
  vars:
    _dest: "/etc/libaudit.conf"
    flush: "sync"
    local: true
    format: "epoch"
    legacy: false
    remote: false
    timeout: 60
    _service: ""
    log_file: "/var/log/audit/audit.log"
    num_logs: 5
    use_ayat: false
    _packages:
      - "libaudit-common"
    admin_msg: "Audit daemon unable to write to log"
    log_group: "adm"
    log_level: 2
    extra_rules: []
    remote_port: 6080
    max_log_file: 6
    remote_server: ""
    action_mail_acct: "root"
  tasks:
    - name: Install Libaudit Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: libaudit.conf.j2
        dest: "{{ _dest }}"
        mode: "0640"
        owner: root
        group: root
      vars:
        flush: "{{ flush }}"
        local: "{{ local }}"
        format: "{{ format }}"
        legacy: "{{ legacy }}"
        remote: "{{ remote }}"
        timeout: "{{ timeout }}"
        log_file: "{{ log_file }}"
        num_logs: "{{ num_logs }}"
        use_ayat: "{{ use_ayat }}"
        admin_msg: "{{ admin_msg }}"
        log_group: "{{ log_group }}"
        log_level: "{{ log_level }}"
        extra_rules: "{{ extra_rules }}"
        remote_port: "{{ remote_port }}"
        max_log_file: "{{ max_log_file }}"
        remote_server: "{{ remote_server }}"
        action_mail_acct: "{{ action_mail_acct }}"

    - name: Enable and restart Libaudit Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
