- name: install-networkd.conf
  hosts: all
  become: true
  vars:
    dhcp: "ipv6"
    mdns: "yes"
    _dest: "/etc/systemd/networkd.conf"
    llmnr: "yes"
    dnssec: "allow-downgrade"
    use_dns: "yes"
    use_ntp: "yes"
    emit_dns: "yes"
    emit_ntp: "yes"
    link_mac: ""
    link_mtu: 0
    link_name: ""
    mtu_bytes: 0
    mac_policy: "persistent"
    max_routes: 0
    emit_router: "yes"
    use_domains: "yes"
    accept_rdnss: "yes"
    dns_over_tls: "no"
    use_timezone: "yes"
    default_route: "yes"
    emit_timezone: "yes"
    send_hostname: "yes"
    carry_over_mac: "yes"
    dhcpv4_use_dns: "yes"
    dhcpv4_use_ntp: "yes"
    dhcpv6_use_dns: "yes"
    dhcpv6_use_ntp: "yes"
    ipv6_hop_limit: 64
    max_dns_servers: 3
    max_ntp_servers: 0
    request_options: ""
    activation_policy: "up"
    dhcpv6_use_prefix: "yes"
    send_vendor_class: "yes"
    dhcpv4_use_domains: "yes"
    dhcpv6_use_address: "yes"
    dhcpv6_use_domains: "yes"
    dhcpv4_use_timezone: "yes"
    ipv6_route_priority: 0
    dhcpv4_default_route: "yes"
    link_local_addressing: "yes"
    ipv6_accept_ra_enabled: "yes"
    ipv6_accept_ra_use_dns: "yes"
    ipv6_accept_ra_use_mtu: "yes"
    ipv6_accept_ra_use_ntp: "yes"
    ipv6_accept_ra_route_table: 0
    ipv6_accept_ra_use_address: "yes"
    ipv6_accept_ra_use_domains: "yes"
    ipv6_accept_ra_route_metric: 1024
    ipv6_accept_ra_default_route: "yes"
    ipv6_accept_ra_use_hop_limit: "yes"
    _packages:
      - systemd
    _service: ""
  tasks:
    - name: Install Networkd Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: networkd.conf.j2
        dest: "{{ _dest }}"
      vars:
        dhcp: "{{ dhcp }}"
        mdns: "{{ mdns }}"
        llmnr: "{{ llmnr }}"
        dnssec: "{{ dnssec }}"
        use_dns: "{{ use_dns }}"
        use_ntp: "{{ use_ntp }}"
        emit_dns: "{{ emit_dns }}"
        emit_ntp: "{{ emit_ntp }}"
        link_mac: "{{ link_mac }}"
        link_mtu: "{{ link_mtu }}"
        link_name: "{{ link_name }}"
        mtu_bytes: "{{ mtu_bytes }}"
        mac_policy: "{{ mac_policy }}"
        max_routes: "{{ max_routes }}"
        emit_router: "{{ emit_router }}"
        use_domains: "{{ use_domains }}"
        accept_rdnss: "{{ accept_rdnss }}"
        dns_over_tls: "{{ dns_over_tls }}"
        use_timezone: "{{ use_timezone }}"
        default_route: "{{ default_route }}"
        emit_timezone: "{{ emit_timezone }}"
        send_hostname: "{{ send_hostname }}"
        carry_over_mac: "{{ carry_over_mac }}"
        dhcpv4_use_dns: "{{ dhcpv4_use_dns }}"
        dhcpv4_use_ntp: "{{ dhcpv4_use_ntp }}"
        dhcpv6_use_dns: "{{ dhcpv6_use_dns }}"
        dhcpv6_use_ntp: "{{ dhcpv6_use_ntp }}"
        ipv6_hop_limit: "{{ ipv6_hop_limit }}"
        max_dns_servers: "{{ max_dns_servers }}"
        max_ntp_servers: "{{ max_ntp_servers }}"
        request_options: "{{ request_options }}"
        activation_policy: "{{ activation_policy }}"
        dhcpv6_use_prefix: "{{ dhcpv6_use_prefix }}"
        send_vendor_class: "{{ send_vendor_class }}"
        dhcpv4_use_domains: "{{ dhcpv4_use_domains }}"
        dhcpv6_use_address: "{{ dhcpv6_use_address }}"
        dhcpv6_use_domains: "{{ dhcpv6_use_domains }}"
        dhcpv4_use_timezone: "{{ dhcpv4_use_timezone }}"
        ipv6_route_priority: "{{ ipv6_route_priority }}"
        dhcpv4_default_route: "{{ dhcpv4_default_route }}"
        link_local_addressing: "{{ link_local_addressing }}"
        ipv6_accept_ra_enabled: "{{ ipv6_accept_ra_enabled }}"
        ipv6_accept_ra_use_dns: "{{ ipv6_accept_ra_use_dns }}"
        ipv6_accept_ra_use_mtu: "{{ ipv6_accept_ra_use_mtu }}"
        ipv6_accept_ra_use_ntp: "{{ ipv6_accept_ra_use_ntp }}"
        ipv6_accept_ra_route_table: "{{ ipv6_accept_ra_route_table }}"
        ipv6_accept_ra_use_address: "{{ ipv6_accept_ra_use_address }}"
        ipv6_accept_ra_use_domains: "{{ ipv6_accept_ra_use_domains }}"
        ipv6_accept_ra_route_metric: "{{ ipv6_accept_ra_route_metric }}"
        ipv6_accept_ra_default_route: "{{ ipv6_accept_ra_default_route }}"
        ipv6_accept_ra_use_hop_limit: "{{ ipv6_accept_ra_use_hop_limit }}"

    - name: Enable and restart Networkd Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
