- name: install-journald.conf
  hosts: all
  become: true
  vars:
    seal: false
    audit: false
    color: true
    storage: "auto"
    boot_ids: 0
    compress: true
    stream_path: "/run/systemd/journal/stdout"
    max_file_sec: "2weeks"
    show_boot_id: true
    stream_socket: "/run/systemd/journal/stdout"
    syslog_socket: "/run/systemd/journal/syslog"
    console_format: "verbose"
    remote_servers: []
    system_max_use: "100M"
    forward_to_kmsg: false
    header_checksum: false
    max_level_store: "info"
    runtime_max_use: "10%"
    rate_limit_burst: 10000
    system_keep_free: "10%"
    system_max_files: 0
    forward_to_syslog: false
    max_retention_sec: "1month"
    runtime_directory: ""
    runtime_keep_free: "15%"
    runtime_max_files: 0
    sync_interval_sec: 0
    forward_to_console: false
    system_max_file_size: "10G"
    runtime_max_file_size: "1G"
    write_kernel_messages: true
    write_service_messages: true
    rate_limit_interval_sec: 30
    write_user_session_messages: true
  tasks:
    - name: Install Journald Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: journald.conf.j2
        dest: "{{ _dest }}"
      vars:
        seal: "{{ seal }}"
        audit: "{{ audit }}"
        color: "{{ color }}"
        storage: "{{ storage }}"
        boot_ids: "{{ boot_ids }}"
        compress: "{{ compress }}"
        stream_path: "{{ stream_path }}"
        max_file_sec: "{{ max_file_sec }}"
        show_boot_id: "{{ show_boot_id }}"
        stream_socket: "{{ stream_socket }}"
        syslog_socket: "{{ syslog_socket }}"
        console_format: "{{ console_format }}"
        remote_servers: "{{ remote_servers }}"
        system_max_use: "{{ system_max_use }}"
        forward_to_kmsg: "{{ forward_to_kmsg }}"
        header_checksum: "{{ header_checksum }}"
        max_level_store: "{{ max_level_store }}"
        runtime_max_use: "{{ runtime_max_use }}"
        rate_limit_burst: "{{ rate_limit_burst }}"
        system_keep_free: "{{ system_keep_free }}"
        system_max_files: "{{ system_max_files }}"
        forward_to_syslog: "{{ forward_to_syslog }}"
        max_retention_sec: "{{ max_retention_sec }}"
        runtime_directory: "{{ runtime_directory }}"
        runtime_keep_free: "{{ runtime_keep_free }}"
        runtime_max_files: "{{ runtime_max_files }}"
        sync_interval_sec: "{{ sync_interval_sec }}"
        forward_to_console: "{{ forward_to_console }}"
        system_max_file_size: "{{ system_max_file_size }}"
        runtime_max_file_size: "{{ runtime_max_file_size }}"
        write_kernel_messages: "{{ write_kernel_messages }}"
        write_service_messages: "{{ write_service_messages }}"
        rate_limit_interval_sec: "{{ rate_limit_interval_sec }}"
        write_user_session_messages: "{{ write_user_session_messages }}"

    - name: Enable and restart Journald Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
