- name: install-capability.conf
  hosts: all
  become: true
  vars:
    _dest: "/etc/security/capability.conf"
    entries: []
    _service: ""
    _packages: ["libpam-cap"]
  tasks:
    - name: Install Capability Conf
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: present

    - name: Render configuration
      ansible.builtin.template:
        src: capability.conf.j2
        dest: "{{ _dest }}"
      vars:
        entries: "{{ entries }}"

    - name: Enable and restart Capability Conf
      ansible.builtin.service:
        name: "{{ _service }}"
        state: restarted
        enabled: true
      when: _service | length > 0
