// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type collectorEvent struct {
	_             structs.HostLayout
	Type          uint32
	Pid           uint32
	Comm          [16]uint8
	Saddr         uint32
	Daddr         uint32
	Sport         uint16
	Dport         uint16
	Oldstate      uint8
	Newstate      uint8
	_             [2]byte
	ConnLatencyNs uint64
	Filename      [128]uint8
	DiskDev       uint32
	_             [4]byte
	DiskSector    uint64
	DiskNrSector  uint32
	_             [4]byte
	DiskLatencyNs uint64
	DiskRwbs      [8]uint8
	DiskError     int32
	_             [4]byte
}

type collectorIoKey struct {
	_      structs.HostLayout
	Dev    uint32
	_      [4]byte
	Sector uint64
}

type collectorIoStartVal struct {
	_    structs.HostLayout
	TsNs uint64
	Pid  uint32
	Comm [16]uint8
	_    [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	collectorMapConnStart              = "conn_start"
	collectorMapEvents                 = "events"
	collectorMapIoStart                = "io_start"
	collectorProgTraceBlockRqComplete  = "trace_block_rq_complete"
	collectorProgTraceBlockRqIssue     = "trace_block_rq_issue"
	collectorProgTraceInetSockSetState = "trace_inet_sock_set_state"
	collectorProgTraceSchedProcessExec = "trace_sched_process_exec"
	collectorVarUnusedEventBtfAnchor   = "unused_event_btf_anchor"
)

// loadCollector returns the embedded CollectionSpec for collector.
func loadCollector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CollectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load collector: %w", err)
	}

	return spec, err
}

// loadCollectorObjects loads collector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*collectorObjects
//	*collectorPrograms
//	*collectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCollectorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadCollector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// collectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorSpecs struct {
	collectorProgramSpecs
	collectorMapSpecs
	collectorVariableSpecs
}

// collectorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorProgramSpecs struct {
	TraceBlockRqComplete  *ebpf.ProgramSpec `ebpf:"trace_block_rq_complete"`
	TraceBlockRqIssue     *ebpf.ProgramSpec `ebpf:"trace_block_rq_issue"`
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
	TraceSchedProcessExec *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
}

// collectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorMapSpecs struct {
	ConnStart *ebpf.MapSpec `ebpf:"conn_start"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	IoStart   *ebpf.MapSpec `ebpf:"io_start"`
}

// collectorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorVariableSpecs struct {
	UnusedEventBtfAnchor *ebpf.VariableSpec `ebpf:"unused_event_btf_anchor"`
}

// collectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorObjects struct {
	collectorPrograms
	collectorMaps
	collectorVariables
}

func (o *collectorObjects) Close() error {
	return _CollectorClose(
		&o.collectorPrograms,
		&o.collectorMaps,
	)
}

// collectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorMaps struct {
	ConnStart *ebpf.Map `ebpf:"conn_start"`
	Events    *ebpf.Map `ebpf:"events"`
	IoStart   *ebpf.Map `ebpf:"io_start"`
}

func (m *collectorMaps) Close() error {
	return _CollectorClose(
		m.ConnStart,
		m.Events,
		m.IoStart,
	)
}

// collectorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorVariables struct {
	UnusedEventBtfAnchor *ebpf.Variable `ebpf:"unused_event_btf_anchor"`
}

// collectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorPrograms struct {
	TraceBlockRqComplete  *ebpf.Program `ebpf:"trace_block_rq_complete"`
	TraceBlockRqIssue     *ebpf.Program `ebpf:"trace_block_rq_issue"`
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
}

func (p *collectorPrograms) Close() error {
	return _CollectorClose(
		p.TraceBlockRqComplete,
		p.TraceBlockRqIssue,
		p.TraceInetSockSetState,
		p.TraceSchedProcessExec,
	)
}

func _CollectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed collector_x86_bpfel.o
var _CollectorBytes []byte
