#!/usr/bin/env bash
# Publish the built repository tree to the gh-pages branch, which is what makes the apt/dnf URL real.
#
# A WORKTREE, not a branch switch: this repo has a 3 GB working tree (5474 template directories, the config
# catalog) and checking out an orphan branch over it would be slow and would leave every untracked build
# artifact in the way. `git worktree` gives gh-pages its own directory and leaves the working tree alone.
#
# The branch is REPLACED, not appended to: a package repository is a snapshot of what is currently offered,
# and keeping every past tree in the history of a Pages branch is how a 100 MB package becomes a 2 GB clone.
# --orphan on the first run, and a single commit per publish after that.
#
#   scripts/publish-repo.sh
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"
REPO="$ROOT/deploy-artifacts/repo"
VERSION="$(cat VERSION)"
[ -f "$REPO/index.html" ] || { echo "no repo tree — run scripts/build-repo.sh first" >&2; exit 1; }

WORK="$ROOT/deploy-artifacts/gh-pages"
rm -rf "$WORK"
git worktree remove --force "$WORK" 2>/dev/null || true

if git ls-remote --exit-code --heads origin gh-pages >/dev/null 2>&1; then
  git worktree add -f "$WORK" gh-pages 2>/dev/null || {
    git fetch origin gh-pages:gh-pages
    git worktree add -f "$WORK" gh-pages
  }
  ( cd "$WORK" && git rm -rq . 2>/dev/null || true )
else
  git worktree add -f --detach "$WORK"
  ( cd "$WORK" && git checkout --orphan gh-pages && git rm -rq --cached . 2>/dev/null || true )
  find "$WORK" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
fi

cp -r "$REPO"/. "$WORK"/
# GitHub Pages runs Jekyll by default, which SKIPS files and directories starting with an underscore and can
# mangle others. A package repository must be served byte for byte.
touch "$WORK/.nojekyll"

cd "$WORK"
git add -A
if git diff --cached --quiet; then
  echo ">> nothing changed"
else
  git commit -q -m "repository: yoloman-agent + yoloman-bossman ${VERSION}

Generated by scripts/build-repo.sh and published by scripts/publish-repo.sh. Signed APT Release
(InRelease + Release.gpg) and repomd.xml; the public key is yoloman-archive-keyring.asc.

This branch is REPLACED on every publish — it is a snapshot of what is currently offered, not a history."
  git push -f origin gh-pages
fi
cd "$ROOT"
git worktree remove --force "$WORK"
echo ">> published — enable Pages for the gh-pages branch once, then:"
echo "   https://imoes.github.io/yoloman/deb   https://imoes.github.io/yoloman/rpm"
