#!/usr/bin/env bash
# Publish the built repository tree to the PACKAGE repository, which is what makes the apt/dnf URL real.
#
# A SEPARATE REPOSITORY, not a gh-pages branch of the code. A branch holding 250 MB of packages is dragged
# along by every `git clone` of the source: measured, a full clone went from 74 MB to 302 MB the moment
# gh-pages existed. Packages are release artifacts, not source history, and they belong in their own place —
# which also means the code repository's size stays a function of the code.
#
# The branch there is REPLACED on every publish: a package repository is a snapshot of what is currently
# offered, not a history that should grow by 100 MB per release.
#
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"
REPO="$ROOT/deploy-artifacts/repo"
VERSION="$(cat VERSION)"
[ -f "$REPO/index.html" ] || { echo "no repo tree — run scripts/build-repo.sh first" >&2; exit 1; }

WORK="$ROOT/deploy-artifacts/pkgrepo"
PKG_REMOTE="${YOLOMAN_PKG_REMOTE:-https://github.com/imoes/yoloman-packages.git}"
PKG_BRANCH="${YOLOMAN_PKG_BRANCH:-main}"

rm -rf "$WORK"
mkdir -p "$WORK"
cd "$WORK"
git init -q -b "$PKG_BRANCH"
cp -r "$REPO"/. .
# GitHub Pages runs Jekyll by default, which SKIPS files and directories starting with an underscore and can
# mangle others. A package repository must be served byte for byte.
touch .nojekyll
git add -A
git -c user.name="yoloman packaging" -c user.email="yoloman@users.noreply.github.com" \
  commit -q -m "repository: yoloman-agent + yoloman-bossman ${VERSION}

Generated by scripts/build-repo.sh and published by scripts/publish-repo.sh. Signed APT Release (InRelease
+ Release.gpg) and repomd.xml; the public key is yoloman-archive-keyring.asc.

This branch is REPLACED on every publish — it is a snapshot of what is currently offered, not a history."
git remote add origin "$PKG_REMOTE"
git push -f -q origin "$PKG_BRANCH"
cd "$ROOT"
echo ">> published to $PKG_REMOTE ($PKG_BRANCH)"
echo "   https://imoes.github.io/yoloman-packages/deb   https://imoes.github.io/yoloman-packages/rpm"
