"""The package catalog (Block 0): the installation wizard + Roles & Features
snap-in read this to know which configurable server packages exist, their
per-family package names / service / config path, and whether a config template
(the wizard's Configure step) is available. Static data file, generated by
scripts/build_package_catalog.py."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends

from bossman.api.auth import get_current_identity
from bossman.config import Settings, get_settings

router = APIRouter()


def _catalog_path(settings: Settings) -> Path:
    # config_templates_dir is .../configs/config_templates → sibling file.
    return Path(settings.config_templates_dir).parent / "package_catalog.json"


@router.get("/api/v1/package-catalog")
async def get_package_catalog(
    settings: Settings = Depends(get_settings),
    _identity=Depends(get_current_identity),
) -> dict[str, Any]:
    """{packages: {name: {label, category, icon, description, template,
    validate_cmd?, families:{debian,redhat:{packages,service,config_path}}}}}."""
    path = _catalog_path(settings)
    if not path.is_file():
        return {"packages": {}}
    try:
        return {"packages": json.loads(path.read_text())}
    except (OSError, ValueError):
        return {"packages": {}}
