name: rhel_rpm_ostree
fqcn: ansible.posix.rhel_rpm_ostree
collection: ansible.posix
short_description: Ensure packages exist in a RHEL for Edge rpm-ostree based system
description: Compatibility layer for using the "package" module for RHEL for Edge systems utilizing the
  RHEL System Roles.
options:
  name:
    type: list
    default: []
    aliases:
    - pkg
    description: A package name or package specifier with version, like C(name-1.0). Comparison operators
      for package version are valid here C(>), C(<), C(>=), C(<=). Example - C(name>=1.0) If a previous
      version is specified, the task also needs to turn C(allow_downgrade) on. See the C(allow_downgrade)
      documentation for caveats with downgrading packages. When using state=latest, this can be C('*')
      which means run C(yum -y update). You can also pass a url or a local path to a rpm file (using state=present).
      To operate on several packages this can accept a comma separated string of packages or (as of 2.0)
      a list of packages.
  state:
    type: str
    choices:
    - absent
    - installed
    - latest
    - present
    - removed
    description: Whether to install (C(present) or C(installed), C(latest)), or remove (C(absent) or C(removed))
      a package. C(present) and C(installed) will simply ensure that a desired package is installed. C(latest)
      will update the specified package if it's not of the latest available version. C(absent) and C(removed)
      will remove the specified package. Default is C(None), however in effect the default action is C(present)
      unless the C(autoremove) option is enabled for this module, then C(absent) is inferred.
writes: true
runtime: starlark
source: translated
examples: "\n- name: Ensure htop and ansible are installed on rpm-ostree based RHEL\n  ansible.posix.rhel_rpm_ostree:\n\
  \    name:\n      - htop\n      - ansible\n    state: present\n"
