name: seboolean
fqcn: ansible.posix.seboolean
collection: ansible.posix
short_description: Toggles SELinux booleans
description: Toggles SELinux booleans.
options:
  ignore_selinux_state:
    type: bool
    default: false
    description: Useful for scenarios (chrooted environment) that you can't get the real SELinux state.
  name:
    type: str
    required: true
    description: Name of the boolean to configure.
  persistent:
    type: bool
    default: false
    description: Set to C(true) if the boolean setting should survive a reboot.
  state:
    type: bool
    required: true
    description: Desired boolean value
writes: true
runtime: starlark
source: translated
examples: "\n- name: Set httpd_can_network_connect flag on and keep it persistent across reboots\n  ansible.posix.seboolean:\n\
  \    name: httpd_can_network_connect\n    state: true\n    persistent: true\n"
