#!/bin/sh
case "$1" in
  --state) [ "${FIREWALLD_STATE:-dead}" = running ] && exit 0 || exit 252 ;;
  --get-default-zone) echo public; exit 0 ;;
  *) echo "firewall-cmd $*" >> "$FWLOG"; exit 0 ;;
esac
